#!/usr/bin/env python3
"""Generate server catalog entries and PR templates for community contributions."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

VALID_CATEGORIES = [
    "developer-tools", "database", "communication", "productivity",
    "cloud-infra", "ai-ml", "data", "cms-content", "finance",
    "observability", "search", "auth", "storage", "version-control", "browser",
]

VALID_TRANSPORTS = ["stdio", "http"]

VALID_INSTALL_METHODS = ["npx", "npm", "uvx", "pip", "http", "docker"]


def load_existing_ids(base_dir: str) -> set:
    path = Path(base_dir) / "assets" / "known_servers.json"
    try:
        with open(path) as f:
            data = json.load(f)
        return {s["id"] for s in data["servers"]}
    except (FileNotFoundError, json.JSONDecodeError, KeyError):
        return set()


def validate_entry(entry: dict, existing_ids: set) -> list[str]:
    """Validate a server entry and return list of errors."""
    errors = []

    if not entry.get("id"):
        errors.append("Missing required field: id")
    elif entry["id"] in existing_ids:
        errors.append(f"Server ID '{entry['id']}' already exists in the catalog")

    if not entry.get("displayName"):
        errors.append("Missing required field: displayName")

    if not entry.get("description"):
        errors.append("Missing required field: description")

    if not entry.get("package"):
        errors.append("Missing required field: package")

    categories = entry.get("categories", [])
    for cat in categories:
        if cat not in VALID_CATEGORIES:
            errors.append(f"Invalid category: '{cat}'. Valid: {', '.join(VALID_CATEGORIES)}")

    transport = entry.get("transport", "stdio")
    if transport not in VALID_TRANSPORTS:
        errors.append(f"Invalid transport: '{transport}'. Valid: {', '.join(VALID_TRANSPORTS)}")

    method = entry.get("installMethod", "")
    if method not in VALID_INSTALL_METHODS:
        errors.append(f"Invalid installMethod: '{method}'. Valid: {', '.join(VALID_INSTALL_METHODS)}")

    return errors


def build_entry(
    server_id: str,
    display_name: str,
    description: str,
    package: str,
    transport: str = "stdio",
    install_method: str = "npx",
    categories: list[str] | None = None,
    tags: list[str] | None = None,
    required_env: list[str] | None = None,
    required_env_links: dict | None = None,
    required_env_descriptions: dict | None = None,
) -> dict:
    return {
        "id": server_id,
        "displayName": display_name,
        "description": description,
        "categories": categories or [],
        "transport": transport,
        "installMethod": install_method,
        "package": package,
        "args": [],
        "requiredEnv": required_env or [],
        "requiredEnvLinks": required_env_links or {},
        "requiredEnvDescriptions": required_env_descriptions or {},
        "optionalEnv": [],
        "verified": False,
        "popularity": 0,
        "tags": tags or [],
    }


def generate_pr_template(entry: dict) -> str:
    return f"""## Add {entry['displayName']} MCP Server

### Server Details
- **ID:** `{entry['id']}`
- **Package:** `{entry['package']}`
- **Transport:** {entry['transport']}
- **Install Method:** {entry['installMethod']}
- **Categories:** {', '.join(entry['categories']) if entry['categories'] else 'None'}

### Description
{entry['description']}

### Testing Checklist
- [ ] Server installs successfully via `{entry['installMethod']}`
- [ ] Config entry works in OpenClaw / Claude Code
- [ ] All required env vars are documented
- [ ] Health check passes (if applicable)

### Auth Requirements
{chr(10).join(f'- `{var}`' for var in entry['requiredEnv']) if entry['requiredEnv'] else 'None'}

---
Generated by MCP Marketplace Skill
"""


def main():
    parser = argparse.ArgumentParser(description="Generate server catalog entries for contribution")
    parser.add_argument("--id", required=True, help="Server ID (lowercase, hyphenated)")
    parser.add_argument("--display-name", required=True, help="Display name")
    parser.add_argument("--description", required=True, help="Server description")
    parser.add_argument("--package", required=True, help="Package name")
    parser.add_argument("--transport", default="stdio", choices=VALID_TRANSPORTS)
    parser.add_argument("--install-method", default="npx", choices=VALID_INSTALL_METHODS)
    parser.add_argument("--categories", default=None, help="Comma-separated categories")
    parser.add_argument("--tags", default=None, help="Comma-separated tags")
    parser.add_argument("--required-env", default=None, help="Comma-separated required env vars")
    parser.add_argument("--required-env-links", default=None, help="JSON object of env var links")
    parser.add_argument("--required-env-descriptions", default=None, help="JSON object of env var descriptions")
    args = parser.parse_args()

    base_dir = Path(__file__).resolve().parent.parent
    existing_ids = load_existing_ids(str(base_dir))

    categories = [c.strip() for c in args.categories.split(",")] if args.categories else []
    tags = [t.strip() for t in args.tags.split(",")] if args.tags else []
    required_env = [e.strip() for e in args.required_env.split(",")] if args.required_env else []

    try:
        env_links = json.loads(args.required_env_links) if args.required_env_links else {}
    except json.JSONDecodeError:
        env_links = {}

    try:
        env_descriptions = json.loads(args.required_env_descriptions) if args.required_env_descriptions else {}
    except json.JSONDecodeError:
        env_descriptions = {}

    entry = build_entry(
        server_id=args.id,
        display_name=args.display_name,
        description=args.description,
        package=args.package,
        transport=args.transport,
        install_method=args.install_method,
        categories=categories,
        tags=tags,
        required_env=required_env,
        required_env_links=env_links,
        required_env_descriptions=env_descriptions,
    )

    errors = validate_entry(entry, existing_ids)

    output = {
        "action": "contribute",
        "valid": len(errors) == 0,
        "validationErrors": errors,
        "serverEntry": entry,
        "prTitle": f"Add {entry['displayName']} MCP server",
        "prBody": generate_pr_template(entry),
    }
    json.dump(output, sys.stdout, indent=2)
    print()

    if errors:
        sys.exit(1)


if __name__ == "__main__":
    main()
