#!/usr/bin/env python3
"""
AI Meeting Helper - 会议纪要生成器
使用 Whisper API 转录音频，并用 LLM 生成结构化会议纪要
"""

import os
import sys
import json
import argparse
import logging
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

# 加载环境变量
BASE_DIR = Path(__file__).parent.parent
load_dotenv(BASE_DIR / ".env")

# 设置日志
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# 检查 API Key
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    logger.error("未设置 OPENAI_API_KEY，请编辑 .env 文件")
    sys.exit(1)

try:
    from openai import OpenAI
    client = OpenAI(api_key=OPENAI_API_KEY)
except ImportError:
    logger.error("未安装 openai 库，运行：pip install openai")
    sys.exit(1)


def transcribe_audio(audio_path, model="base"):
    """使用 Whisper API 转录音频"""
    logger.info(f"🎙️  转录音频: {audio_path} (模型: {model})")

    try:
        with open(audio_path, "rb") as audio_file:
            transcript = client.audio.transcriptions.create(
                model="whisper-1",
                file=audio_file,
                response_format="text"
            )
        return transcript
    except Exception as e:
        logger.error(f"转录失败: {e}")
        return None


def summarize_transcript(transcript, llm_model="gpt-4o-mini"):
    """使用 LLM 总结会议内容"""
    logger.info(f"🤖 生成会议纪要 (模型: {llm_model})")

    prompt = f"""你是一个专业的会议纪要助手。请将以下会议转录文本整理为结构化纪要。

转录文本：
{transcript}

请输出以下格式（JSON）：
{{
  "date": "会议日期（如未知则写今天）",
  "duration": "预估时长",
  "participants": 人数（整数）,
  "summary": "会议核心内容摘要（2-3句话）",
  "action_items": [
    {{"assignee": "负责人", "task": "任务", "due": "截止日期"}},
    ...
  ],
  "decisions": ["决策点1", "决策点2", ...],
  "todo": ["待办事项1", "待办事项2", ...]
}}

注意：
- 如果无法确定某些信息，请用合理值或留空
- 行动项和待办事项要清晰可执行
- 日期格式：YYYY-MM-DD 或相对日期
"""

    try:
        response = client.chat.completions.create(
            model=llm_model,
            messages=[
                {"role": "system", "content": "你是一个专业的会议纪要助手，擅长从对话中提取结构化的会议信息。"},
                {"role": "user", "content": prompt}
            ],
            response_format={"type": "json_object"},
            temperature=0.3
        )
        result = json.loads(response.choices[0].message.content)
        return result
    except Exception as e:
        logger.error(f"总结失败: {e}")
        return None


def format_markdown(meeting_data, audio_filename):
    """将会议数据格式化为 Markdown"""
    date = meeting_data.get("date", datetime.now().strftime("%Y-%m-%d"))
    duration = meeting_data.get("duration", "未知")
    participants = meeting_data.get("participants", "未知")
    summary = meeting_data.get("summary", "无摘要")
    action_items = meeting_data.get("action_items", [])
    decisions = meeting_data.get("decisions", [])
    todo = meeting_data.get("todo", [])

    md = f"""# 会议纪要

📅 **日期**：{date}
⏱️ **时长**：{duration}
👥 **参会人数**：{participants}
🎙️ **录音文件**：{audio_filename}

## 💡 摘要

{summary}

## ✅ 行动项

"""
    if action_items:
        for i, item in enumerate(action_items, 1):
            assignee = item.get("assignee", "未指定")
            task = item.get("task", "")
            due = item.get("due", "")
            md += f"{i}. **{assignee}**: {task}"
            if due:
                md += f"（截止：{due}）"
            md += "\n"
    else:
        md += "暂无行动项\n"

    md += "\n## 📢 决策点\n\n"
    if decisions:
        for d in decisions:
            md += f"- {d}\n"
    else:
        md += "暂无决策点\n"

    md += "\n## 📝 待办事项\n\n"
    if todo:
        for t in todo:
            md += f"- [ ] {t}\n"
    else:
        md += "暂无待办事项\n"

    md += f"\n---\n* Generated by AI Meeting Helper on {datetime.now().strftime('%Y-%m-%d %H:%M')} *\n"
    return md


def process_single_file(audio_path, output_path=None, format="markdown", model="base", llm_model="gpt-4o-mini", backup=False, preview=False):
    """处理单个音频文件"""
    audio_path = Path(audio_path)
    if not audio_path.exists():
        logger.error(f"文件不存在: {audio_path}")
        return False

    # 备份
    if backup and not preview:
        backup_dir = BASE_DIR / ".ai_meeting_backup"
        backup_dir.mkdir(exist_ok=True)
        backup_file = backup_dir / f"{audio_path.stem}_{datetime.now().strftime('%Y%m%d_%H%M%S')}{audio_path.suffix}"
        import shutil
        shutil.copy2(audio_path, backup_file)
        logger.info(f"📦 已备份: {backup_file}")

    # 1. 转录
    transcript = transcribe_audio(audio_path, model)
    if not transcript:
        return False

    # 2. 总结
    meeting_data = summarize_transcript(transcript, llm_model)
    if not meeting_data:
        return False

    # 3. 格式化输出
    if format == "markdown":
        content = format_markdown(meeting_data, audio_path.name)
    elif format == "json":
        content = json.dumps(meeting_data, ensure_ascii=False, indent=2)
    else:  # text
        content = f"会议纪要\n\n{meeting_data.get('summary', '')}\n\n行动项: {meeting_data.get('action_items', [])}"

    # 4. 预览或保存
    if preview:
        print("\n" + "="*50)
        print("预览模式 - 会议纪要：")
        print("="*50)
        print(content)
        print("="*50)
        logger.info("预览模式完成，未生成文件")
    else:
        if not output_path:
            output_path = audio_path.with_suffix(f".meeting.{format if format != 'markdown' else 'md'}")
        else:
            output_path = Path(output_path)
            if output_path.is_dir():
                output_path = output_path / f"{audio_path.stem}.meeting.{format if format != 'markdown' else 'md'}"

        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info(f"✅ 纪要已保存: {output_path}")

    return True


def batch_process(folder, output_dir=None, format="markdown", model="base", llm_model="gpt-4o-mini", backup=False, preview=False):
    """批量处理文件夹中的音频文件"""
    folder = Path(folder)
    if not folder.exists():
        logger.error(f"文件夹不存在: {folder}")
        return

    if not output_dir:
        output_dir = folder
    else:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

    # 支持的音频格式
    audio_extensions = {".mp3", ".wav", ".m4a", ".flac", ".ogg", ".mp4", ".mov", ".avi"}

    files = [f for f in folder.rglob("*") if f.suffix.lower() in audio_extensions]
    logger.info(f"发现 {len(files)} 个音频文件")

    success_count = 0
    for audio_file in files:
        logger.info(f"处理: {audio_file.name}")
        if process_single_file(audio_file, output_dir / audio_file.stem, format, model, llm_model, backup, preview):
            success_count += 1

    logger.info(f"批量处理完成: {success_count}/{len(files)} 成功")


def main():
    parser = argparse.ArgumentParser(
        description="AI Meeting Helper - 会议纪要生成器",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例：
  ai-meeting-helper process meeting.mp3
  ai-meeting-helper process meeting.mp3 --output notes.md --format markdown
  ai-meeting-helper batch ./meetings/ --output ./notes/ --backup
  ai-meeting-helper process meeting.mp3 --preview  # 预览模式
        """
    )

    subparsers = parser.add_subparsers(dest="command", help="命令")

    # process 命令
    process_parser = subparsers.add_parser("process", help="处理单个音频文件")
    process_parser.add_argument("input", help="输入音频文件路径")
    process_parser.add_argument("--output", "-o", help="输出文件路径")
    process_parser.add_argument("--format", "-f", choices=["markdown", "json", "text"], default="markdown", help="输出格式")
    process_parser.add_argument("--model", "-m", choices=["tiny", "base", "small", "medium", "large"], default="base", help="Whisper 模型")
    process_parser.add_argument("--llm-model", default="gpt-4o-mini", help="LLM 模型（gpt-4o/gpt-4o-mini）")
    process_parser.add_argument("--backup", action="store_true", help="启用备份")
    process_parser.add_argument("--preview", action="store_true", help="预览模式（不生成文件）")

    # batch 命令
    batch_parser = subparsers.add_parser("batch", help="批量处理文件夹")
    batch_parser.add_argument("input", help="输入文件夹路径")
    batch_parser.add_argument("--output", "-o", help="输出文件夹路径")
    batch_parser.add_argument("--format", "-f", choices=["markdown", "json", "text"], default="markdown", help="输出格式")
    batch_parser.add_argument("--model", "-m", choices=["tiny", "base", "small", "medium", "large"], default="base", help="Whisper 模型")
    batch_parser.add_argument("--llm-model", default="gpt-4o-mini", help="LLM 模型")
    batch_parser.add_argument("--backup", action="store_true", help="启用备份")
    batch_parser.add_argument("--preview", action="store_true", help="预览模式（不生成文件）")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return

    if args.command == "process":
        success = process_single_file(
            args.input,
            args.output,
            args.format,
            args.model,
            args.llm_model,
            args.backup,
            args.preview
        )
        sys.exit(0 if success else 1)

    elif args.command == "batch":
        batch_process(
            args.input,
            args.output,
            args.format,
            args.model,
            args.llm_model,
            args.backup,
            args.preview
        )


if __name__ == "__main__":
    main()