#!/usr/bin/env python3
"""ERPClaw OS — DGM (Darwin Godel Machine) Variant Engine (Phase 3, Deliverable 3c)

Performs evolutionary optimization for NON-FINANCIAL code only.
Generates code variants using template-based mutations, evaluates them
against existing test suites in sandbox, and selects the best performer.

CRITICAL SAFETY RULES:
- NEVER touches financial core files (gl_posting, stock_posting, tax_calculation, cross_skill)
- NEVER touches constitution/validation/sandbox/invariant-checker files
- NEVER modifies itself (dgm_engine.py)
- NEVER touches Tier 3 classified actions
- NEVER auto-deploys — always queues for human review via improvement_log
"""
import difflib
import json
import os
import sqlite3
import sys
import time
import uuid
from datetime import datetime, timezone
from decimal import Decimal, ROUND_HALF_UP

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

# Add shared lib to path
sys.path.insert(0, os.path.expanduser("~/.openclaw/erpclaw/lib"))

from erpclaw_lib.db import get_connection
from erpclaw_lib.query import (
    Q, P, Table, Field, Order, LiteralValue, insert_row, dynamic_update,
)

from variant_manager import (
    store_variant,
    compare_variants,
    select_best,
    cleanup_old_variants,
    get_variant_diff,
)
from tier_classifier import classify_action, TIER_3


# ---------------------------------------------------------------------------
# Safety Exclusion List — NEVER MODIFY THESE FILES
# ---------------------------------------------------------------------------

SAFETY_EXCLUDED_FILES = frozenset({
    "gl_posting.py",
    "stock_posting.py",
    "tax_calculation.py",
    "cross_skill.py",
    "constitution.py",
    "validate_module.py",
    "sandbox.py",
    "gl_invariant_checker.py",
    "dgm_engine.py",
    "adversarial_audit.py",
    "compliance_weather.py",
    "schema_migrator.py",       # Can DROP tables — must not be auto-mutated
    "tier_classifier.py",       # Changing tier = bypassing safety gates
    "improvement_log.py",       # Manipulating approval status = audit bypass
    "deploy_pipeline.py",       # Auto-deploy logic — mutation could skip gates
    "in_module_generator.py",   # Generator must not self-modify
})

# Actions that map to excluded files — resolved by checking the source file
SAFETY_EXCLUDED_MODULES = frozenset({
    "gl_posting",
    "stock_posting",
    "tax_calculation",
    "cross_skill",
    "schema_migrator",
    "tier_classifier",
    "improvement_log",
    "deploy_pipeline",
    "in_module_generator",
})

VALID_MUTATION_TYPES = (
    "query_optimization",
    "algorithm_change",
    "caching",
    "parameter_reorder",
    "data_structure",
    "batch_processing",
)


# ---------------------------------------------------------------------------
# Safety checks
# ---------------------------------------------------------------------------

def is_safety_excluded(module_name, action_name, source_file=None):
    """Check if an action/module is in the safety exclusion list.

    Args:
        module_name: module that owns the action
        action_name: kebab-case action name
        source_file: optional filename of the source (e.g., "gl_posting.py")

    Returns:
        tuple: (is_excluded: bool, reason: str or None)
    """
    # Check source file exclusion
    if source_file:
        basename = os.path.basename(source_file)
        if basename in SAFETY_EXCLUDED_FILES:
            return True, f"File '{basename}' is in the safety exclusion list"

    # Check module-level exclusion
    if module_name in SAFETY_EXCLUDED_MODULES:
        return True, f"Module '{module_name}' is safety-excluded (financial core)"

    # Check tier classification — Tier 3 actions are excluded
    classification = classify_action(action_name, module_name)
    if classification["tier"] == TIER_3:
        return True, f"Action '{action_name}' is classified as Tier 3 (human-only)"

    return False, None


# ---------------------------------------------------------------------------
# Variant generation (template-based mutations)
# ---------------------------------------------------------------------------

def _generate_variant_code(original_code, mutation_type, variant_number):
    """Generate a mutated variant of the original code.

    In production, this would use AST-level transformations. For now,
    we use template-based comment annotations to mark the mutation type,
    simulating the kind of changes each mutation would produce.

    Args:
        original_code: str — original source code
        mutation_type: str — one of VALID_MUTATION_TYPES
        variant_number: int — variant index (for deterministic differentiation)

    Returns:
        str: mutated source code
    """
    header = (
        f"# DGM Variant {variant_number} — mutation: {mutation_type}\n"
        f"# Generated by ERPClaw OS DGM Engine\n"
        f"# This variant applies {mutation_type} optimization\n\n"
    )

    if mutation_type == "query_optimization":
        return header + original_code.replace(
            "SELECT *", "SELECT id, name", 1
        ) if "SELECT *" in original_code else header + original_code

    elif mutation_type == "caching":
        cache_code = (
            "\n# DGM: Added memoization cache\n"
            "_dgm_cache = {}\n\n"
        )
        return header + cache_code + original_code

    elif mutation_type == "batch_processing":
        batch_comment = (
            "\n# DGM: Converted to batch processing for N+1 elimination\n"
        )
        return header + batch_comment + original_code

    elif mutation_type == "parameter_reorder":
        reorder_comment = (
            "\n# DGM: Reordered parameters for optimal index usage\n"
        )
        return header + reorder_comment + original_code

    elif mutation_type == "data_structure":
        ds_comment = (
            "\n# DGM: Changed data structure for O(1) lookup\n"
        )
        return header + ds_comment + original_code

    elif mutation_type == "algorithm_change":
        algo_comment = (
            "\n# DGM: Applied algorithmic optimization\n"
        )
        return header + algo_comment + original_code

    # Fallback
    return header + original_code


def _compute_diff(original_code, variant_code):
    """Compute unified diff between original and variant code.

    Args:
        original_code: str
        variant_code: str

    Returns:
        str: unified diff
    """
    original_lines = original_code.splitlines(keepends=True)
    variant_lines = variant_code.splitlines(keepends=True)
    diff = difflib.unified_diff(
        original_lines, variant_lines,
        fromfile="original", tofile="variant",
    )
    return "".join(diff)


def _compute_composite_score(exec_time_ms, memory_kb, test_pass_count, test_total):
    """Compute composite score for a variant.

    Formula: score = (1/exec_time_ms) * 0.6 + (1/memory_kb) * 0.2 + (test_pass_rate) * 0.2
    test_pass_rate MUST be 1.0 to qualify.

    Args:
        exec_time_ms: int
        memory_kb: int
        test_pass_count: int
        test_total: int

    Returns:
        str: composite score as Decimal string, or "0" if disqualified
    """
    if not test_total or test_total == 0:
        return "0"

    test_pass_rate = Decimal(str(test_pass_count)) / Decimal(str(test_total))

    # Disqualify variants that don't pass all tests
    if test_pass_rate < Decimal("1.0"):
        return "0"

    # Avoid division by zero
    if not exec_time_ms or exec_time_ms == 0:
        exec_time_ms = 1
    if not memory_kb or memory_kb == 0:
        memory_kb = 1

    time_score = Decimal("1") / Decimal(str(exec_time_ms)) * Decimal("0.6")
    mem_score = Decimal("1") / Decimal(str(memory_kb)) * Decimal("0.2")
    test_score = test_pass_rate * Decimal("0.2")

    total = time_score + mem_score + test_score
    return str(total.quantize(Decimal("0.000001"), rounding=ROUND_HALF_UP))


# ---------------------------------------------------------------------------
# Action: dgm-run-variant
# ---------------------------------------------------------------------------

def handle_dgm_run_variant(args):
    """Run DGM variant generation and evaluation for an action.

    Required: --module-name, --action-name
    Optional: --variant-count (default 3), --db-path
    """
    module_name = getattr(args, "module_name_arg", None) or getattr(args, "module_name", None)
    action_name = getattr(args, "action_name", None)
    variant_count = getattr(args, "variant_count", 3) or 3
    db_path = getattr(args, "db_path", None)

    if not module_name:
        return {"error": "--module-name is required"}
    if not action_name:
        return {"error": "--action-name is required"}

    # Step 1: Safety check
    excluded, reason = is_safety_excluded(module_name, action_name)
    if excluded:
        return {
            "error": f"DGM safety exclusion: {reason}",
            "module_name": module_name,
            "action_name": action_name,
            "safety_excluded": True,
        }

    # Step 2: Create run record
    run_id = str(uuid.uuid4())
    conn = get_connection(db_path)
    try:
        sql, cols = insert_row("erpclaw_dgm_run", {
            "id": P(),
            "module_name": P(),
            "action_name": P(),
            "variant_count": P(),
            "status": P(),
            "started_at": LiteralValue("datetime('now')"),
        })
        conn.execute(sql, [run_id, module_name, action_name, variant_count, "running"])
        conn.commit()

        # Step 3: Read current implementation (simulated — use placeholder)
        original_code = _read_action_source(module_name, action_name)
        if original_code is None:
            original_code = f"# Placeholder source for {module_name}/{action_name}\ndef handler(args):\n    pass\n"

        # Step 4: Generate variants
        mutation_types = list(VALID_MUTATION_TYPES)
        variants_created = []

        for i in range(variant_count):
            mutation_type = mutation_types[i % len(mutation_types)]
            variant_code = _generate_variant_code(original_code, mutation_type, i + 1)
            variant_diff = _compute_diff(original_code, variant_code)

            # Step 5: Execute in sandbox and collect metrics
            # In production, this calls sandbox.run_in_sandbox()
            # For now, we record metrics as pending (to be filled by sandbox)
            metrics = _evaluate_variant_in_sandbox(variant_code, module_name)

            composite_score = _compute_composite_score(
                metrics["exec_time_ms"],
                metrics["memory_kb"],
                metrics["test_pass_count"],
                metrics["test_total"],
            )

            variant_data = {
                "module_name": module_name,
                "action_name": action_name,
                "variant_number": i + 1,
                "variant_code": variant_code,
                "variant_diff": variant_diff,
                "mutation_type": mutation_type,
                "exec_time_ms": metrics["exec_time_ms"],
                "memory_kb": metrics["memory_kb"],
                "test_pass_count": metrics["test_pass_count"],
                "test_total": metrics["test_total"],
                "composite_score": composite_score,
            }

            variant_id = store_variant(conn, run_id, variant_data)
            variants_created.append({
                "variant_id": variant_id,
                "variant_number": i + 1,
                "mutation_type": mutation_type,
                "composite_score": composite_score,
                "exec_time_ms": metrics["exec_time_ms"],
                "memory_kb": metrics["memory_kb"],
                "test_pass_count": metrics["test_pass_count"],
                "test_total": metrics["test_total"],
            })

        conn.commit()

        # Step 6: Select best variant
        best_result = select_best(conn, run_id)
        conn.commit()

        if best_result:
            status = "completed"
        else:
            # No qualifying variant found
            conn.execute(
                'UPDATE erpclaw_dgm_run SET status = ?, completed_at = datetime(\'now\') WHERE id = ?',
                ("no_improvement", run_id),
            )
            conn.commit()
            status = "no_improvement"

    except Exception as e:
        # Mark run as failed
        try:
            conn.execute(
                'UPDATE erpclaw_dgm_run SET status = ?, completed_at = datetime(\'now\') WHERE id = ?',
                ("failed", run_id),
            )
            conn.commit()
        except Exception:
            pass
        return {"error": f"DGM run failed: {str(e)}", "run_id": run_id}
    finally:
        conn.close()

    result = {
        "result": "ok",
        "run_id": run_id,
        "module_name": module_name,
        "action_name": action_name,
        "variant_count": variant_count,
        "variants": variants_created,
        "status": status,
    }
    if best_result:
        result["best_variant_id"] = best_result["variant_id"]
        result["improvement_id"] = best_result["improvement_id"]
        result["improvement_pct"] = best_result.get("improvement_pct")

    return result


def _read_action_source(module_name, action_name):
    """Attempt to read the source code of an action's handler.

    Searches the project source tree for the module's db_query.py.
    Returns None if not found.
    """
    # Navigate from SCRIPT_DIR (erpclaw-os/) up to src/
    src_root = os.path.normpath(os.path.join(SCRIPT_DIR, "..", "..", ".."))
    if not os.path.isdir(src_root):
        return None

    # Try standard locations
    candidates = [
        os.path.join(src_root, module_name, "scripts", "db_query.py"),
        os.path.join(src_root, module_name, "db_query.py"),
    ]

    for candidate in candidates:
        if os.path.isfile(candidate):
            try:
                with open(candidate, "r") as f:
                    return f.read()
            except (IOError, OSError):
                pass

    return None


def _evaluate_variant_in_sandbox(variant_code, module_name):
    """Evaluate a variant in sandbox and return metrics.

    In production, this creates a temp module with the variant code,
    runs it through sandbox.run_in_sandbox(), and measures performance.

    For the initial implementation, returns simulated baseline metrics.
    Real sandbox integration will be added when the full pipeline is tested.
    """
    # Simulated metrics — in production, these come from sandbox execution
    import hashlib
    code_hash = int(hashlib.md5(variant_code.encode()).hexdigest()[:8], 16)

    return {
        "exec_time_ms": 50 + (code_hash % 200),  # 50-250ms range
        "memory_kb": 1024 + (code_hash % 4096),   # 1-5MB range
        "test_pass_count": 10,                      # Assume all pass for simulation
        "test_total": 10,
    }


# ---------------------------------------------------------------------------
# Action: dgm-list-variants
# ---------------------------------------------------------------------------

def handle_dgm_list_variants(args):
    """List variants for a given run or module.

    Optional: --run-id, --module-name
    At least one filter is required.
    """
    run_id = getattr(args, "run_id", None)
    module_name = getattr(args, "module_name_arg", None) or getattr(args, "module_name", None)
    db_path = getattr(args, "db_path", None)

    if not run_id and not module_name:
        return {"error": "--run-id or --module-name is required"}

    conn = get_connection(db_path)
    try:
        t = Table("erpclaw_dgm_variant")
        q = Q.from_(t).select(t.star)
        params = []

        if run_id:
            q = q.where(t.run_id == P())
            params.append(run_id)
        if module_name:
            q = q.where(t.module_name == P())
            params.append(module_name)

        q = q.orderby(t.composite_score, order=Order.desc)
        sql = q.get_sql()

        rows = conn.execute(sql, params).fetchall()
        items = [dict(r) for r in rows]

        # Also fetch run info if run_id provided
        run_info = None
        if run_id:
            run_row = conn.execute(
                'SELECT * FROM erpclaw_dgm_run WHERE id = ?',
                (run_id,),
            ).fetchone()
            if run_row:
                run_info = dict(run_row)

    finally:
        conn.close()

    result = {
        "result": "ok",
        "variants": items,
        "count": len(items),
    }
    if run_info:
        result["run"] = run_info

    return result


# ---------------------------------------------------------------------------
# Action: dgm-select-best
# ---------------------------------------------------------------------------

def handle_dgm_select_best(args):
    """For a completed run, mark the best variant as selected.

    Required: --run-id
    """
    run_id = getattr(args, "run_id", None)
    db_path = getattr(args, "db_path", None)

    if not run_id:
        return {"error": "--run-id is required"}

    conn = get_connection(db_path)
    try:
        # Check run exists
        run_row = conn.execute(
            'SELECT * FROM erpclaw_dgm_run WHERE id = ?',
            (run_id,),
        ).fetchone()
        if not run_row:
            return {"error": f"DGM run not found: {run_id}"}

        run_dict = dict(run_row)

        # Check if already has a selected variant
        if run_dict.get("best_variant_id"):
            return {
                "result": "ok",
                "run_id": run_id,
                "already_selected": True,
                "best_variant_id": run_dict["best_variant_id"],
                "improvement_id": run_dict.get("improvement_id"),
            }

        # Select best
        best_result = select_best(conn, run_id)
        conn.commit()

        if not best_result:
            # No qualifying variant
            conn.execute(
                'UPDATE erpclaw_dgm_run SET status = ?, completed_at = datetime(\'now\') WHERE id = ?',
                ("no_improvement", run_id),
            )
            conn.commit()
            return {
                "result": "ok",
                "run_id": run_id,
                "status": "no_improvement",
                "message": "No variant qualified (all tests must pass)",
            }

    finally:
        conn.close()

    return {
        "result": "ok",
        "run_id": run_id,
        "best_variant_id": best_result["variant_id"],
        "improvement_id": best_result["improvement_id"],
        "improvement_pct": best_result.get("improvement_pct"),
        "composite_score": best_result.get("composite_score"),
        "status": "completed",
    }
