from __future__ import annotations

import json
from pathlib import Path

from config import load_config
from project import get_current_version_dir
from state import StateManager
from project_queries import find_board_path, list_projects


HTML_TEMPLATE = """<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>DevTaskFlow Dashboard</title>
  <style>
    :root {
      --bg: #0b1020;
      --panel: rgba(18, 26, 43, 0.88);
      --border: rgba(104, 128, 171, 0.22);
      --text: #e8ecf3;
      --muted: #9fb0d1;
      --primary: #7c9cff;
      --shadow: 0 16px 48px rgba(0,0,0,.28);
    }
    * { box-sizing: border-box; }
    body {
      font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      margin: 0;
      color: var(--text);
      background:
        radial-gradient(circle at top left, rgba(124,156,255,.18), transparent 30%),
        linear-gradient(180deg, #0b1020 0%, #0d1326 100%);
    }
    .wrap { max-width: 1240px; margin: 0 auto; padding: 28px; }
    .hero { display:flex; justify-content:space-between; gap:20px; align-items:flex-start; margin-bottom:24px; }
    .hero h1 { margin:0; font-size:36px; letter-spacing:-0.02em; }
    .hero .sub { color:var(--muted); margin-top:8px; max-width:760px; line-height:1.6; }
    .glass { background: var(--panel); backdrop-filter: blur(14px); border:1px solid var(--border); border-radius: 20px; box-shadow: var(--shadow); }
    .card { padding:18px; }
    .search-box { min-width:320px; flex:1; max-width:460px; }
    .label { color:var(--muted); font-size:13px; margin-bottom:10px; }
    input { width:100%; padding:14px 16px; border-radius:14px; border:1px solid #31415f; background:#0f1728; color:#fff; font-size:14px; }
    .stats { display:grid; grid-template-columns: repeat(3, minmax(0,1fr)); gap:16px; margin-bottom:20px; }
    .stat .num { font-size:30px; font-weight:700; margin-top:8px; }
    .section-title { display:flex; justify-content:space-between; align-items:center; margin-bottom:14px; }
    .section-title h2 { margin:0; font-size:20px; }
    .muted { color:var(--muted); font-size:14px; }
    .projects { display:grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap:16px; }
    .project-card { padding:18px; }
    .project-head { display:flex; align-items:flex-start; justify-content:space-between; gap:12px; margin-bottom:14px; }
    .project-name { font-size:20px; font-weight:700; }
    .badge { display:inline-flex; align-items:center; border-radius:999px; padding:6px 10px; font-size:12px; background: rgba(124,156,255,.14); color:#dbe5ff; }
    .kv { display:grid; grid-template-columns: 96px 1fr; gap:8px; font-size:14px; margin-top:8px; }
    .kv .k { color:var(--muted); }
    .mono { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; word-break: break-all; }
    .footer { margin-top: 20px; color:var(--muted); font-size:13px; text-align:right; }
    @media (max-width: 980px) {
      .stats, .projects { grid-template-columns:1fr; }
      .hero { flex-direction:column; }
    }
  </style>
</head>
<body>
  <div class="wrap">
    <div class="hero">
      <div>
        <h1>DevTaskFlow</h1>
        <div class="sub">全部项目总览页。用于本地打开或发送本地链接查看当前工作区项目，不承担复杂项目管理功能。</div>
      </div>
      <div class="glass card search-box">
        <div class="label">搜索项目名 / 状态 / 版本</div>
        <input id="q" placeholder="例如：socialhub / 新建中 / v1.2.0" />
      </div>
    </div>

    <div class="stats">
      <div class="glass card stat"><div class="muted">项目总数</div><div class="num" id="count-all"></div></div>
      <div class="glass card stat"><div class="muted">迭代中</div><div class="num" id="count-active"></div></div>
      <div class="glass card stat"><div class="muted">已发布</div><div class="num" id="count-published"></div></div>
    </div>

    <div class="glass card">
      <div class="section-title">
        <h2>项目列表</h2>
        <div class="muted">看板文件：<span class="mono" id="board-path"></span></div>
      </div>
      <div class="projects" id="rows"></div>
    </div>

    <div class="footer">Generated by DevTaskFlow Dashboard</div>
  </div>
  <script>
    const DATA = __DATA__;
    const BOARD_PATH = __BOARD_PATH__;
    const rowsEl = document.getElementById('rows');
    const qEl = document.getElementById('q');
    document.getElementById('board-path').textContent = BOARD_PATH;
    document.getElementById('count-all').textContent = String(DATA.length);
    document.getElementById('count-active').textContent = String(DATA.filter(x => String(x.status || '').includes('迭代')).length);
    document.getElementById('count-published').textContent = String(DATA.filter(x => !!x.publish).length);

    function esc(v){ return String(v ?? '').replace(/[&<>\"]/g, s => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[s])); }
    function badge(text){ return `<span class="badge">${esc(text || '-')}</span>`; }
    function card(item){
      return `
        <div class="glass project-card">
          <div class="project-head">
            <div>
              <div class="project-name">${esc(item.name)}</div>
              <div class="muted">${esc(item.note || '暂无备注')}</div>
            </div>
            ${badge(item.status || '-')}
          </div>
          <div class="kv"><div class="k">当前版本</div><div class="mono">${esc(item.current_version || '-')}</div></div>
          <div class="kv"><div class="k">项目路径</div><div class="mono">${esc(item.path || '-')}</div></div>
          <div class="kv"><div class="k">更新时间</div><div>${esc(item.updated_at || '-')}</div></div>
          <div class="kv"><div class="k">归档状态</div><div>${esc(item.pipeline_status || '未启动')}</div></div>
          <div class="kv"><div class="k">发布状态</div><div>${item.publish ? '已发布' : '未发布'}</div></div>
        </div>
      `;
    }
    function render(items){ rowsEl.innerHTML = items.map(card).join(''); }
    qEl.addEventListener('input', () => {
      const q = qEl.value.trim().toLowerCase();
      if (!q) return render(DATA);
      render(DATA.filter(item => JSON.stringify(item).toLowerCase().includes(q)));
    });
    render(DATA);
  </script>
</body>
</html>
"""


def enrich_projects(projects: list[dict], start: Path | None = None):
    enriched = []
    base = (start or Path.cwd()).resolve()
    for item in projects:
        row = dict(item)
        project_path = (base / item['path']).resolve() if item.get('path') not in (None, '.') else base
        try:
            config = load_config(project_path)
            version_dir = get_current_version_dir(project_path, config)
            if version_dir and (version_dir / '.state.json').exists():
                state = StateManager(version_dir)
                row['pipeline_status'] = state.data.get('status')
                row['publish'] = state.data.get('publish')
        except Exception:
            pass
        enriched.append(row)
    return enriched


def build_dashboard(start: Path | None = None) -> dict:
    board_path = find_board_path(start)
    projects = enrich_projects(list_projects(start), start)
    html_text = HTML_TEMPLATE.replace('__DATA__', json.dumps(projects, ensure_ascii=False))
    html_text = html_text.replace('__BOARD_PATH__', json.dumps(str(board_path), ensure_ascii=False))
    out_path = board_path.parent / 'dtflow-dashboard.html'
    out_path.write_text(html_text, encoding='utf-8')
    return {
        'board_path': str(board_path),
        'dashboard_path': str(out_path),
        'project_count': len(projects),
    }
