#!/bin/bash
# AI Court Skill - 安装后脚本

echo ""
echo "🏛️ AI Court Skill 安装完成！"
echo "================================"
echo ""
echo "下一步："
echo ""
echo "1. 选择制度并复制配置："
echo "   # 明朝内阁制（推荐）"
echo "   cd ~/.openclaw && cp -r clawd/skills/ai-court/configs/ming-neige/* ."
echo ""
echo "   # 或唐朝三省制"
echo "   cd ~/.openclaw && cp -r clawd/skills/ai-court/configs/tang-sansheng/* ."
echo ""
echo "   # 或现代企业制"
echo "   cd ~/.openclaw && cp -r clawd/skills/ai-court/configs/modern-ceo/* ."
echo ""
echo "2. 配置 API Keys："
echo "   编辑 ~/.openclaw/openclaw.json"
echo "   填写你的 API Key（DashScope/OpenAI/Claude 等）"
echo ""
echo "3. 启动："
echo "   openclaw start"
echo ""
echo "📚 查看文档："
echo "   cat ~/.openclaw/clawd/skills/ai-court/references/tutorial-basics.md"
echo ""
echo "================================"
echo "✅ 如有问题，访问：https://github.com/wanikua/ai-court-skill"
echo "================================"
echo ""
