#!/usr/bin/env python3
# Part of doc2slides skill.

#!/usr/bin/env python3
"""
Generate PowerPoint presentation with consulting style.
Usage: python generate_ppt.py --output <output.pptx> --title "Title" --content <content.json>
       python generate_ppt.py --output <output.pptx> --title "Title" --slides <slides.json>
"""

import sys
import json
import argparse
import os

def create_consulting_presentation(title, slides, template_path=None, output_path="output.pptx"):
    """
    Create a PowerPoint presentation with consulting style.
    
    Args:
        title: Presentation title
        slides: List of slide dicts with 'title', 'content', and optionally 'type'
        template_path: Optional template PPTX to use for styling
        output_path: Output file path
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RgbColor
        from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
    except ImportError:
        return {"success": False, "error": "python-pptx not installed. Run: pip install python-pptx"}
    
    try:
        # Load template or create new
        if template_path and os.path.exists(template_path):
            prs = Presentation(template_path)
        else:
            prs = Presentation()
            # Set slide size to 16:9 (widescreen)
            prs.slide_width = Inches(13.333)
            prs.slide_height = Inches(7.5)
        
        # Colors
        NAVY_900 = RgbColor(0x0f, 0x17, 0x2a)
        NAVY_800 = RgbColor(0x1e, 0x29, 0x3b)
        SLATE_400 = RgbColor(0x94, 0xa3, 0xb8)
        SLATE_600 = RgbColor(0x47, 0x55, 0x68)
        RED = RgbColor(0xdc, 0x26, 0x26)
        GREEN = RgbColor(0x05, 0x96, 0x69)
        
        # Title slide
        title_slide_layout = prs.slide_layouts[6]  # Blank
        slide = prs.slides.add_slide(title_slide_layout)
        
        # Add title manually with styling
        title_box = slide.shapes.add_textbox(Inches(0.5), Inches(2.5), Inches(12.333), Inches(1.5))
        tf = title_box.text_frame
        p = tf.paragraphs[0]
        p.text = title
        p.font.size = Pt(44)
        p.font.bold = True
        p.font.color.rgb = NAVY_900
        p.alignment = PP_ALIGN.CENTER
        
        # Subtitle
        subtitle_box = slide.shapes.add_textbox(Inches(0.5), Inches(4.2), Inches(12.333), Inches(0.5))
        tf = subtitle_box.text_frame
        p = tf.paragraphs[0]
        p.text = "Generated by Doc-to-PPT Pro"
        p.font.size = Pt(18)
        p.font.color.rgb = SLATE_400
        p.alignment = PP_ALIGN.CENTER
        
        # Content slides
        for slide_data in slides:
            slide_title = slide_data.get('title', 'Untitled')
            slide_content = slide_data.get('content', [])
            slide_type = slide_data.get('type', 'default')
            
            # Use blank layout
            blank_layout = prs.slide_layouts[6]
            slide = prs.slides.add_slide(blank_layout)
            
            # Add eyebrow (small label)
            eyebrow_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.5), Inches(12.333), Inches(0.4))
            tf = eyebrow_box.text_frame
            p = tf.paragraphs[0]
            p.text = slide_data.get('eyebrow', '')
            p.font.size = Pt(12)
            p.font.color.rgb = SLATE_400
            
            # Add title
            title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.9), Inches(12.333), Inches(1))
            tf = title_box.text_frame
            p = tf.paragraphs[0]
            p.text = slide_title
            p.font.size = Pt(32)
            p.font.bold = True
            p.font.color.rgb = NAVY_900
            
            # Add content
            if slide_type == 'problem' and slide_data.get('stats'):
                # Left side: description
                desc_box = slide.shapes.add_textbox(Inches(0.5), Inches(2.2), Inches(5.5), Inches(4))
                tf = desc_box.text_frame
                tf.word_wrap = True
                
                # Description
                if slide_data.get('description'):
                    p = tf.paragraphs[0]
                    p.text = slide_data['description']
                    p.font.size = Pt(18)
                    p.font.color.rgb = SLATE_600
                    p.space_after = Pt(20)
                
                # Insight box
                if slide_data.get('insight'):
                    p = tf.add_paragraph()
                    p.text = "💡 关键洞察"
                    p.font.size = Pt(14)
                    p.font.bold = True
                    p.font.color.rgb = NAVY_800
                    p.space_before = Pt(20)
                    
                    p = tf.add_paragraph()
                    p.text = slide_data['insight']
                    p.font.size = Pt(16)
                    p.font.color.rgb = NAVY_900
                
                # Right side: stats (simplified as text)
                stats_box = slide.shapes.add_textbox(Inches(6.5), Inches(2.2), Inches(6.333), Inches(4))
                tf = stats_box.text_frame
                tf.word_wrap = True
                
                for i, stat in enumerate(slide_data['stats'][:3]):
                    if i > 0:
                        p = tf.add_paragraph()
                    else:
                        p = tf.paragraphs[0]
                    
                    p.text = f"{stat.get('value', 0)}% - {stat.get('label', '')}"
                    p.font.size = Pt(24)
                    p.font.bold = True
                    p.font.color.rgb = RED
                    p.space_after = Pt(15)
            else:
                # Default layout: bullet points
                content_box = slide.shapes.add_textbox(Inches(0.5), Inches(2.2), Inches(12.333), Inches(4.5))
                tf = content_box.text_frame
                tf.word_wrap = True
                
                # Handle content as list or string
                if isinstance(slide_content, str):
                    items = [line.strip() for line in slide_content.split('\n') if line.strip()]
                else:
                    items = slide_content
                
                for i, item in enumerate(items):
                    if i == 0:
                        p = tf.paragraphs[0]
                    else:
                        p = tf.add_paragraph()
                    
                    p.text = f"• {item}"
                    p.font.size = Pt(18)
                    p.font.color.rgb = SLATE_600
                    p.space_after = Pt(12)
                    p.level = 0
        
        prs.save(output_path)
        return {
            "success": True, 
            "output": output_path,
            "slides": len(prs.slides),
            "message": f"Created {len(prs.slides)} slides in {output_path}"
        }
        
    except Exception as e:
        return {"success": False, "error": str(e)}

def main():
    parser = argparse.ArgumentParser(description='Generate consulting-style PowerPoint from content')
    parser.add_argument('--output', '-o', required=True, help='Output PPTX file path')
    parser.add_argument('--title', '-t', default='Presentation', help='Presentation title')
    parser.add_argument('--template', help='Template PPTX file to use for styling')
    parser.add_argument('--content', help='JSON file with content structure')
    parser.add_argument('--slides', help='JSON string or file with slides array')
    
    args = parser.parse_args()
    
    # Get slides
    slides = []
    if args.slides:
        if os.path.exists(args.slides):
            with open(args.slides, 'r', encoding='utf-8') as f:
                slides = json.load(f)
        else:
            try:
                slides = json.loads(args.slides)
            except:
                slides = [{"title": "Content", "content": args.slides}]
    elif args.content:
        with open(args.content, 'r', encoding='utf-8') as f:
            data = json.load(f)
            slides = data.get('slides', [data])
    else:
        # Read from stdin
        try:
            data = json.load(sys.stdin)
            slides = data.get('slides', [data])
        except:
            print(json.dumps({"success": False, "error": "No content provided"}))
            sys.exit(1)
    
    result = create_consulting_presentation(
        title=args.title,
        slides=slides,
        template_path=args.template,
        output_path=args.output
    )
    
    print(json.dumps(result, ensure_ascii=False, indent=2))

if __name__ == "__main__":
    main()
