#!/bin/bash
# export.sh — Export research findings to markdown file
# Usage: ./export.sh <summary_file> [output_dir]

OUTPUT_DIR="${2:-$(dirname "$0")/../exports}"
mkdir -p "$OUTPUT_DIR"

if [ -z "$1" ]; then
  echo "Usage: $0 <summary_file> [output_dir]" >&2
  exit 1
fi

SUMMARY_FILE="$1"

if [ ! -f "$SUMMARY_FILE" ]; then
  echo "Error: File not found: $SUMMARY_FILE" >&2
  exit 1
fi

# Generate filename with date
date_stamp=$(date +%Y-%m-%d)
output_file="${OUTPUT_DIR}/reddit-research-${date_stamp}.md"

# Copy and enhance the summary
{
  echo "---
title: Reddit Research Report
date: $(date -u +%Y-%m-%dT%H:%M:%SZ)
keywords: ${REDDIT_KEYWORDS:-N/A}
subreddits: ${REDDIT_SUBREDDITS:-all}
---"
  echo ""
  cat "$SUMMARY_FILE"
  echo ""
  echo "---"
  echo ""
  echo "*Generated by OpenClaw Reddit Researcher*"
} > "$output_file"

echo "Exported to: $output_file"
echo ""
echo "File size: $(wc -c < "$output_file") bytes"
echo "Lines: $(wc -l < "$output_file")"

exit 0
