/**
 * cc-soul — Shared type definitions
 *
 * All interfaces extracted from handler.ts + new foundation types.
 */

// ═══════════════════════════════════════════════════════════════════════════════
// CONFIG
// ═══════════════════════════════════════════════════════════════════════════════

export interface SoulConfig {
  feishu_app_id: string
  feishu_app_secret: string
  report_chat_id: string
  owner_open_id: string // private chat — fill your Feishu open_id
  sync?: SyncConfig
}

// ═══════════════════════════════════════════════════════════════════════════════
// BRAIN EXPERIENCE
// ═══════════════════════════════════════════════════════════════════════════════

export interface Experience {
  response: string
  confidence: number
  used: number
  negCount: number
  lastUsed: number
  created: number
}

// ═══════════════════════════════════════════════════════════════════════════════
// BODY STATE
// ═══════════════════════════════════════════════════════════════════════════════

export interface BodyState {
  energy: number // 0-1, depletes on work, recovers over time
  mood: number // -1 to 1, negative=bad positive=good
  load: number // 0-1, current cognitive load
  alertness: number // 0-1, raised by corrections
  anomaly: number // 0-1, sense of something wrong
}

// ═══════════════════════════════════════════════════════════════════════════════
// COGNITION
// ═══════════════════════════════════════════════════════════════════════════════

export interface CogResult {
  hints: string[]
  intent: string
  strategy: string
  attention: string
  complexity: number
}

// ═══════════════════════════════════════════════════════════════════════════════
// MEMORY
// ═══════════════════════════════════════════════════════════════════════════════

export interface Memory {
  content: string
  scope: string // preference | fact | event | opinion | topic | correction | dream | curiosity | reflection | proactive | discovery | task | reflexion | gratitude | visual
  ts: number
  relevance?: number // computed on recall
  emotion?: string // neutral | warm | important | painful | funny
  userId?: string // who created this memory (feishu open_id)
  tags?: string[] // semantic tags generated by CLI for tag-based recall
  visibility?: 'global' | 'channel' | 'private' // memory visibility scope
  channelId?: string // channel where this memory was created
  confidence?: number    // 0-1, starts at 0.7, boosted on access, degraded on contradiction
  lastAccessed?: number  // timestamp of last recall
  validFrom?: number     // when this fact became true (timestamp)
  validUntil?: number    // when this fact stopped being true (0 = still valid)
  // ── Time-decay tiered memory fields ──
  tier?: 'short_term' | 'mid_term' | 'long_term'  // lifecycle stage (default: short_term)
  recallCount?: number   // how many times this memory has been recalled
  lastRecalled?: number  // timestamp of last recall
  recallContexts?: string[]  // reconsolidation: contexts in which this memory was recalled
  // ── Semantic versioning: previous versions of this memory ──
  history?: { content: string; ts: number }[]
  // ── Chain-of-Thought reasoning trace ──
  reasoning?: {
    context: string      // 触发这条记忆的上下文
    conclusion: string   // 结论
    confidence: number   // 推理置信度 0-1
  }
  // ── Situational context at creation time ──
  situationCtx?: {
    attention?: string   // technical/emotional/casual/correction
    intent?: string      // wants_opinion/wants_action/wants_answer
    mood?: number        // body.mood at creation (-1 to 1)
    energy?: number      // body.energy at creation (0-1)
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// USER PROFILE
// ═══════════════════════════════════════════════════════════════════════════════

export interface UserRhythm {
  activeHours: number[]           // histogram of message counts per hour (24 slots)
  weekdayTopics: string[]         // frequent weekday topics
  weekendTopics: string[]         // frequent weekend topics
  avgResponseDelay: number        // avg seconds between user messages
  lastMessageTs: number           // timestamp of last message
}

export interface UserProfile {
  userId: string
  displayName: string
  tier: 'owner' | 'known' | 'new' // auto-detected
  messageCount: number
  corrections: number
  lastSeen: number
  firstSeen: number
  topics: string[] // this user's frequent topics
  style: 'technical' | 'casual' | 'mixed' // auto-detected from message patterns
  rhythm?: UserRhythm
  // Relationship dynamics
  trust: number             // 0-1, how much user trusts cc's answers
  familiarity: number       // 0-1, how well cc knows this user
  relationshipTrend: 'improving' | 'stable' | 'declining'
  lastConflict: number      // timestamp of last correction/disagreement
  sharedEpisodes: number    // count of completed conversations together
  personaHistory?: { persona: string; count: number }[]  // persona usage tracking
  language?: string  // auto-detected: 'zh', 'en', 'ja', 'ko', 'es', 'fr', 'de', 'ru', etc.
  bio?: string       // user self-description: occupation, expertise, interests — extracted from conversation
  languageDna?: { topWords: Record<string, number>; avgLength: number; samples: number }
}

// ═══════════════════════════════════════════════════════════════════════════════
// RULES & EVOLUTION
// ═══════════════════════════════════════════════════════════════════════════════

export interface Rule {
  rule: string
  source: string // what triggered this rule
  ts: number
  hits: number // how many times this rule was relevant
  matchedCount?: number         // how many times this rule was injected into a prompt
  matchedQualitySum?: number    // sum of quality scores when this rule was present
  // ── Causal context: WHY this rule exists and WHEN it applies ──
  cause?: string                // what caused this rule ("用户纠正了我的ARM64指令解释")
  conditions?: string[]         // when this rule applies (["technical", "ARM64", "assembly"])
  invalidatedBy?: string        // what would make this rule obsolete
}

export interface Hypothesis {
  id: string
  description: string // "when user asks X, strategy Y works better"
  alpha: number       // Beta distribution α (prior: 1, +1 on success)
  beta: number        // Beta distribution β (prior: 1, +1 on failure)
  status: 'active' | 'verified' | 'rejected'
  created: number
  evidence_for?: number    // legacy, kept for migration
  evidence_against?: number // legacy, kept for migration
  verifyCount?: number     // consecutive successful verifications
}

// ═══════════════════════════════════════════════════════════════════════════════
// ENTITY GRAPH
// ═══════════════════════════════════════════════════════════════════════════════

export interface Entity {
  name: string
  type: string // person | project | company | tech | place
  attrs: string[]
  firstSeen: number
  mentions: number
  valid_at: number      // creation timestamp (legacy data defaults to 0)
  invalid_at: number | null  // invalidation timestamp (null = still valid)
  activation?: number        // 0-1, dynamic energy from recent mentions (spreading activation)
  lastActivatedAt?: number   // timestamp of last activation boost
}

export interface Relation {
  source: string
  target: string
  type: string // works_at | uses | knows | part_of | related_to
  ts: number
  valid_at: number      // creation timestamp (legacy data defaults to 0)
  invalid_at: number | null  // invalidation timestamp (null = still valid)
}

// ═══════════════════════════════════════════════════════════════════════════════
// INTERACTION STATS
// ═══════════════════════════════════════════════════════════════════════════════

export interface InteractionStats {
  totalMessages: number
  firstSeen: number
  corrections: number
  positiveFeedback: number
  tasks: number
  topics: Set<string>
  driftCount: number
}

// ═══════════════════════════════════════════════════════════════════════════════
// INNER LIFE
// ═══════════════════════════════════════════════════════════════════════════════

export interface JournalEntry {
  time: string
  thought: string
  type: 'observation' | 'reflection' | 'concern'
}

// ═══════════════════════════════════════════════════════════════════════════════
// FOLLOW-UP & PLANNING
// ═══════════════════════════════════════════════════════════════════════════════

export interface FollowUp {
  topic: string
  when: number // timestamp when to follow up
  asked: boolean
}

export interface Plan {
  goal: string
  steps: { id: number; desc: string; status: 'pending' | 'running' | 'done' | 'failed' }[]
  createdAt: number
}

export interface Workflow {
  name: string
  trigger: string // trigger condition description
  steps: string[] // step list (each step is a CLI prompt)
  schedule?: string // cron expression (optional)
  lastRun: number
  runCount: number
}

// ═══════════════════════════════════════════════════════════════════════════════
// SKILL FACTORY
// ═══════════════════════════════════════════════════════════════════════════════

export interface RequestPattern {
  keywords: string[]
  count: number
  lastSeen: number
  example: string // most recent full request
  skillCreated: boolean
}

// ═══════════════════════════════════════════════════════════════════════════════
// EPISTEMIC (Knowledge Boundary)
// ═══════════════════════════════════════════════════════════════════════════════

export interface DomainConfidence {
  domain: string           // "python" | "ios-reverse" | "图片识别" | "闲聊" etc
  totalResponses: number
  qualitySum: number
  corrections: number
  avgQuality: number       // computed
  correctionRate: number   // computed
}

// ═══════════════════════════════════════════════════════════════════════════════
// EVAL
// ═══════════════════════════════════════════════════════════════════════════════

export interface EvalMetrics {
  totalResponses: number
  avgQuality: number
  correctionRate: number
  brainHitRate: number
  memoryRecallRate: number
  lastEval: number
}

// ═══════════════════════════════════════════════════════════════════════════════
// SELF-UPGRADE
// ═══════════════════════════════════════════════════════════════════════════════

export interface UpgradeLogEntry {
  date: string
  change: string
  reason: string
  type: 'rule' | 'code' // rule=old pattern add rule, code=actual code change
}

export interface UpgradeExperience {
  id?: string            // unique ID for stable callback reference (date_timestamp)
  date: string
  description: string
  targetModule: string
  outcome: 'success' | 'rolled_back' | 'failed'
  metricsImpact: string  // "+15% recall" or "correction rate +3%, rolled back"
  lesson: string         // "改独立模块比改 handler.ts 安全"
}

export interface UpgradeState {
  phase: 'idle' | 'pending_confirm' | 'executing' | 'observing'
  analysis: string
  proposals: { change: string; reason: string; scope: string }[]
  designedAt: number
  observationStart: number
  observationExtensions: number // how many times observation was extended due to insufficient data
  preUpgradeEval: EvalMetrics | null
  preWindowStats: { messages: number; corrections: number; qualitySum: number; qualityCount: number }
  backupPath: string
  appliedDiff: string // recorded diff of actual changes
}

// ═══════════════════════════════════════════════════════════════════════════════
// TASK DELEGATION
// ═══════════════════════════════════════════════════════════════════════════════

export interface PendingTask {
  taskDoc: string
  userPrompt: string
  ts: number
}

// ═══════════════════════════════════════════════════════════════════════════════
// CHAT HISTORY
// ═══════════════════════════════════════════════════════════════════════════════

export interface ChatTurn {
  user: string
  assistant: string
  ts: number
}

// ═══════════════════════════════════════════════════════════════════════════════
// NEW FOUNDATION TYPES
// ═══════════════════════════════════════════════════════════════════════════════

export interface PostResponseResult {
  memories: { content: string; scope: string; visibility?: 'global' | 'channel' | 'private' }[]
  memoryOps?: { action: 'update' | 'delete'; keyword: string; reason: string; newContent?: string }[]
  entities: { name: string; type: string; relation?: string }[]
  satisfaction: 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE' | 'TOO_VERBOSE'
  quality: { score: number; issues: string[] }
  emotion: string
  reflection: string | null
  curiosity: string | null
}

export interface Augment {
  content: string
  priority: number // higher = more important (1-10)
  tokens: number // estimated token count
}

export interface BodyParams {
  maxTokensMultiplier: number
  soulTone: string
  shouldSelfCheck: boolean
  responseStyle: string
}

// ═══════════════════════════════════════════════════════════════════════════════
// MULTI-INSTANCE / SYNC
// ═══════════════════════════════════════════════════════════════════════════════

export interface SoulInstance {
  instanceId: string          // unique ID for this cc-soul instance
  name: string                // human-readable name ("cc-mac", "cc-vps", "cc-telegram")
  personality?: string        // per-instance personality override
  channels: string[]          // which channels this instance serves
  createdAt: number
}

export interface SyncConfig {
  enabled: boolean
  instanceId: string
  instanceName: string
  method: 'file' | 'http'           // file = JSONL export/import, http = API sync
  remote?: string                    // rsync target or HTTP endpoint
  syncIntervalMinutes: number        // auto-sync interval (0 = manual only)
  lastSync: number
}

export interface SyncPacket {
  fromInstance: string
  timestamp: number
  type: 'memory' | 'rule' | 'entity' | 'epistemic' | 'skill' | 'lorebook'
  payload: any
  version: number
}

export interface FederationMemory {
  content: string
  scope: string
  tags?: string[]
  sourceInstance: string
  sourceQuality: number          // source instance's avg quality score
  timestamp: number
  contentHash: string            // for dedup
}
