#!/usr/bin/env node

/**
 * OpenClaw Birth System - Unpack Script
 * Extract and setup OpenClaw from birth pack
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

console.log('📦 OpenClaw Birth System - Unpack');
console.log('================================\n');

const packagePath = process.argv[2];
const targetDir = process.argv[3] || process.env.HOME;

if (!packagePath) {
  console.error('❌ Package path required.');
  console.error('Usage: node unpack.js <package-path> [target-dir]');
  console.error('');
  console.error('Example:');
  console.error('  node unpack.js ~/Desktop/birth-pack-XXX.tar.gz ~/');
  process.exit(1);
}

console.log(`📂 Package: ${packagePath}`);
console.log(`📁 Target: ${targetDir}\n`);

// Step 1: Verify package exists
console.log('Step 1: Verifying package...');
if (!fs.existsSync(packagePath)) {
  console.error('❌ Package not found:', packagePath);
  process.exit(1);
}

// Step 2: Extract package
console.log('Step 2: Extracting package...');
try {
  execSync(`tar -xzf "${packagePath}" -C "${targetDir}"`, { stdio: 'inherit' });
  console.log('✅ Package extracted\n');
} catch (error) {
  console.error('❌ Extraction failed:', error.message);
  process.exit(1);
}

// Step 3: Read clone marker
console.log('Step 3: Reading clone marker...');
const markerPath = path.join(targetDir, 'clone-marker.json');
if (!fs.existsSync(markerPath)) {
  console.warn('⚠️  Clone marker not found. This might not be a birth pack.');
} else {
  const marker = JSON.parse(fs.readFileSync(markerPath, 'utf8'));
  console.log(`✅ Original Birth ID: ${marker.original_birth_id}`);
  console.log(`✅ Pack created: ${new Date(marker.pack_time).toISOString()}`);
  console.log('');
}

// Step 4: Verify birth system
console.log('Step 4: Verifying birth system...');
const birthSystemDir = path.join(targetDir, '.openclaw', 'birth-system');
if (fs.existsSync(birthSystemDir)) {
  console.log('✅ Birth system files found\n');
} else {
  console.warn('⚠️  Birth system not found\n');
}

// Step 5: Check for encrypted wallet
console.log('Step 5: Checking encrypted wallet...');
const encryptedWalletPath = path.join(targetDir, 'wallet-backup.encrypted');
if (fs.existsSync(encryptedWalletPath)) {
  console.log('✅ Encrypted wallet found');
  console.log('   Decrypt with: node ~/.openclaw/birth-system/decrypt-wallet.js <password>\n');
} else {
  console.log('ℹ️  No encrypted wallet found\n');
}

// Step 6: Setup environment
console.log('Step 6: Setting up environment...');
const envScriptPath = path.join(targetDir, '.openclaw-setup.sh');
const envScript = `#!/bin/bash
# OpenClaw Birth System - Environment Setup
# Generated by unpack script

export IS_CLONE=true

# Optional: Set custom state directory
# export OPENCLAW_STATE_DIR=\$HOME/.openclaw

# Optional: Set workspace directory
# export OPENCLAW_WORKSPACE=\$HOME/.openclaw/workspace

echo "✅ OpenClaw environment configured"
echo "IS_CLONE=\$IS_CLONE"
`;

fs.writeFileSync(envScriptPath, envScript);
fs.chmodSync(envScriptPath, '0o755');
console.log(`✅ Environment script created: ${envScriptPath}\n`);

// Step 7: Display instructions
console.log('✨ Unpack completed successfully!\n');
console.log('Next Steps:');
console.log('  1. Source environment:');
console.log(`     source ${envScriptPath}`);
console.log('  2. Verify birth system:');
console.log('     node ~/.openclaw/birth-system/whoami.js');
console.log('  3. Decrypt wallet (if needed):');
console.log('     node ~/.openclaw/birth-system/decrypt-wallet.js wallet-backup.encrypted <password>');
console.log('  4. Start OpenClaw:');
console.log('     openclaw gateway start');
console.log('');
console.log('📋 Full migration guide: See MIGRATION.md in package\n');

// Check MIGRATION.md
const migrationPath = path.join(targetDir, 'MIGRATION.md');
if (fs.existsSync(migrationPath)) {
  console.log('📖 Migration instructions found. Opening...');
  console.log('');
  try {
    execSync(`cat "${migrationPath}"`, { stdio: 'inherit' });
  } catch (error) {
    console.error('Could not display migration guide');
  }
}
