#!/usr/bin/env bash
# init-project.sh — Initialize Aegis structure in a project
#
# Usage: bash init-project.sh /path/to/project
#
# Creates:
#   contracts/api-spec.yaml
#   contracts/shared-types.ts
#   contracts/errors.yaml
#   docs/designs/.gitkeep

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
TEMPLATES="$SKILL_DIR/templates"

PROJECT="${1:-.}"

if [[ ! -d "$PROJECT" ]]; then
  echo "Error: Project directory '$PROJECT' does not exist."
  exit 1
fi

echo "🛡️  Initializing Aegis structure in: $PROJECT"

# --- Detect project stack ---
STACK_JSON=""
if [[ -x "$SCRIPT_DIR/detect-stack.sh" ]]; then
  STACK_JSON=$(bash "$SCRIPT_DIR/detect-stack.sh" "$PROJECT" 2>/dev/null || echo "{}")
  echo "📋 Detected stack: $STACK_JSON"
  echo ""
fi

# Helper: check if a value is in the detected stack JSON
stack_has() { echo "$STACK_JSON" | grep -q "\"$1\"" 2>/dev/null; }

# Create directories
mkdir -p "$PROJECT/contracts"
mkdir -p "$PROJECT/docs/designs"
mkdir -p "$PROJECT/.aegis"

# Copy templates (don't overwrite existing)
copy_if_missing() {
  local src="$1"
  local dest="$2"
  if [[ -f "$dest" ]]; then
    echo "  ⏭️  Skipped (exists): $dest"
  else
    cp "$src" "$dest"
    echo "  ✅ Created: $dest"
  fi
}

copy_if_missing "$TEMPLATES/api-spec-starter.yaml" "$PROJECT/contracts/api-spec.yaml"
copy_if_missing "$TEMPLATES/shared-types-starter.ts" "$PROJECT/contracts/shared-types.ts"
copy_if_missing "$TEMPLATES/errors-starter.yaml" "$PROJECT/contracts/errors.yaml"

# --- Generate project-aware docker-compose (Issue #1) ---
generate_docker_compose() {
  local dest="$PROJECT/docker-compose.integration.yml"
  [[ -f "$dest" ]] && { echo "  ⏭️  Skipped (exists): $dest"; return; }

  local db_service=""
  local db_env=""
  local db_url=""

  # Detect database from project files
  if stack_has "mongodb" || grep -rq "mongo\|pymongo\|mongoose" "$PROJECT" --include="*.json" --include="*.toml" --include="*.txt" --include="*.yaml" --include="*.yml" 2>/dev/null; then
    db_service='  db:
    image: mongo:7-jammy
    environment:
      MONGO_INITDB_DATABASE: test
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand({ping:1})"]
      interval: 5s
      timeout: 3s
      retries: 5
    tmpfs:
      - /data/db'
    db_url="MONGO_URL=mongodb://db:27017/test"
  elif stack_has "redis" || grep -rq "redis\|ioredis\|aioredis" "$PROJECT" --include="*.json" --include="*.toml" --include="*.txt" 2>/dev/null; then
    db_service='  db:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5'
    db_url="REDIS_URL=redis://db:6379"
  elif stack_has "mysql" || grep -rq "mysql\|mysqlclient\|mysql2" "$PROJECT" --include="*.json" --include="*.toml" --include="*.txt" 2>/dev/null; then
    db_service='  db:
    image: mysql:8-oracle
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
    tmpfs:
      - /var/lib/mysql'
    db_url="DATABASE_URL=mysql://root:test@db:3306/test"
  else
    # Default to PostgreSQL
    db_service='  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 3s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data'
    db_url="DATABASE_URL=postgresql://test:test@db:5432/test"
  fi

  cat > "$dest" << COMPOSE_EOF
# docker-compose.integration.yml
# Integration test environment — real services, no mocks.
# Auto-generated by Aegis init-project.sh based on detected stack.
#
# Usage:
#   docker compose -f docker-compose.integration.yml up --build --abort-on-container-exit

services:
$db_service

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - $db_url
      - PORT=8080
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - API_URL=http://backend:8080
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 10

  e2e:
    image: mcr.microsoft.com/playwright:v1.42.0-jammy
    depends_on:
      frontend:
        condition: service_healthy
    volumes:
      - ./e2e:/tests
    working_dir: /tests
    command: npx playwright test
    environment:
      - BASE_URL=http://frontend:3000
      - API_URL=http://backend:8080
COMPOSE_EOF
  echo "  ✅ Created: $dest (detected DB: $(echo "$db_url" | cut -d= -f1))"
}

generate_docker_compose

# --- Copy Aegis scripts into project .aegis/ (Issue #2: no absolute paths) ---
for script in validate-contract.sh generate-types.sh gap-report.sh; do
  if [[ -f "$SCRIPT_DIR/$script" ]]; then
    copy_if_missing "$SCRIPT_DIR/$script" "$PROJECT/.aegis/$script"
    chmod +x "$PROJECT/.aegis/$script" 2>/dev/null || true
  fi
done

# Create .gitkeep for empty dirs
touch "$PROJECT/docs/designs/.gitkeep"

# If CLAUDE.md doesn't exist, offer the template
if [[ ! -f "$PROJECT/CLAUDE.md" ]]; then
  cp "$TEMPLATES/claude-md.md" "$PROJECT/CLAUDE.md"
  echo "  ✅ Created: CLAUDE.md (from Aegis template — customize it!)"
else
  echo "  ⏭️  Skipped (exists): CLAUDE.md"
fi

echo ""
echo "🛡️  Aegis initialized! Next steps:"
echo "  1. Edit contracts/api-spec.yaml with your API endpoints"
echo "  2. Customize CLAUDE.md for your project"
echo "  3. Create your first Design Brief in docs/designs/"
echo ""
echo "  Template: $TEMPLATES/design-brief.md"
echo "  Aegis tools copied to: $PROJECT/.aegis/"
