#!/usr/bin/env node
/**
 * Feishu Weekly Report Generator
 * Generates professional weekly work reports
 */

import { execSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Parse command line arguments
function parseArgs() {
  const args = process.argv.slice(2);
  const options = {
    start: getLastMonday(),
    end: getLastFriday(),
    git: null,
    template: 'standard',
    output: null,
    name: null,
    department: null
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    switch (arg) {
      case '--start':
        options.start = args[++i];
        break;
      case '--end':
        options.end = args[++i];
        break;
      case '--git':
        options.git = args[++i];
        break;
      case '--template':
        options.template = args[++i];
        break;
      case '--output':
        options.output = args[++i];
        break;
      case '--name':
        options.name = args[++i];
        break;
      case '--department':
        options.department = args[++i];
        break;
      case '--help':
      case '-h':
        showHelp();
        process.exit(0);
        break;
    }
  }

  // Set default output filename
  if (!options.output) {
    options.output = `weekly-report-${options.end}.md`;
  }

  // Get user name from git if not provided
  if (!options.name) {
    try {
      options.name = execSync('git config user.name', { encoding: 'utf8' }).trim();
    } catch {
      options.name = '用户';
    }
  }

  return options;
}

function showHelp() {
  console.log(`
Feishu Weekly Report Generator

Usage: node generate-weekly.mjs [options]

Options:
  --start <date>      Start date (YYYY-MM-DD), default: last Monday
  --end <date>        End date (YYYY-MM-DD), default: last Friday
  --git <path>        Git repository path to collect commits
  --template <name>   Template name (standard|detailed|minimal), default: standard
  --output <path>     Output file path
  --name <name>       User name
  --department <dept> Department name
  --help, -h          Show this help

Examples:
  node generate-weekly.mjs
  node generate-weekly.mjs --git ~/my-project --name "张三"
  node generate-weekly.mjs --start 2026-03-10 --end 2026-03-14
`);
}

function getLastMonday() {
  const now = new Date();
  const day = now.getDay();
  const diff = now.getDate() - day + (day === 0 ? -6 : 1);
  const monday = new Date(now.setDate(diff));
  return formatDate(monday);
}

function getLastFriday() {
  const now = new Date();
  const day = now.getDay();
  const diff = now.getDate() - day + (day === 0 ? -2 : 5);
  const friday = new Date(now.setDate(diff));
  return formatDate(friday);
}

function formatDate(date) {
  return date.toISOString().split('T')[0];
}

function getWeekDates(start, end) {
  const dates = [];
  const startDate = new Date(start);
  const endDate = new Date(end);
  
  for (let d = new Date(startDate); d <= endDate; d.setDate(d.getDate() + 1)) {
    dates.push(formatDate(new Date(d)));
  }
  return dates;
}

function getWeekdayName(dateStr) {
  const days = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'];
  const date = new Date(dateStr);
  return days[date.getDay()];
}

// Collect git commits
function collectGitCommits(gitPath, since, until) {
  if (!gitPath || !existsSync(gitPath)) {
    return [];
  }

  try {
    const format = '%H|%s|%ad';
    const output = execSync(
      `git -C "${gitPath}" log --since="${since} 00:00:00" --until="${until} 23:59:59" --format="${format}" --date=short`,
      { encoding: 'utf8', cwd: gitPath }
    );

    return output.trim().split('\n').filter(line => line).map(line => {
      const [hash, message, date] = line.split('|');
      return { hash: hash.slice(0, 7), message, date };
    });
  } catch (error) {
    console.warn('Warning: Could not collect git commits:', error.message);
    return [];
  }
}

// Load template
function loadTemplate(templateName) {
  const templatePath = resolve(__dirname, '../references/templates', `${templateName}.md`);
  
  if (existsSync(templatePath)) {
    return readFileSync(templatePath, 'utf8');
  }

  // Default template
  return `# {{name}} - 周报 ({{start}} ~ {{end}})

**汇报人**: {{name}}{{department}}
**汇报周期**: {{start}} ~ {{end}}

---

## 一、本周工作总结

本周主要完成了以下工作：

{{summary}}

---

## 二、已完成工作

{{completed}}

---

## 三、进行中工作

{{inProgress}}

---

## 四、下周计划

{{nextWeek}}

---

## 五、遇到的问题与风险

{{issues}}

---

## 六、需要的支持

{{support}}

---

*Generated by Feishu Weekly Report Generator*
`;
}

// Generate report content
function generateReport(options) {
  const weekDates = getWeekDates(options.start, options.end);
  const commits = options.git ? collectGitCommits(options.git, options.start, options.end) : [];

  // Build completed work section
  let completedWork = '';
  if (commits.length > 0) {
    completedWork += '### 代码提交\n\n';
    commits.forEach(commit => {
      completedWork += `- ${commit.date} ${commit.message}\n`;
    });
    completedWork += '\n';
  }
  completedWork += `- 完成项目相关开发任务\n- 参与团队技术讨论\n- 处理日常开发工作\n`;

  // Build summary based on commits
  let summary = '';
  if (commits.length > 0) {
    const categories = categorizeCommits(commits);
    summary = `本周共计提交代码 ${commits.length} 次，主要工作包括：`;
    if (categories.feature > 0) summary += ` 新增功能 ${categories.feature} 项，`;
    if (categories.fix > 0) summary += ` 修复问题 ${categories.fix} 个，`;
    if (categories.docs > 0) summary += ` 文档更新 ${categories.docs} 次，`;
    summary = summary.replace(/，$/, '。');
  } else {
    summary = '本周按计划完成了各项工作任务，项目进展顺利。';
  }

  // Build weekday sections
  let dailyWork = '';
  weekDates.forEach(date => {
    const weekday = getWeekdayName(date);
    const dayCommits = commits.filter(c => c.date === date);
    
    dailyWork += `### ${weekday} (${date})\n\n`;
    if (dayCommits.length > 0) {
      dayCommits.forEach(c => {
        dailyWork += `- ${c.message}\n`;
      });
    } else {
      dailyWork += `- 日常工作处理\n`;
    }
    dailyWork += '\n';
  });

  const template = loadTemplate(options.template);
  
  return template
    .replace(/{{name}}/g, options.name)
    .replace(/{{department}}/g, options.department ? ` | ${options.department}` : '')
    .replace(/{{start}}/g, options.start)
    .replace(/{{end}}/g, options.end)
    .replace(/{{summary}}/g, summary)
    .replace(/{{completed}}/g, completedWork)
    .replace(/{{inProgress}}/g, dailyWork)
    .replace(/{{nextWeek}}/g, `- 继续推进项目开发\n- 完成本周遗留任务\n- 准备下周迭代计划`)
    .replace(/{{issues}}/g, '- 暂无重大问题\n- 项目整体进展正常')
    .replace(/{{support}}/g, '- 暂无特殊支持需求');
}

function categorizeCommits(commits) {
  const categories = { feature: 0, fix: 0, docs: 0, other: 0 };
  
  commits.forEach(commit => {
    const msg = commit.message.toLowerCase();
    if (msg.includes('feat') || msg.includes('add') || msg.includes('new')) {
      categories.feature++;
    } else if (msg.includes('fix') || msg.includes('bug') || msg.includes('修复')) {
      categories.fix++;
    } else if (msg.includes('doc') || msg.includes('文档')) {
      categories.docs++;
    } else {
      categories.other++;
    }
  });
  
  return categories;
}

// Main
async function main() {
  try {
    const options = parseArgs();
    
    console.log('📝 Generating weekly report...');
    console.log(`   Period: ${options.start} ~ ${options.end}`);
    console.log(`   User: ${options.name}`);
    if (options.git) console.log(`   Git: ${options.git}`);
    
    const report = generateReport(options);
    
    writeFileSync(options.output, report, 'utf8');
    
    console.log('\n✅ Weekly report generated successfully!');
    console.log(`   Output: ${resolve(options.output)}`);
    
  } catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  }
}

main();
