// AWP Dispatch Worker — Cloudflare Dynamic Workers Adapter
// Orchestrates multi-agent DAG execution on Cloudflare Workers.
//
// Generated by AWP Skill. Customize as needed.

import { Hono } from "hono";
import type {
  Env,
  WorkflowConfig,
  AgentConfig,
  GraphNode,
  ChatMessage,
  WorkflowResult,
} from "./types";
import { callLLM } from "./llm";
import { MemoryManager } from "./memory";

// ── Embedded Configs (replaced during generation) ──────────

// These are injected by the AWP skill at generation time.
// In a real deployment, you would import these from ./config/.
const WORKFLOW_CONFIG: WorkflowConfig = {{WORKFLOW_CONFIG_JSON}};
const AGENT_CONFIGS: Record<string, AgentConfig> = {{AGENT_CONFIGS_JSON}};

// ── App ────────────────────────────────────────────────────

const app = new Hono<{ Bindings: Env }>();

app.post("/", async (c) => {
  const body = await c.req.json<{ task: string }>();
  if (!body.task) {
    return c.json({ error: "Missing 'task' in request body" }, 400);
  }

  try {
    const result = await executeWorkflow(c.env, body.task);
    return c.json(result);
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    return c.json({ error: message }, 500);
  }
});

app.get("/health", (c) => {
  return c.json({
    status: "ok",
    workflow: WORKFLOW_CONFIG.workflow.name,
    version: WORKFLOW_CONFIG.workflow.version,
    agents: WORKFLOW_CONFIG.graph.map((n) => n.id),
  });
});

export default {
  fetch: app.fetch,

  async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext) {
    // Uncomment for cron-triggered workflow execution:
    // ctx.waitUntil(executeWorkflow(env, "Scheduled execution"));
  },
};

// ── Workflow Execution ─────────────────────────────────────

async function executeWorkflow(
  env: Env,
  task: string,
): Promise<WorkflowResult> {
  const memory = new MemoryManager(env, WORKFLOW_CONFIG.workflow.name);
  await memory.initDatabase();

  // Topological sort
  const sorted = topologicalSort(WORKFLOW_CONFIG.graph);

  // Execute agents in order
  const state: WorkflowResult = {};

  for (const node of sorted) {
    if (!node.enabled) continue;

    const agentConfig = AGENT_CONFIGS[node.agent];
    if (!agentConfig) {
      throw new Error(`Agent config not found: ${node.agent}`);
    }

    // Check dependencies
    const depsSatisfied = node.depends_on.every((dep) => {
      if (dep.condition === "success") {
        return dep.agent in state;
      }
      return true;
    });

    if (!depsSatisfied) continue;

    // Build context from predecessor outputs
    const context = buildContext(node, state);

    // Load long-term memory
    const longTermMemory = await memory.readLongTerm(node.agent);

    // Build messages
    const messages = buildMessages(agentConfig, task, context, longTermMemory);

    // Call LLM
    const result = await callLLM(env, agentConfig, messages);

    // Store result
    state[node.agent] = result;

    // Write daily log if memory is enabled
    if (env.DB) {
      await memory.writeDailyLog(
        node.agent,
        JSON.stringify(result).substring(0, 4000),
      );
    }
  }

  return state;
}

// ── Helpers ────────────────────────────────────────────────

function buildContext(
  node: GraphNode,
  state: WorkflowResult,
): string {
  const parts: string[] = [];

  for (const [agentId, fields] of Object.entries(node.share_input)) {
    const agentResult = state[agentId];
    if (!agentResult) continue;

    if (fields.length === 0) {
      parts.push(`## Output from ${agentId}\n${JSON.stringify(agentResult, null, 2)}`);
    } else {
      const filtered: Record<string, unknown> = {};
      for (const field of fields) {
        if (field in agentResult) {
          filtered[field] = agentResult[field];
        }
      }
      parts.push(`## Output from ${agentId}\n${JSON.stringify(filtered, null, 2)}`);
    }
  }

  return parts.join("\n\n");
}

function buildMessages(
  agent: AgentConfig,
  task: string,
  context: string,
  longTermMemory: string,
): ChatMessage[] {
  // System prompt + skills + memory
  let systemPrompt = agent.prompts.system;
  if (longTermMemory) {
    systemPrompt += `\n\n## Long-term Memory\n${longTermMemory}`;
  }

  // User prompt + context
  let userPrompt = agent.prompts.user.replace("{{TASK}}", task);
  if (context) {
    userPrompt += `\n\n## Context from Previous Agents\n${context}`;
  }

  return [
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt },
  ];
}

function topologicalSort(graph: GraphNode[]): GraphNode[] {
  const nodeMap = new Map(graph.map((n) => [n.id, n]));
  const visited = new Set<string>();
  const result: GraphNode[] = [];

  function visit(id: string) {
    if (visited.has(id)) return;
    visited.add(id);
    const node = nodeMap.get(id);
    if (!node) return;
    for (const dep of node.depends_on) {
      visit(dep.agent);
    }
    result.push(node);
  }

  for (const node of graph) {
    visit(node.id);
  }

  return result;
}
