// AWP Type Definitions for Cloudflare Workers
// Generated by AWP Skill — Cloudflare Dynamic Workers Adapter

/** Cloudflare Worker environment bindings. */
export interface Env {
  STATE: KVNamespace;
  MEMORY?: R2Bucket;
  DB?: D1Database;
  AI?: Ai;
  LLM_API_KEY: string;
  LLM_MODEL: string;
  LLM_BASE_URL: string;
}

/** AWP Agent configuration (compiled from agent.awp.yaml). */
export interface AgentConfig {
  identity: {
    id: string;
    role: string;
    description: string;
  };
  model: {
    provider?: "workers-ai" | "openai-compatible";
    name: string;
    parameters: {
      temperature: number;
      max_tokens?: number;
    };
  };
  prompts: {
    system: string;
    user: string;
  };
  tools: {
    enabled: boolean;
    allowed: string[];
  };
  output_schema: Record<string, unknown>;
}

/** AWP Workflow manifest (compiled from workflow.awp.yaml). */
export interface WorkflowConfig {
  workflow: {
    name: string;
    version: string;
    description: string;
  };
  graph: GraphNode[];
  execution: {
    mode: "sequential" | "parallel" | "conditional";
    timeout: {
      per_agent: number;
      total: number;
    };
  };
}

/** A node in the agent DAG. */
export interface GraphNode {
  id: string;
  agent: string;
  enabled: boolean;
  depends_on: Array<{
    agent: string;
    condition: string;
  }>;
  share_input: Record<string, string[]>;
  description: string;
}

/** Standard AWP tool result format. */
export interface ToolResult {
  ok: boolean;
  status: number;
  data: Record<string, unknown>;
  error: string | null;
  log?: string;
}

/** LLM chat message. */
export interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

/** Workflow execution result. */
export type WorkflowResult = Record<string, Record<string, unknown>>;
