services:
  reasoning:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: qwen35-a3b-gguf
    restart: unless-stopped

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    volumes:
      - ../models:/models

    ports:
      - "8080:8080"

    command: >
      -m /models/reasoning/Qwen3.5-35B-A3B/Qwen3.5-35B-A3B-Q4_K_M.gguf
      --host 0.0.0.0
      --port 8080
      --ctx-size 16384 
      --temp 1.0 
      --top-p 0.95 
      --top-k 20 
      --min-p 0.00

  vlm:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: gemma3-27b-it-gguf
    restart: unless-stopped

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    volumes:
      - ../models:/models

    ports:
      - "8081:8080"

    command: >
      -m /models/vlm/gemma-3-27b-it/gemma-3-27b-it-Q4_K_M.gguf
      --mmproj /models/vlm/gemma-3-27b-it/mmproj-F16.gguf
      --host 0.0.0.0
      --port 8080
      --ctx-size 8192 
      --n-gpu-layers 99 
      --seed 3407 
      --prio 2 
      --temp 1.0 
      --repeat-penalty 1.0 
      --min-p 0.01 
      --top-k 64 
      --top-p 0.95 
    

  transcription:
    image: ghcr.io/speaches-ai/speaches:latest-cuda
    container_name: whisper-asr
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CHAT_COMPLETION_BASE_URL=http://reasoning:8080/v1
      - CHAT_COMPLETION_API_KEY=dummy
      - PRELOAD_MODELS=Systran/faster-whisper-medium-v3  
    ports:
      - "8000:8000"
    volumes:
      - ../models/whisper:/home/ubuntu/.cache/huggingface/hub
