#!/usr/bin/env bash
# ============================================================
# gen_types.sh — 从 Rust 后端生成前端类型文件
#
# 原理：cargo test 触发 ts-rs 导出 .ts → 合并到前端指定路径
#
# 用法: ./gen_types.sh <ts_rs_output_dir> <frontend_types_path>
#
#   ts_rs_output_dir    ts-rs 生成 .ts 文件的目录（如 ./bindings）
#   frontend_types_path 前端类型文件输出路径（如 ../frontend/src/lib/types.generated.ts）
#
# 示例: ./gen_types.sh ./bindings ../frontend/src/lib/types.generated.ts
# ============================================================

set -euo pipefail

if [ $# -ne 2 ]; then
    echo "用法: $0 <ts_rs_output_dir> <frontend_types_path>"
    echo "示例: $0 ./bindings ../frontend/src/lib/types.generated.ts"
    exit 1
fi

TS_RS_OUTPUT_DIR="$1"
FRONTEND_TYPES_PATH="$2"

echo "🔄 Running cargo test to trigger ts-rs export..."
cargo test --quiet 2>/dev/null

if [ ! -d "$TS_RS_OUTPUT_DIR" ] || [ -z "$(ls "$TS_RS_OUTPUT_DIR"/*.ts 2>/dev/null)" ]; then
    echo "❌ No .ts files found in $TS_RS_OUTPUT_DIR"
    echo "   确认 contracts.rs 中的 struct 有 #[derive(TS)] #[ts(export)]"
    exit 1
fi

mkdir -p "$(dirname "$FRONTEND_TYPES_PATH")"

{
    echo "// AUTO-GENERATED by ts-rs from Rust contracts. DO NOT EDIT."
    echo "// Re-generate: ./gen_types.sh $TS_RS_OUTPUT_DIR $FRONTEND_TYPES_PATH"
    echo ""
    for f in "$TS_RS_OUTPUT_DIR"/*.ts; do
        [ -f "$f" ] || continue
        cat "$f"
        echo ""
    done
} > "$FRONTEND_TYPES_PATH"

count=$(ls "$TS_RS_OUTPUT_DIR"/*.ts 2>/dev/null | wc -l | tr -d ' ')
echo "✅ Generated $FRONTEND_TYPES_PATH ($count types merged)"
