#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Monthly PDF rendering for Health-Mate."""

from __future__ import annotations

import math
import os
import re
import tempfile
from datetime import datetime
from typing import Dict, Iterable, List, Optional

from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
from reportlab.platypus import Image, KeepTogether, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from i18n import condition_name, format_weight, inline_localize, resolve_locale
from daily_pdf_generator import clean_html_tags, get_font_prop, register_chinese_font, stars_to_text

try:
    import matplotlib.patches as mpatches
    import matplotlib.patheffects as path_effects
    import matplotlib.pyplot as plt
    import numpy as np

    MATPLOTLIB_AVAILABLE = True
except ImportError:
    MATPLOTLIB_AVAILABLE = False

C_PRIMARY = "#2563EB"
C_SUCCESS = "#16A34A"
C_SUCCESS_LIGHT = "#86EFAC"
C_WARNING = "#F59E0B"
C_DANGER = "#EF4444"
C_DANGER_LIGHT = "#FCA5A5"
C_ACCENT = "#7C3AED"
C_TEXT_MAIN = "#0F172A"
C_TEXT_MUTED = "#64748B"
C_BORDER = "#E2E8F0"
C_BG_HEAD = "#F8FAFC"
C_BG_SOFT = "#F8FAFC"
C_GRID = "#CBD5E1"
C_EMPTY = "#E5E7EB"
C_MEDICATION = "#FDE68A"


def localize(locale: str, zh_text: str, en_text: str) -> str:
    return inline_localize(locale, zh_text, en_text)


def profile_condition_title(profile: dict, locale: str) -> str:
    display = str((profile or {}).get("condition_display", "") or "").strip()
    if display:
        return display
    conditions = (profile or {}).get("conditions", [])
    if isinstance(conditions, list) and conditions:
        labels = [condition_name(locale, item) for item in conditions if item]
        labels = [item for item in labels if item]
        if labels:
            return "、".join(labels) if resolve_locale(locale=locale) in {"zh-CN", "ja-JP"} else ", ".join(labels)
        return condition_name(locale, (profile or {}).get("condition", "balanced"))


def source_text(locale: str, source: str) -> str:
    labels = {
        "llm": localize(locale, "来源：LLM 动态生成", "Source: dynamically generated by LLM"),
        "fallback": localize(locale, "来源：本地规则", "Source: local rules"),
        "fallback_tavily": localize(locale, "来源：Tavily 检索 + 本地规则", "Source: Tavily retrieval + local rules"),
        "local": localize(locale, "来源：本地规则", "Source: local rules"),
    }
    return labels.get(source or "fallback", labels["fallback"])


def localize_three(locale: str, zh_text: str, en_text: str, ja_text: Optional[str] = None) -> str:
    resolved = resolve_locale(locale=locale)
    if resolved == "zh-CN":
        return zh_text
    if resolved == "ja-JP" and ja_text is not None:
        return ja_text
    return en_text


def is_lifestyle_mode(primary_condition: Optional[str], population_branch: Optional[str] = None) -> bool:
    normalized_branch = str(population_branch or "").strip().lower()
    if normalized_branch in {"lifestyle", "disease"}:
        return normalized_branch == "lifestyle"
    return str(primary_condition or "").strip() in {"balanced", "fat_loss"}


def monthly_section_label(locale: str, primary_condition: Optional[str], key: str, population_branch: Optional[str] = None) -> str:
    lifestyle_mode = is_lifestyle_mode(primary_condition, population_branch)
    mappings = {
        "deep_dive": (
            ("核心体征与习惯洞察", "Core Vitals & Habit Insights", "コア指標と習慣インサイト"),
            ("专科病理深度对齐", "Specialty Deep Dive", "病態別ディープダイブ"),
        ),
        "action_plan": (
            ("月度健康复盘与行动策略", "Monthly Review & Action Strategy", "月次レビューと行動戦略"),
            ("专家会诊与医疗规划", "Medical Action Plan", "医療アクションプラン"),
        ),
        "ai_review": (
            ("AI 综合健康研判", "AI Comprehensive Assessment", "AI 総合ヘルス評価"),
            ("AI 月度病情研判", "AI Monthly Review", "AI 月次レビュー"),
        ),
        "follow_up": (
            ("周期性体测与筛查建议", "Periodic Screening Suggestions", "定期スクリーニング提案"),
            ("复查提醒", "Follow-up Reminders", "フォローアップ提案"),
        ),
        "hospital": (
            ("医院与门诊建议", "Hospital and Clinic Suggestions", "病院・外来提案"),
            ("医院与门诊建议", "Hospital and Clinic Suggestions", "病院・外来提案"),
        ),
    }
    lifestyle_titles, default_titles = mappings[key]
    chosen = lifestyle_titles if lifestyle_mode else default_titles
    return localize_three(locale, *chosen)


def _save_figure(fig) -> Optional[str]:
    temp_img = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
    fig.savefig(temp_img.name, transparent=True, dpi=220, bbox_inches="tight")
    plt.close(fig)
    return temp_img.name


def _style_text(text_obj, font_prop=None, weight: str = "bold", color: Optional[str] = None, fontsize: Optional[float] = None) -> None:
    resolved_color = color if color is not None else text_obj.get_color()
    if color is not None:
        text_obj.set_color(color)
    if fontsize is not None:
        text_obj.set_fontsize(fontsize)
    if font_prop:
        text_obj.set_fontproperties(font_prop)
    if weight:
        text_obj.set_fontweight(weight)
    outline_color = C_TEXT_MAIN if str(resolved_color).lower() in {"#ffffff", "white"} else "white"
    text_obj.set_path_effects([path_effects.withStroke(linewidth=1.0, foreground=outline_color, alpha=0.65)])


def _apply_tick_font(ax, font_prop, color: Optional[str] = None) -> None:
    for label in ax.get_xticklabels():
        _style_text(label, font_prop, color=color)
    for label in ax.get_yticklabels():
        _style_text(label, font_prop, color=color)


def _style_legend(legend, font_prop=None, fontsize: Optional[float] = None) -> None:
    if not legend:
        return
    for text in legend.get_texts():
        _style_text(text, font_prop, fontsize=fontsize)
    legend_title = legend.get_title()
    if legend_title:
        _style_text(legend_title, font_prop, fontsize=fontsize)


def _build_chart_image(path: str, max_width_cm: float, max_height_cm: float, h_align: str = "CENTER") -> Image:
    width_limit = max_width_cm * cm
    height_limit = max_height_cm * cm
    try:
        width_px, height_px = ImageReader(path).getSize()
        scale = min(width_limit / max(width_px, 1), height_limit / max(height_px, 1))
        width = width_px * scale
        height = height_px * scale
    except Exception:
        width = width_limit
        height = height_limit
    chart = Image(path, width=width, height=height)
    chart.hAlign = h_align
    return chart


def create_macro_radar_chart(macro_scores: Dict[str, float], locale: str) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE:
        return None

    try:
        font_prop = get_font_prop(locale)
        labels = [
            localize(locale, "饮食", "Diet"),
            localize(locale, "饮水", "Hydration"),
            localize(locale, "运动", "Exercise"),
            localize(locale, "用药", "Medication"),
            localize(locale, "监测", "Monitoring"),
        ]
        values = [
            float(macro_scores.get("diet", 0)) / 100.0,
            float(macro_scores.get("water", 0)) / 100.0,
            float(macro_scores.get("exercise", 0)) / 100.0,
            float(macro_scores.get("medication", 0)) / 100.0,
            float(macro_scores.get("monitoring", 0)) / 100.0,
        ]
        angles = np.linspace(0, 2 * math.pi, len(labels), endpoint=False).tolist()
        angles += angles[:1]
        values += values[:1]

        fig, ax = plt.subplots(figsize=(5.2, 4.6), subplot_kw={"polar": True})
        fig.patch.set_alpha(0)
        ax.set_theta_offset(math.pi / 2)
        ax.set_theta_direction(-1)
        ax.set_ylim(0, 1)
        ax.set_facecolor("none")
        ax.spines["polar"].set_color(C_BORDER)
        ax.grid(color=C_GRID, linestyle="--", alpha=0.7)

        line = ax.plot(angles, values, color=C_PRIMARY, linewidth=2.4)[0]
        line.set_path_effects([path_effects.withStroke(linewidth=5, foreground="white", alpha=0.45)])
        ax.fill(angles, values, color=C_PRIMARY, alpha=0.18)
        ax.scatter(angles[:-1], values[:-1], s=36, color=C_PRIMARY, zorder=3)

        ax.set_xticks(angles[:-1])
        ax.set_xticklabels(labels, color=C_TEXT_MAIN, fontsize=10)
        ax.set_yticks([0.25, 0.5, 0.75, 1.0])
        ax.set_yticklabels(["25", "50", "75", "100"], color=C_TEXT_MAIN, fontsize=8.4)
        _apply_tick_font(ax, font_prop)

        center = ax.text(
            0,
            0,
            localize(locale, "本月依从性", "Monthly\nAdherence"),
            ha="center",
            va="center",
            color=C_TEXT_MAIN,
            fontsize=10,
            fontweight="bold",
        )
        _style_text(center, font_prop, color=C_TEXT_MAIN, fontsize=10)

        return _save_figure(fig)
    except Exception:
        return None


def create_symptom_heatmap(daily_records: List[dict], locale: str, min_weeks: int = 4) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE or not daily_records:
        return None

    try:
        font_prop = get_font_prop(locale)
        valid_records = [record for record in daily_records if record.get("date")]
        if not valid_records:
            return None

        import datetime as _dt

        start_date = _dt.datetime.strptime(valid_records[0]["date"], "%Y-%m-%d").date()
        end_date = _dt.datetime.strptime(valid_records[-1]["date"], "%Y-%m-%d").date()
        total_days = (end_date - start_date).days + 1
        weeks = max(min_weeks, math.ceil((start_date.weekday() + total_days) / 7))
        matrix = np.full((7, weeks), -1, dtype=int)
        overlays = {}
        day_numbers = {}

        for record in valid_records:
            current = _dt.datetime.strptime(record["date"], "%Y-%m-%d").date()
            offset = (current - start_date).days + start_date.weekday()
            row = current.weekday()
            col = offset // 7

            symptom_count = int(record.get("symptom_count", 0) or 0)
            medication_count = int(record.get("medication_count", 0) or 0)
            has_data = bool(record.get("has_data"))

            if not has_data:
                state = 0
            elif symptom_count > 0:
                state = 4 if symptom_count >= 2 else 3
            elif medication_count > 0:
                state = 2
            else:
                state = 1

            matrix[row, col] = state
            overlays[(row, col)] = medication_count > 0
            day_numbers[(row, col)] = current.day

        cmap = plt.matplotlib.colors.ListedColormap(
            [C_EMPTY, C_SUCCESS_LIGHT, C_MEDICATION, C_DANGER_LIGHT, C_DANGER]
        )
        norm = plt.matplotlib.colors.BoundaryNorm([-0.5, 0.5, 1.5, 2.5, 3.5, 4.5], cmap.N)

        fig, ax = plt.subplots(figsize=(max(8.8, weeks * 1.6), 3.45))
        fig.patch.set_alpha(0)
        ax.imshow(matrix, cmap=cmap, norm=norm, aspect="equal")

        weekdays = [
            localize(locale, "周一", "Mon"),
            localize(locale, "周二", "Tue"),
            localize(locale, "周三", "Wed"),
            localize(locale, "周四", "Thu"),
            localize(locale, "周五", "Fri"),
            localize(locale, "周六", "Sat"),
            localize(locale, "周日", "Sun"),
        ]
        ax.set_yticks(range(7))
        ax.set_yticklabels(weekdays, fontsize=8.2, color=C_TEXT_MAIN)
        ax.set_xticks(range(weeks))
        ax.set_xticklabels(
            [localize(locale, f"{index + 1}周", f"W{index + 1}") for index in range(weeks)],
            fontsize=5.8,
            color=C_TEXT_MAIN,
        )
        _apply_tick_font(ax, font_prop)

        ax.set_xticks(np.arange(-0.5, weeks, 1), minor=True)
        ax.set_yticks(np.arange(-0.5, 7, 1), minor=True)
        ax.grid(which="minor", color="white", linewidth=2)
        ax.tick_params(which="minor", bottom=False, left=False)
        ax.tick_params(axis="both", length=0)
        ax.tick_params(axis="x", pad=2)
        for spine in ax.spines.values():
            spine.set_visible(False)

        for (row, col), day_num in day_numbers.items():
            state = matrix[row, col]
            color = "white" if state in {3, 4} else C_TEXT_MAIN
            text = ax.text(col, row, str(day_num), ha="center", va="center", fontsize=6.8, color=color)
            _style_text(text, font_prop, color=color, fontsize=6.8)
            if overlays.get((row, col)):
                marker = ax.text(col + 0.28, row - 0.24, "M", ha="center", va="center", fontsize=4.4, color=color)
                _style_text(marker, font_prop, color=color, fontsize=4.4)

        legend_items = [
            mpatches.Patch(color=C_SUCCESS_LIGHT, label=localize(locale, "稳定", "Stable")),
            mpatches.Patch(color=C_MEDICATION, label=localize(locale, "用药日", "Medication day")),
            mpatches.Patch(color=C_DANGER_LIGHT, label=localize(locale, "轻度症状", "Mild symptom")),
            mpatches.Patch(color=C_DANGER, label=localize(locale, "明显症状", "Notable symptom")),
        ]
        legend_kwargs = {
            "handles": legend_items,
            "loc": "upper center",
            "bbox_to_anchor": (0.5, -0.2),
            "frameon": False,
            "ncol": 2,
            "fontsize": 6.5,
            "columnspacing": 1.6,
            "handlelength": 1.2,
        }
        legend = ax.legend(**legend_kwargs)
        _style_legend(legend, font_prop, fontsize=6.5)
        fig.subplots_adjust(bottom=0.26)

        return _save_figure(fig)
    except Exception:
        return None


def create_activity_heatmap(
    daily_records: List[dict],
    locale: str,
    step_target: int = 8000,
    min_weeks: int = 4,
) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE or not daily_records:
        return None

    try:
        font_prop = get_font_prop(locale)
        valid_records = [record for record in daily_records if record.get("date")]
        if not valid_records:
            return None

        import datetime as _dt

        start_date = _dt.datetime.strptime(valid_records[0]["date"], "%Y-%m-%d").date()
        end_date = _dt.datetime.strptime(valid_records[-1]["date"], "%Y-%m-%d").date()
        total_days = (end_date - start_date).days + 1
        weeks = max(min_weeks, math.ceil((start_date.weekday() + total_days) / 7))
        matrix = np.full((7, weeks), -1, dtype=int)
        day_numbers = {}
        target = max(1, int(step_target or 8000))

        for record in valid_records:
            current = _dt.datetime.strptime(record["date"], "%Y-%m-%d").date()
            offset = (current - start_date).days + start_date.weekday()
            row = current.weekday()
            col = offset // 7

            steps = int(record.get("steps", 0) or 0)
            exercise_calories = float(record.get("exercise_calories", 0) or 0)
            exercise_count = int(record.get("exercise_count", 0) or 0)
            has_data = bool(record.get("has_data"))

            if not has_data:
                state = 0
            elif steps >= max(int(target * 1.5), target + 4000) or exercise_calories >= 450:
                state = 3
            elif steps >= target or exercise_count > 0 or exercise_calories >= 150:
                state = 2
            elif steps >= int(target * 0.5) or exercise_calories >= 60:
                state = 1
            else:
                state = 0

            matrix[row, col] = state
            day_numbers[(row, col)] = current.day

        cmap = plt.matplotlib.colors.ListedColormap(
            [C_BG_SOFT, C_EMPTY, "#BBF7D0", C_SUCCESS, "#166534"]
        )
        norm = plt.matplotlib.colors.BoundaryNorm([-1.5, -0.5, 0.5, 1.5, 2.5, 3.5], cmap.N)

        fig, ax = plt.subplots(figsize=(max(8.8, weeks * 1.6), 3.45))
        fig.patch.set_alpha(0)
        ax.imshow(matrix, cmap=cmap, norm=norm, aspect="equal")

        weekdays = [
            localize(locale, "周一", "Mon"),
            localize(locale, "周二", "Tue"),
            localize(locale, "周三", "Wed"),
            localize(locale, "周四", "Thu"),
            localize(locale, "周五", "Fri"),
            localize(locale, "周六", "Sat"),
            localize(locale, "周日", "Sun"),
        ]
        ax.set_yticks(range(7))
        ax.set_yticklabels(weekdays, fontsize=8.2, color=C_TEXT_MAIN)
        ax.set_xticks(range(weeks))
        ax.set_xticklabels(
            [localize(locale, f"{index + 1}周", f"W{index + 1}") for index in range(weeks)],
            fontsize=5.8,
            color=C_TEXT_MAIN,
        )
        _apply_tick_font(ax, font_prop)

        ax.set_xticks(np.arange(-0.5, weeks, 1), minor=True)
        ax.set_yticks(np.arange(-0.5, 7, 1), minor=True)
        ax.grid(which="minor", color="white", linewidth=2)
        ax.tick_params(which="minor", bottom=False, left=False)
        ax.tick_params(axis="both", length=0)
        ax.tick_params(axis="x", pad=2)
        for spine in ax.spines.values():
            spine.set_visible(False)

        for (row, col), day_num in day_numbers.items():
            state = matrix[row, col]
            color = "white" if state >= 2 else C_TEXT_MAIN
            text = ax.text(col, row, str(day_num), ha="center", va="center", fontsize=6.8, color=color)
            _style_text(text, font_prop, color=color, fontsize=6.8)

        legend_items = [
            mpatches.Patch(color=C_EMPTY, label=localize(locale, "休息/未达标", "Rest / below target")),
            mpatches.Patch(color="#BBF7D0", label=localize(locale, "轻度活跃", "Light activity")),
            mpatches.Patch(color=C_SUCCESS, label=localize(locale, "完全达标", "Goal met")),
            mpatches.Patch(color="#166534", label=localize(locale, "强化训练", "High-intensity day")),
        ]
        legend_kwargs = {
            "handles": legend_items,
            "loc": "upper center",
            "bbox_to_anchor": (0.5, -0.2),
            "frameon": False,
            "ncol": 2,
            "fontsize": 6.5,
            "columnspacing": 1.6,
            "handlelength": 1.2,
        }
        legend = ax.legend(**legend_kwargs)
        _style_legend(legend, font_prop, fontsize=6.5)
        fig.subplots_adjust(bottom=0.26)

        return _save_figure(fig)
    except Exception:
        return None


def _moving_average(values: List[Optional[float]], window: int = 3) -> List[Optional[float]]:
    smoothed = []
    for index, value in enumerate(values):
        if value is None:
            smoothed.append(None)
            continue
        start = max(0, index - window + 1)
        slice_values = [item for item in values[start : index + 1] if item is not None]
        smoothed.append(sum(slice_values) / len(slice_values) if slice_values else value)
    return smoothed


def _estimate_bmr(weight_kg: float, height_cm: float, age: float, gender: str) -> float:
    gender_value = str(gender or "male").strip().lower()
    gender_offset = 5 if gender_value in {"male", "man", "m"} else -161
    return 10 * float(weight_kg) + 6.25 * float(height_cm) - 5 * float(age) + gender_offset


def _estimate_activity_burn(record: dict) -> float:
    exercise_calories = float(record.get("exercise_calories", 0) or 0)
    steps = float(record.get("steps", 0) or 0)
    step_burn = max(0.0, steps - 4000) * 0.03
    return exercise_calories + step_burn


def create_weight_bmr_trend_chart(records: List[dict], profile: dict, locale: str) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE:
        return None

    try:
        filtered = [record for record in records if record.get("weight") is not None]
        if len(filtered) < 2:
            return None

        font_prop = get_font_prop(locale)
        age = float(profile.get("age", 30) or 30)
        height_cm = float(profile.get("height_cm", 170) or 170)
        gender = str(profile.get("gender", "male") or "male")
        labels = [record["date"][8:] for record in filtered]
        x = np.arange(len(filtered))
        weights = [float(record.get("weight")) for record in filtered]
        weight_smooth = _moving_average(weights, window=7)
        bmr_values = [_estimate_bmr(weight, height_cm, age, gender) for weight in weights]
        bmr_smooth = _moving_average(bmr_values, window=7)

        fig, ax1 = plt.subplots(figsize=(7.4, 3.2))
        fig.patch.set_alpha(0)
        ax2 = ax1.twinx()

        raw_line = ax1.plot(x, weights, color="#BFDBFE", linewidth=1.3, alpha=0.95)[0]
        trend_line = ax1.plot(x, [value if value is not None else np.nan for value in weight_smooth], color=C_PRIMARY, linewidth=2.5, marker="o", markersize=3.4)[0]
        bmr_line = ax2.plot(x, [value if value is not None else np.nan for value in bmr_smooth], color=C_WARNING, linewidth=2.0, linestyle="--")[0]

        target_weight = profile.get("target_weight_kg")
        if target_weight is not None:
            ax1.axhline(float(target_weight), color=C_SUCCESS, linestyle=":", linewidth=1.1, alpha=0.8)

        tick_step = max(1, math.ceil(len(labels) / 7))
        ax1.set_xticks(x[::tick_step])
        ax1.set_xticklabels([labels[index] for index in range(0, len(labels), tick_step)], color=C_TEXT_MUTED, fontsize=8)
        y1_label = ax1.set_ylabel(localize(locale, "体重 (kg)", "Weight (kg)"), color=C_PRIMARY)
        y2_label = ax2.set_ylabel(localize(locale, "基础代谢 (kcal)", "BMR (kcal)"), color=C_WARNING)
        ax1.tick_params(axis="y", colors=C_PRIMARY, labelsize=8)
        ax1.tick_params(axis="x", colors=C_TEXT_MUTED, labelsize=8)
        ax2.tick_params(axis="y", colors=C_WARNING, labelsize=8)
        ax1.grid(axis="y", color=C_GRID, linestyle="--", alpha=0.45)
        ax1.spines["top"].set_visible(False)
        ax1.spines["right"].set_visible(False)
        ax1.spines["left"].set_color(C_BORDER)
        ax1.spines["bottom"].set_color(C_BORDER)
        ax2.spines["top"].set_visible(False)
        ax2.spines["right"].set_color(C_BORDER)
        _apply_tick_font(ax1, font_prop)
        _apply_tick_font(ax2, font_prop)
        _style_text(y1_label, font_prop, color=C_PRIMARY)
        _style_text(y2_label, font_prop, color=C_WARNING)

        legend_labels = [
            localize(locale, "每日体重", "Daily weight"),
            localize(locale, "7 日均线", "7-day moving average"),
            localize(locale, "估算基础代谢", "Estimated BMR"),
        ]
        legend_kwargs = {
            "handles": [raw_line, trend_line, bmr_line],
            "labels": legend_labels,
            "loc": "upper left",
            "frameon": False,
            "fontsize": 7.8,
        }
        if font_prop:
            legend_kwargs["prop"] = font_prop
        legend = ax1.legend(**legend_kwargs)
        _style_legend(legend, font_prop, fontsize=7.8)
        return _save_figure(fig)
    except Exception:
        return None


def create_symptom_distribution_chart(chart: Dict[str, object], locale: str) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE:
        return None

    try:
        font_prop = get_font_prop(locale)
        distribution = chart.get("distribution", {}) if isinstance(chart, dict) else {}
        total_days = int(chart.get("calendar_days", 0) or 0) if isinstance(chart, dict) else 0
        symptom_days = int(chart.get("symptom_days", 0) or 0) if isinstance(chart, dict) else 0
        healthy_days = int(chart.get("healthy_days", max(total_days - symptom_days, 0)) or 0) if isinstance(chart, dict) else 0
        if total_days <= 0:
            return None
        completion_rate = float(chart.get("completion_rate", healthy_days / max(total_days, 1) * 100) or 0) if isinstance(chart, dict) else 0
        healthy_label = (
            chart.get("healthy_legend")
            if isinstance(chart, dict)
            else localize(locale, f"健康无症状：{healthy_days} 天", f"Healthy symptom-free: {healthy_days} days")
        )
        symptom_label = (
            chart.get("symptom_legend")
            if isinstance(chart, dict)
            else localize(locale, f"出现不适：{symptom_days} 天", f"Symptoms present: {symptom_days} days")
        )

        fig, ax = plt.subplots(figsize=(7.8, 4.0))
        fig.patch.set_alpha(0)
        wedges, _ = ax.pie(
            [healthy_days, max(symptom_days, 0)],
            startangle=90,
            counterclock=False,
            colors=[C_SUCCESS, C_WARNING if symptom_days > 0 else C_EMPTY],
            wedgeprops={"width": 0.34, "edgecolor": "white", "linewidth": 2},
        )
        ax.set(aspect="equal")
        ax.axis("off")

        center_title = ax.text(
            0,
            0.10,
            localize(locale, "健康达标", "Healthy days"),
            ha="center",
            va="center",
            fontsize=11,
            color=C_TEXT_MUTED,
        )
        _style_text(center_title, font_prop, color=C_TEXT_MUTED, fontsize=11)
        center_value = ax.text(
            0,
            -0.08,
            localize(locale, f"{completion_rate:.0f}%", f"{completion_rate:.0f}%"),
            ha="center",
            va="center",
            fontsize=18,
            color=C_TEXT_MAIN,
        )
        _style_text(center_value, font_prop, color=C_TEXT_MAIN, fontsize=18)

        top_items = list((distribution or {}).items())[:2]
        if top_items and symptom_days > 0:
            symptom_detail = (
                "、".join(f"{label} {count}次" for label, count in top_items)
                if resolve_locale(locale=locale) == "zh-CN"
                else ", ".join(f"{label} {count}x" for label, count in top_items)
            )
            symptom_label = localize(
                locale,
                f"出现不适：{symptom_days} 天（{symptom_detail}）",
                f"Symptoms present: {symptom_days} days ({symptom_detail})",
            )

        legend = ax.legend(
            wedges,
            [healthy_label, symptom_label],
            loc="center left",
            bbox_to_anchor=(1.02, 0.5),
            frameon=False,
            fontsize=8.8,
            handlelength=1.2,
            handletextpad=0.6,
            borderaxespad=0.0,
        )
        _style_legend(legend, font_prop, fontsize=8.8)

        return _save_figure(fig)
    except Exception:
        return None


def create_intake_boxplot(records: List[dict], locale: str) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE:
        return None

    try:
        fat_values = [float(record.get("fat", 0) or 0) for record in records if record.get("fat", 0) > 0]
        carb_values = [float(record.get("carb", 0) or 0) for record in records if record.get("carb", 0) > 0]
        if len(fat_values) < 3 or len(carb_values) < 3:
            return None

        font_prop = get_font_prop(locale)
        fig, (ax_fat, ax_carb) = plt.subplots(1, 2, figsize=(7.4, 3.2))
        fig.patch.set_alpha(0)
        fat_box = ax_fat.boxplot(
            [fat_values],
            patch_artist=True,
            labels=[localize(locale, "脂肪", "Fat")],
        )
        carb_box = ax_carb.boxplot(
            [carb_values],
            patch_artist=True,
            labels=[localize(locale, "碳水", "Carb")],
        )

        for patch, color in zip(fat_box["boxes"], ["#FCD34D"]):
            patch.set_facecolor(color)
            patch.set_edgecolor(C_TEXT_MAIN)
        for patch, color in zip(carb_box["boxes"], ["#93C5FD"]):
            patch.set_facecolor(color)
            patch.set_edgecolor(C_TEXT_MAIN)

        for box_items in (fat_box, carb_box):
            for key in ("whiskers", "caps", "medians"):
                for item in box_items[key]:
                    item.set_color(C_TEXT_MAIN)

        fat_ylabel = ax_fat.set_ylabel("g", color=C_TEXT_MAIN)
        carb_ylabel = ax_carb.set_ylabel("g", color=C_TEXT_MAIN)
        fat_upper = max(50, math.ceil(max(fat_values) / 5.0) * 5)
        carb_upper = max(250, math.ceil(max(carb_values) / 25.0) * 25)
        ax_fat.set_ylim(0, fat_upper)
        ax_carb.set_ylim(0, carb_upper)

        for ax in (ax_fat, ax_carb):
            ax.tick_params(axis="y", colors=C_TEXT_MAIN, labelsize=8)
            ax.grid(axis="y", color=C_GRID, linestyle="--", alpha=0.45)
            ax.spines["top"].set_visible(False)
            ax.spines["right"].set_visible(False)
            ax.spines["left"].set_color(C_BORDER)
            ax.spines["bottom"].set_color(C_BORDER)
            _apply_tick_font(ax, font_prop)
        _style_text(fat_ylabel, font_prop, color=C_TEXT_MAIN)
        _style_text(carb_ylabel, font_prop, color=C_TEXT_MAIN)

        ax_fat.set_title(localize(locale, "脂肪波动", "Fat spread"), color=C_TEXT_MAIN, fontsize=10)
        ax_carb.set_title(localize(locale, "碳水波动", "Carb spread"), color=C_TEXT_MAIN, fontsize=10)
        _style_text(ax_fat.title, font_prop, color=C_TEXT_MAIN, fontsize=10)
        _style_text(ax_carb.title, font_prop, color=C_TEXT_MAIN, fontsize=10)

        plt.tight_layout(pad=1.0, w_pad=1.6)
        return _save_figure(fig)
    except Exception:
        return None


def create_gallstone_correlation_chart(records: List[dict], locale: str, fat_target: Optional[float] = None) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE:
        return None

    try:
        filtered = [record for record in records if record.get("fat", 0) > 0 or record.get("symptom_count", 0) > 0]
        if len(filtered) < 2:
            return None

        font_prop = get_font_prop(locale)
        labels = [record["date"][8:] for record in filtered]
        fat_values = [float(record.get("fat", 0) or 0) for record in filtered]
        symptom_values = [int(record.get("symptom_count", 0) or 0) for record in filtered]

        fig, ax1 = plt.subplots(figsize=(7.4, 3.1))
        fig.patch.set_alpha(0)
        ax2 = ax1.twinx()

        ax1.plot(labels, fat_values, color=C_WARNING, linewidth=2.2, marker="o", label=localize(locale, "脂肪摄入", "Fat intake"))
        ax2.plot(labels, symptom_values, color=C_DANGER, linewidth=2.0, marker="o", linestyle="--", label=localize(locale, "症状次数", "Symptoms"))

        if fat_target:
            ax1.axhline(y=fat_target, color=C_PRIMARY, linestyle=":", linewidth=1.4, alpha=0.8)

        ax1_label = ax1.set_ylabel(localize(locale, "脂肪 (g)", "Fat (g)"), color=C_WARNING)
        ax2_label = ax2.set_ylabel(localize(locale, "症状次数", "Symptom count"), color=C_DANGER)
        ax1.tick_params(axis="x", labelrotation=0, colors=C_TEXT_MUTED, labelsize=8)
        ax1.tick_params(axis="y", colors=C_WARNING, labelsize=8)
        ax2.tick_params(axis="y", colors=C_DANGER, labelsize=8)
        ax1.grid(axis="y", color=C_GRID, linestyle="--", alpha=0.5)
        ax1.spines["top"].set_visible(False)
        ax2.spines["top"].set_visible(False)
        ax1.spines["left"].set_color(C_BORDER)
        ax1.spines["bottom"].set_color(C_BORDER)
        ax2.spines["right"].set_color(C_BORDER)
        _apply_tick_font(ax1, font_prop)
        _apply_tick_font(ax2, font_prop)
        _style_text(ax1_label, font_prop, color=C_WARNING)
        _style_text(ax2_label, font_prop, color=C_DANGER)

        handles = [
            mpatches.Patch(color=C_WARNING, label=localize(locale, "脂肪摄入", "Fat intake")),
            mpatches.Patch(color=C_DANGER, label=localize(locale, "症状次数", "Symptoms")),
        ]
        legend_kwargs = {"handles": handles, "loc": "upper left", "frameon": False}
        if font_prop:
            legend_kwargs["prop"] = font_prop
        legend = ax1.legend(**legend_kwargs)
        _style_legend(legend, font_prop, fontsize=8)

        return _save_figure(fig)
    except Exception:
        return None


def create_bp_boxplot(bp_records: List[dict], locale: str) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE or len(bp_records) < 2:
        return None

    try:
        font_prop = get_font_prop(locale)
        systolic = [record["systolic"] for record in bp_records if record.get("systolic")]
        diastolic = [record["diastolic"] for record in bp_records if record.get("diastolic")]
        if len(systolic) < 2 or len(diastolic) < 2:
            return None

        fig, ax = plt.subplots(figsize=(5.8, 3.2))
        fig.patch.set_alpha(0)
        box = ax.boxplot(
            [systolic, diastolic],
            patch_artist=True,
            labels=[localize(locale, "收缩压", "Systolic"), localize(locale, "舒张压", "Diastolic")],
        )
        colors = [C_DANGER_LIGHT, "#BFDBFE"]
        for patch, color in zip(box["boxes"], colors):
            patch.set_facecolor(color)
            patch.set_edgecolor(C_TEXT_MAIN)
        for key in ("whiskers", "caps", "medians"):
            for item in box[key]:
                item.set_color(C_TEXT_MAIN)

        ax.axhline(140, color=C_DANGER, linestyle="--", linewidth=1.1, alpha=0.75)
        ax.axhline(90, color=C_WARNING, linestyle="--", linewidth=1.1, alpha=0.75)
        ylabel = ax.set_ylabel("mmHg", color=C_TEXT_MUTED)
        ax.grid(axis="y", color=C_GRID, linestyle="--", alpha=0.45)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color(C_BORDER)
        ax.spines["bottom"].set_color(C_BORDER)
        ax.tick_params(axis="y", colors=C_TEXT_MAIN, labelsize=8)
        _apply_tick_font(ax, font_prop)
        _style_text(ylabel, font_prop, color=C_TEXT_MAIN)
        return _save_figure(fig)
    except Exception:
        return None


def create_weight_bodyfat_chart(records: List[dict], locale: str) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE:
        return None

    try:
        filtered = [record for record in records if record.get("weight") is not None or record.get("body_fat_percent") is not None]
        if len(filtered) < 2:
            return None

        font_prop = get_font_prop(locale)
        labels = [record["date"][8:] for record in filtered]
        weights = [record.get("weight") for record in filtered]
        bodyfat = [record.get("body_fat_percent") for record in filtered]
        weight_smooth = _moving_average(weights, window=4)
        bodyfat_smooth = _moving_average(bodyfat, window=4)

        fig, ax1 = plt.subplots(figsize=(7.4, 3.1))
        fig.patch.set_alpha(0)
        ax1.plot(labels, [w if w is not None else np.nan for w in weights], color="#93C5FD", linewidth=1.2, alpha=0.8)
        ax1.plot(labels, [w if w is not None else np.nan for w in weight_smooth], color=C_PRIMARY, linewidth=2.3, marker="o")
        y1_label = ax1.set_ylabel(localize(locale, "体重 (kg)", "Weight (kg)"), color=C_PRIMARY)
        ax1.tick_params(axis="y", colors=C_PRIMARY, labelsize=8)
        ax1.tick_params(axis="x", colors=C_TEXT_MUTED, labelsize=8)
        ax1.grid(axis="y", color=C_GRID, linestyle="--", alpha=0.45)

        any_bodyfat = any(value is not None for value in bodyfat_smooth)
        if any_bodyfat:
            ax2 = ax1.twinx()
            ax2.plot(labels, [v if v is not None else np.nan for v in bodyfat], color="#C4B5FD", linewidth=1.2, alpha=0.8)
            ax2.plot(labels, [v if v is not None else np.nan for v in bodyfat_smooth], color=C_ACCENT, linewidth=2.0, marker="o", linestyle="--")
            y2_label = ax2.set_ylabel(localize(locale, "体脂率 (%)", "Body fat (%)"), color=C_ACCENT)
            ax2.tick_params(axis="y", colors=C_ACCENT, labelsize=8)
            ax2.spines["top"].set_visible(False)
            ax2.spines["right"].set_color(C_BORDER)
            _apply_tick_font(ax2, font_prop)
            _style_text(y2_label, font_prop, color=C_ACCENT)

        ax1.spines["top"].set_visible(False)
        ax1.spines["right"].set_visible(False)
        ax1.spines["left"].set_color(C_BORDER)
        ax1.spines["bottom"].set_color(C_BORDER)
        _apply_tick_font(ax1, font_prop)
        _style_text(y1_label, font_prop, color=C_PRIMARY)
        return _save_figure(fig)
    except Exception:
        return None


def create_energy_deficit_chart(records: List[dict], profile: dict, locale: str, deficit_target_kcal: float = 300) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE:
        return None

    try:
        filtered = [record for record in records if record.get("has_data") and (record.get("calories", 0) or record.get("steps", 0) or record.get("exercise_calories", 0))]
        if len(filtered) < 2:
            return None

        font_prop = get_font_prop(locale)
        age = float(profile.get("age", 30) or 30)
        height_cm = float(profile.get("height_cm", 170) or 170)
        gender = str(profile.get("gender", "male") or "male")
        fallback_weight = float(profile.get("current_weight_kg", 60) or 60)

        labels = [record["date"][8:] for record in filtered]
        x = np.arange(len(filtered))
        intake = np.array([float(record.get("calories", 0) or 0) for record in filtered])
        weights = [float(record.get("weight")) if record.get("weight") is not None else fallback_weight for record in filtered]
        bmr = np.array([_estimate_bmr(weight, height_cm, age, gender) for weight in weights])
        activity = np.array([_estimate_activity_burn(record) for record in filtered])
        tdee = bmr + activity
        intake_ceiling = max(0.0, float(np.mean(tdee)) - float(deficit_target_kcal))

        fig, ax = plt.subplots(figsize=(8.2, 3.55))
        fig.patch.set_alpha(0)
        fig.subplots_adjust(top=0.9, right=0.98)
        width = 0.38
        intake_colors = [C_WARNING if value <= target else C_DANGER for value, target in zip(intake, tdee)]

        ax.bar(x - width / 2, tdee, width=width, color=C_SUCCESS, alpha=0.85, label=localize(locale, "估算总消耗", "Estimated TDEE"))
        ax.bar(x + width / 2, intake, width=width, color=intake_colors, alpha=0.92, label=localize(locale, "当日摄入", "Daily intake"))
        target_line = ax.axhline(intake_ceiling, color=C_PRIMARY, linewidth=1.4, linestyle="--", alpha=0.85)

        ylabel = ax.set_ylabel("kcal", color=C_TEXT_MAIN)
        tick_step = max(1, math.ceil(len(labels) / 7))
        ax.set_xticks(x[::tick_step])
        ax.set_xticklabels([labels[index] for index in range(0, len(labels), tick_step)], color=C_TEXT_MUTED, fontsize=8)
        ax.tick_params(axis="x", colors=C_TEXT_MUTED, labelsize=8)
        ax.tick_params(axis="y", colors=C_TEXT_MAIN, labelsize=8)
        ax.grid(axis="y", color=C_GRID, linestyle="--", alpha=0.45)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color(C_BORDER)
        ax.spines["bottom"].set_color(C_BORDER)
        _apply_tick_font(ax, font_prop)
        _style_text(ylabel, font_prop, color=C_TEXT_MAIN)

        legend = ax.legend(
            handles=[
                mpatches.Patch(color=C_SUCCESS, label=localize(locale, "估算总消耗", "Estimated TDEE")),
                mpatches.Patch(color=C_WARNING, label=localize(locale, "摄入达标", "Intake within target")),
                mpatches.Patch(color=C_DANGER, label=localize(locale, "摄入偏高", "Intake above target")),
                target_line,
            ],
            labels=[
                localize(locale, "估算总消耗", "Estimated TDEE"),
                localize(locale, "摄入达标", "Intake within target"),
                localize(locale, "摄入偏高", "Intake above target"),
                localize(locale, "建议目标线", "Suggested intake line"),
            ],
            loc="upper right",
            bbox_to_anchor=(1.0, 1.13),
            borderaxespad=0.0,
            frameon=False,
            fontsize=7.8,
        )
        _style_legend(legend, font_prop, fontsize=7.8)

        return _save_figure(fig)
    except Exception:
        return None


def create_weekly_progression_bars(records: List[dict], locale: str) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE:
        return None

    try:
        filtered = [record for record in records if record.get("has_data")]
        if len(filtered) < 4:
            return None

        font_prop = get_font_prop(locale)
        week_slices = [filtered[0:7], filtered[7:14], filtered[14:21], filtered[21:]]
        labels = ["W1", "W2", "W3", "W4"]

        def average(bucket: List[dict], key: str) -> float:
            values = [float(item.get(key, 0) or 0) for item in bucket if item]
            return sum(values) / len(values) if values else 0.0

        steps = [average(bucket, "steps") for bucket in week_slices]
        water = [average(bucket, "water_total") for bucket in week_slices]
        calories = [average(bucket, "calories") for bucket in week_slices]

        fig, axes = plt.subplots(1, 3, figsize=(9.4, 3.2))
        fig.patch.set_alpha(0)
        plots = [
            (axes[0], steps, C_PRIMARY, localize(locale, "日均步数", "Avg steps"), ""),
            (axes[1], water, C_SUCCESS, localize(locale, "日均饮水", "Avg hydration"), "ml"),
            (axes[2], calories, C_WARNING, localize(locale, "日均热量", "Avg calories"), "kcal"),
        ]

        for ax, values, color, title, unit in plots:
            bars = ax.bar(labels, values, color=color, alpha=0.88, width=0.6)
            ax.set_title(title, color=C_TEXT_MAIN, fontsize=9.6)
            ax.grid(axis="y", color=C_GRID, linestyle="--", alpha=0.38)
            ax.spines["top"].set_visible(False)
            ax.spines["right"].set_visible(False)
            ax.spines["left"].set_color(C_BORDER)
            ax.spines["bottom"].set_color(C_BORDER)
            ax.tick_params(axis="x", colors=C_TEXT_MUTED, labelsize=8)
            ax.tick_params(axis="y", colors=C_TEXT_MAIN, labelsize=7.8)
            _apply_tick_font(ax, font_prop)
            _style_text(ax.title, font_prop, color=C_TEXT_MAIN, fontsize=9.6)
            ymax = max(values) if values else 0
            ax.set_ylim(0, max(1, ymax * 1.25))
            for bar, value in zip(bars, values):
                label = f"{int(round(value))}{unit}" if unit else f"{int(round(value))}"
                text = ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + max(1, ymax * 0.04),
                    label,
                    ha="center",
                    va="bottom",
                    fontsize=7.2,
                    color=C_TEXT_MAIN,
                )
                _style_text(text, font_prop, color=C_TEXT_MAIN, fontsize=7.2)

        plt.tight_layout(w_pad=1.4)
        return _save_figure(fig)
    except Exception:
        return None


def create_body_composition_area_chart(records: List[dict], locale: str) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE:
        return None

    try:
        filtered = [
            record
            for record in records
            if record.get("weight") is not None and record.get("body_fat_percent") is not None
        ]
        if len(filtered) < 2:
            return None

        font_prop = get_font_prop(locale)
        labels = [record["date"][8:] for record in filtered]
        x = np.arange(len(filtered))
        weights = np.array([float(record.get("weight", 0) or 0) for record in filtered])
        bodyfat = np.array([float(record.get("body_fat_percent", 0) or 0) for record in filtered])
        lbm = weights * (1 - bodyfat / 100.0)
        fat_mass = np.maximum(weights - lbm, 0)

        fig, ax = plt.subplots(figsize=(8.2, 3.3))
        fig.patch.set_alpha(0)
        layers = ax.stackplot(x, lbm, fat_mass, colors=[C_PRIMARY, "#FDE68A"], alpha=0.92)

        tick_step = max(1, math.ceil(len(labels) / 7))
        ax.set_xticks(x[::tick_step])
        ax.set_xticklabels([labels[index] for index in range(0, len(labels), tick_step)], color=C_TEXT_MUTED, fontsize=8)
        ylabel = ax.set_ylabel(localize(locale, "体重组成 (kg)", "Body composition (kg)"), color=C_TEXT_MAIN)
        ax.tick_params(axis="x", colors=C_TEXT_MUTED, labelsize=8)
        ax.tick_params(axis="y", colors=C_TEXT_MAIN, labelsize=8)
        ax.grid(axis="y", color=C_GRID, linestyle="--", alpha=0.45)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color(C_BORDER)
        ax.spines["bottom"].set_color(C_BORDER)
        _apply_tick_font(ax, font_prop)
        _style_text(ylabel, font_prop, color=C_TEXT_MAIN)

        legend = ax.legend(
            layers,
            [localize(locale, "去脂体重", "Lean mass"), localize(locale, "脂肪重量", "Fat mass")],
            loc="upper left",
            frameon=False,
            fontsize=8,
        )
        _style_legend(legend, font_prop, fontsize=8)
        return _save_figure(fig)
    except Exception:
        return None


def create_glucose_trend_chart(glucose_records: List[dict], locale: str) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE or len(glucose_records) < 2:
        return None

    try:
        font_prop = get_font_prop(locale)
        sorted_records = sorted(glucose_records, key=lambda item: (item.get("date", ""), item.get("time", "")))
        labels = [record["date"][8:] for record in sorted_records]
        values = [float(record.get("value", 0) or 0) for record in sorted_records]
        if max(values) <= 0:
            return None

        fig, ax = plt.subplots(figsize=(7.4, 3.1))
        fig.patch.set_alpha(0)
        ax.plot(labels, values, color=C_PRIMARY, linewidth=2.2, marker="o")
        ax.axhspan(3.9, 7.8, color=C_SUCCESS_LIGHT, alpha=0.18)
        ax.grid(axis="y", color=C_GRID, linestyle="--", alpha=0.45)
        ylabel = ax.set_ylabel(localize(locale, "血糖 (mmol/L)", "Glucose (mmol/L)"), color=C_TEXT_MAIN)
        ax.tick_params(axis="x", colors=C_TEXT_MUTED, labelsize=8)
        ax.tick_params(axis="y", colors=C_TEXT_MAIN, labelsize=8)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color(C_BORDER)
        ax.spines["bottom"].set_color(C_BORDER)
        _apply_tick_font(ax, font_prop)
        _style_text(ylabel, font_prop, color=C_TEXT_MAIN)
        return _save_figure(fig)
    except Exception:
        return None


def create_custom_metric_chart(chart_data: dict, locale: str) -> Optional[str]:
    if not MATPLOTLIB_AVAILABLE:
        return None

    try:
        points = chart_data.get("points", [])
        if len(points) < 2:
            return None
        font_prop = get_font_prop(locale)
        labels = [point["date"][8:] for point in points]
        values = [float(point.get("value", 0) or 0) for point in points]
        if max(values) <= 0:
            return None

        fig, ax = plt.subplots(figsize=(7.4, 3.1))
        fig.patch.set_alpha(0)
        ax.plot(labels, values, color=C_PRIMARY, linewidth=2.2, marker="o")
        ax.fill_between(labels, values, [min(values)] * len(values), color=C_PRIMARY, alpha=0.12)
        ylabel_text = chart_data.get("unit") or localize(locale, "数值", "Value")
        ylabel = ax.set_ylabel(ylabel_text, color=C_TEXT_MAIN)
        ax.tick_params(axis="x", colors=C_TEXT_MUTED, labelsize=8)
        ax.tick_params(axis="y", colors=C_TEXT_MAIN, labelsize=8)
        ax.grid(axis="y", color=C_GRID, linestyle="--", alpha=0.45)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color(C_BORDER)
        ax.spines["bottom"].set_color(C_BORDER)
        _apply_tick_font(ax, font_prop)
        _style_text(ylabel, font_prop, color=C_TEXT_MAIN)
        return _save_figure(fig)
    except Exception:
        return None


def split_structured_review(review_text: str) -> List[dict]:
    sections: List[dict] = []
    current_title = ""
    current_lines: List[str] = []

    for raw_line in str(review_text or "").splitlines():
        line = raw_line.strip()
        if not line:
            if current_lines and current_lines[-1] != "":
                current_lines.append("")
            continue

        match = re.match(r"^(?:\*\*)?(【[^】]+】|\[[^\]]+\])(?:\*\*)?\s*(.*)$", line)
        if match:
            if current_title or current_lines:
                sections.append({"title": current_title, "body": "\n".join(current_lines).strip()})
            current_title = match.group(1).strip()
            trailing = match.group(2).strip()
            current_lines = [trailing] if trailing else []
            continue

        current_lines.append(line)

    if current_title or current_lines:
        sections.append({"title": current_title, "body": "\n".join(current_lines).strip()})

    return [section for section in sections if section.get("title") or section.get("body")] or [
        {"title": "", "body": str(review_text or "").strip()}
    ]


def generate_monthly_pdf_report(
    monthly_data: dict,
    profile: dict,
    ai_review: str,
    output_path: str,
    locale: str = "zh-CN",
    review_source: str = "fallback",
    recommendation_source: str = "fallback",
) -> None:
    locale = resolve_locale(locale=locale)
    font_name = register_chinese_font(locale)
    render_notice = str(monthly_data.get("render_notice") or "").strip()
    primary_condition = monthly_data.get("primary_condition")
    population_branch = monthly_data.get("population_branch")
    lifestyle_mode = is_lifestyle_mode(primary_condition, population_branch)
    deep_dive_title = monthly_section_label(locale, primary_condition, "deep_dive", population_branch)
    action_plan_title = monthly_section_label(locale, primary_condition, "action_plan", population_branch)
    ai_review_title = monthly_section_label(locale, primary_condition, "ai_review", population_branch)
    follow_up_title = monthly_section_label(locale, primary_condition, "follow_up", population_branch)
    hospital_title = monthly_section_label(locale, primary_condition, "hospital", population_branch)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=1.6 * cm,
        leftMargin=1.6 * cm,
        topMargin=1.6 * cm,
        bottomMargin=1.4 * cm,
        title=localize(locale, "健康月报", "Monthly Health Report"),
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], fontSize=22, textColor=HexColor(C_PRIMARY), spaceAfter=5, alignment=TA_CENTER, fontName=font_name)
    sub_title = ParagraphStyle("SubTitle", parent=styles["Normal"], fontSize=10, textColor=HexColor(C_TEXT_MUTED), spaceAfter=14, alignment=TA_CENTER, fontName=font_name)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"], fontSize=14, textColor=HexColor(C_PRIMARY), spaceBefore=12, spaceAfter=8, fontName=font_name)
    sub_heading_style = ParagraphStyle("SubHeading", parent=styles["Heading3"], fontSize=11, textColor=HexColor(C_TEXT_MAIN), spaceBefore=6, spaceAfter=4, fontName=font_name)
    normal_style = ParagraphStyle("NormalText", parent=styles["Normal"], fontSize=9.6, textColor=HexColor(C_TEXT_MAIN), fontName=font_name, leading=16)
    muted_style = ParagraphStyle("Muted", parent=normal_style, textColor=HexColor(C_TEXT_MUTED), fontSize=8.5, leading=13)
    footer_style = ParagraphStyle("Footer", parent=normal_style, fontSize=9, textColor=HexColor(C_TEXT_MUTED), alignment=TA_CENTER, leading=13)
    source_note_style = ParagraphStyle("SourceNote", parent=muted_style, alignment=TA_RIGHT, fontSize=8, spaceBefore=3, spaceAfter=0)
    notice_style = ParagraphStyle("RenderNotice", parent=normal_style, backColor=HexColor("#FFF7ED"), borderColor=HexColor(C_WARNING), borderWidth=0.8, borderPadding=8, leading=14, spaceAfter=10)
    card_title_style = ParagraphStyle("CardTitle", parent=normal_style, fontSize=10, textColor=HexColor(C_PRIMARY), fontName=font_name, leading=14)
    review_body_style = ParagraphStyle("ReviewBody", parent=normal_style, leading=15, spaceAfter=0)

    story: List = []
    temp_images: List[str] = []

    def add_bullet_lines(lines: Iterable[str]) -> None:
        for line in lines:
            clean = clean_html_tags(str(line or "")).strip()
            if not clean:
                continue
            story.append(Paragraph(f"<font color='{C_PRIMARY}'>■</font> {clean}", normal_style))
            story.append(Spacer(1, 0.05 * cm))

    def add_source_note(value: str) -> None:
        story.append(Paragraph(clean_html_tags(value), source_note_style))

    def add_review_cards(review_text: str) -> None:
        for section in split_structured_review(review_text):
            title = clean_html_tags(section.get("title", "")).strip()
            body = clean_html_tags(section.get("body", "")).strip()
            if not title and not body:
                continue

            card_content: List = []
            if title:
                card_content.append(Paragraph(f"<b>{title}</b>", card_title_style))
            if body:
                card_content.append(Paragraph(body.replace("\n", "<br/>"), review_body_style))

            story.append(
                KeepTogether(
                    [
                        Table(
                            [[card_content]],
                            colWidths=[16.2 * cm],
                            style=TableStyle(
                                [
                                    ("BACKGROUND", (0, 0), (-1, -1), HexColor(C_BG_SOFT)),
                                    ("BOX", (0, 0), (-1, -1), 0.6, HexColor(C_BORDER)),
                                    ("INNERPADDING", (0, 0), (-1, -1), 8),
                                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                                ]
                            ),
                        ),
                        Spacer(1, 0.12 * cm),
                    ]
                )
            )

    def build_chart(chart: dict) -> Optional[str]:
        chart_type = chart.get("type")
        if chart_type == "energy_deficit":
            return create_energy_deficit_chart(
                chart.get("records", []),
                profile,
                locale,
                deficit_target_kcal=chart.get("deficit_target_kcal", 300),
            )
        if chart_type == "weekly_progression":
            return create_weekly_progression_bars(chart.get("records", []), locale)
        if chart_type == "body_composition_area":
            return create_body_composition_area_chart(chart.get("records", []), locale)
        if chart_type == "gallstones":
            return create_gallstone_correlation_chart(chart.get("records", []), locale, fat_target=chart.get("fat_target"))
        if chart_type == "symptom_distribution":
            return create_symptom_distribution_chart(chart, locale)
        if chart_type == "intake_boxplot":
            return create_intake_boxplot(chart.get("records", []), locale)
        if chart_type == "hypertension":
            return create_bp_boxplot(chart.get("bp_records", []), locale)
        if chart_type == "fat_loss":
            return create_weight_bodyfat_chart(chart.get("records", []), locale)
        if chart_type == "diabetes":
            return create_glucose_trend_chart(chart.get("glucose_records", []), locale)
        if chart_type == "custom_metric":
            return create_custom_metric_chart(chart, locale)
        return None

    try:
        story.append(Paragraph(f"<b>{profile_condition_title(profile, locale)} · {localize(locale, '健康月报', 'Monthly Health Report')}</b>", title_style))
        story.append(Paragraph(localize(locale, f"评估周期：{monthly_data.get('start_date')} 至 {monthly_data.get('end_date')} | 监测人：{profile.get('name', '-')}", f"Period: {monthly_data.get('start_date')} to {monthly_data.get('end_date')} | User: {profile.get('name', '-')}"), sub_title))
        if render_notice:
            story.append(Paragraph(f"<b>{localize(locale, '渲染说明', 'Rendering Notice')}</b><br/>{clean_html_tags(render_notice)}", notice_style))

        story.append(Paragraph("1. " + localize(locale, "宏观依从性与状态全景", "Macro Overview"), heading_style))

        radar_path = create_macro_radar_chart(monthly_data.get("macro_scores", {}), locale)
        if lifestyle_mode:
            heatmap_path = create_activity_heatmap(
                monthly_data.get("daily_records", []),
                locale,
                step_target=int(profile.get("step_target", 8000) or 8000),
            )
        else:
            heatmap_path = create_symptom_heatmap(monthly_data.get("daily_records", []), locale)
        weight_trend_path = create_weight_bmr_trend_chart(monthly_data.get("daily_records", []), profile, locale)
        if radar_path:
            temp_images.append(radar_path)
        if heatmap_path:
            temp_images.append(heatmap_path)
        if weight_trend_path:
            temp_images.append(weight_trend_path)

        if radar_path and heatmap_path:
            chart_table = Table([[_build_chart_image(radar_path, 7.2, 6.2), _build_chart_image(heatmap_path, 10.0, 5.2)]], colWidths=[7.4 * cm, 10.2 * cm])
            chart_table.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("ALIGN", (0, 0), (-1, -1), "CENTER")]))
            story.append(chart_table)
        elif radar_path:
            story.append(_build_chart_image(radar_path, 10.2, 8.2))
        elif heatmap_path:
            story.append(_build_chart_image(heatmap_path, 16.2, 5.7))

        if heatmap_path:
            story.append(
                Paragraph(
                    localize(
                        locale,
                        "热力图颜色越深，表示当天步数/运动完成度越高；浅灰色表示休息或未达标。",
                        "Darker heatmap cells indicate stronger daily activity; light gray marks rest days or below-target days.",
                    )
                    if lifestyle_mode
                    else localize(locale, "热力图右上角 “M” 表示该日有用药记录。", "In the heatmap, the corner marker 'M' indicates a medication day."),
                    muted_style,
                )
            )

        story.append(Spacer(1, 0.18 * cm))
        summary_rows = [
            [localize(locale, "指标", "Metric"), localize(locale, "结果", "Result")],
            [localize(locale, "饮食达标率", "Diet goal rate"), f"{monthly_data.get('macro_scores', {}).get('diet', 0):.0f}%"],
            [localize(locale, "饮水达标率", "Hydration goal rate"), f"{monthly_data.get('macro_scores', {}).get('water', 0):.0f}%"],
            [localize(locale, "运动达标率", "Exercise goal rate"), f"{monthly_data.get('macro_scores', {}).get('exercise', 0):.0f}%"],
            [localize(locale, "用药覆盖率", "Medication coverage"), f"{monthly_data.get('macro_scores', {}).get('medication', 0):.0f}%"],
            [localize(locale, "监测覆盖率", "Monitoring coverage"), f"{monthly_data.get('macro_scores', {}).get('monitoring', 0):.0f}%"],
            [localize(locale, "症状天数", "Symptom days"), f"{monthly_data.get('symptom_days', 0)} / {monthly_data.get('observed_days', 0)}"],
            [localize(locale, "月均综合评分", "Average overall score"), f"{monthly_data.get('avg_total_score', 0):.1f}/100"],
        ]
        overview_table = Table(summary_rows, colWidths=[5.2 * cm, 10.8 * cm])
        overview_table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), HexColor(C_BG_HEAD)), ("TEXTCOLOR", (0, 0), (-1, 0), HexColor(C_TEXT_MUTED)), ("TEXTCOLOR", (0, 1), (-1, -1), HexColor(C_TEXT_MAIN)), ("FONTNAME", (0, 0), (-1, -1), font_name), ("FONTSIZE", (0, 0), (-1, -1), 9), ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6), ("LINEBELOW", (0, 0), (-1, -1), 0.5, HexColor(C_BORDER)), ("ALIGN", (0, 0), (-1, -1), "CENTER")]))
        story.append(overview_table)
        if weight_trend_path:
            story.append(Spacer(1, 0.16 * cm))
            story.append(Paragraph(localize(locale, "体重与基础代谢趋势", "Weight And BMR Trend"), sub_heading_style))
            story.append(
                Paragraph(
                    localize(locale, "浅色为每日体重，深色为 7 日移动平均，橙色虚线为按当前体重估算的基础代谢。", "The pale line shows daily weight, the darker line is the 7-day moving average, and the dashed orange line is the estimated BMR."),
                    muted_style,
                )
            )
            story.append(_build_chart_image(weight_trend_path, 16.0, 5.0))
        story.append(Spacer(1, 0.18 * cm))
        add_bullet_lines(monthly_data.get("macro_highlights", []))

        story.append(PageBreak())
        story.append(Paragraph("2. " + deep_dive_title, heading_style))
        specialty_charts = monthly_data.get("specialty_charts", [])
        if specialty_charts:
            for chart in specialty_charts:
                story.append(Paragraph(clean_html_tags(chart.get("title", "")), sub_heading_style))
                subtitle = clean_html_tags(chart.get("subtitle", ""))
                if subtitle:
                    story.append(Paragraph(subtitle, muted_style))
                chart_path = build_chart(chart)
                if chart_path:
                    temp_images.append(chart_path)
                    if chart.get("type") == "symptom_distribution":
                        story.append(_build_chart_image(chart_path, 15.8, 4.3))
                    else:
                        story.append(_build_chart_image(chart_path, 16.0, 5.0))
                story.append(Spacer(1, 0.08 * cm))
                chart_summary = clean_html_tags(chart.get("summary", ""))
                if chart_summary:
                    story.append(Paragraph(chart_summary, normal_style))
                story.append(Spacer(1, 0.18 * cm))
        else:
            story.append(
                Paragraph(
                    localize(
                        locale,
                        "当前月份缺少足够的病种专项数据，因此本页保留为监测说明。后续只要按协议写入血压、血糖、体脂或生化模块，月报会自动追加图表。",
                        "This month does not yet contain enough specialty metrics for a dedicated chart. Once blood pressure, glucose, body-fat, or lab modules are logged with the protocol, the monthly report will append those charts automatically.",
                    ),
                    normal_style,
                )
            )

        custom_blocks = monthly_data.get("custom_monitoring_summary", [])
        if custom_blocks:
            story.append(Paragraph(localize(locale, "附加监测模块", "Additional Monitoring"), sub_heading_style))
            for block in custom_blocks:
                title = clean_html_tags(block.get("title", ""))
                lines = block.get("lines", [])
                card = [Paragraph(f"<b>{title}</b>", card_title_style)]
                for line in lines[:4]:
                    card.append(Paragraph(clean_html_tags(line), normal_style))
                story.append(
                    KeepTogether(
                        [
                            Table(
                                [[card]],
                                colWidths=[16.2 * cm],
                                style=TableStyle(
                                    [
                                        ("BACKGROUND", (0, 0), (-1, -1), HexColor(C_BG_SOFT)),
                                        ("BOX", (0, 0), (-1, -1), 0.6, HexColor(C_BORDER)),
                                        ("INNERPADDING", (0, 0), (-1, -1), 8),
                                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                                    ]
                                ),
                            ),
                            Spacer(1, 0.12 * cm),
                        ]
                    )
                )

        story.append(PageBreak())
        story.append(Paragraph("3. " + action_plan_title, heading_style))

        residence_text = clean_html_tags(monthly_data.get("residence_text") or localize(locale, "未配置常居地", "Residence not configured"))
        profile_rows = [
            [localize(locale, "姓名", "Name"), clean_html_tags(profile.get("name", "-"))],
            [localize(locale, "管理目标", "Conditions"), clean_html_tags(profile_condition_title(profile, locale))],
            [localize(locale, "年龄 / 身高", "Age / Height"), f"{profile.get('age', '-')} / {profile.get('height_cm', '-')}cm"],
            [localize(locale, "当前 / 目标体重", "Current / Target weight"), f"{format_weight(locale, monthly_data.get('latest_weight') or profile.get('current_weight_kg'))} / {format_weight(locale, profile.get('target_weight_kg'))}"],
            [localize(locale, "常居地", "Residence"), residence_text],
        ]
        profile_table = Table(profile_rows, colWidths=[4.2 * cm, 11.8 * cm])
        profile_table.setStyle(TableStyle([("BACKGROUND", (0, 0), (0, -1), HexColor(C_BG_HEAD)), ("TEXTCOLOR", (0, 0), (-1, -1), HexColor(C_TEXT_MAIN)), ("FONTNAME", (0, 0), (-1, -1), font_name), ("FONTSIZE", (0, 0), (-1, -1), 9), ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6), ("GRID", (0, 0), (-1, -1), 0.5, HexColor(C_BORDER))]))
        story.append(profile_table)
        story.append(Spacer(1, 0.18 * cm))

        story.append(Paragraph(ai_review_title, sub_heading_style))
        add_review_cards(ai_review)
        add_source_note(source_text(locale, review_source))
        story.append(Spacer(1, 0.18 * cm))

        followups = monthly_data.get("follow_up_reminders", [])
        if followups:
            story.append(Paragraph(follow_up_title, sub_heading_style))
            add_bullet_lines(followups)

        recommendation_groups = monthly_data.get("hospital_recommendation_groups", [])
        if not lifestyle_mode:
            story.append(Paragraph(hospital_title, sub_heading_style))
            if recommendation_groups:
                for group_index, group in enumerate(recommendation_groups):
                    hospital_name = clean_html_tags(group.get("hospital", "-"))
                    if group_index == 0:
                        hospital_name = localize(locale, f"{hospital_name}（首推）", f"{hospital_name} (Top Choice)")
                    hospital_stars_html = stars_to_text(group.get("hospital_stars", ""))
                    story.append(Paragraph(f"<b>{hospital_name}</b> {hospital_stars_html}", card_title_style))
                    hospital_lines = [
                        localize(locale, f"医院等级：{group.get('hospital_grade', '-')}", f"Hospital grade: {group.get('hospital_grade', '-')}"),
                        localize(locale, f"医院优势：{group.get('hospital_strength', '-')}", f"Hospital strengths: {group.get('hospital_strength', '-')}"),
                    ]
                    if group.get("hospital_address"):
                        hospital_lines.append(localize(locale, f"医院地址：{group.get('hospital_address')}", f"Address: {group.get('hospital_address')}"))
                    if group.get("booking_method"):
                        hospital_lines.append(localize(locale, f"挂号方式：{group.get('booking_method')}", f"Booking: {group.get('booking_method')}"))
                    add_bullet_lines(hospital_lines)
                    for doctor in group.get("doctors", []):
                        doctor_name = clean_html_tags(doctor.get("doctor_name", "-"))
                        doctor_title = clean_html_tags(doctor.get("doctor_title", localize(locale, "医生", "Doctor")))
                        doctor_stars_html = stars_to_text(doctor.get("doctor_stars", ""))
                        doctor_heading = localize(
                            locale,
                            f"{doctor_name}【{doctor_title}】",
                            f"{doctor_name} [{doctor_title}]",
                        )
                        story.append(Paragraph(f"<b>{doctor_heading}</b> {doctor_stars_html}", normal_style))
                        doctor_lines = [
                            localize(locale, f"推荐科室：{doctor.get('department', '-')}", f"Recommended department: {doctor.get('department', '-')}"),
                            localize(locale, f"医生擅长：{doctor.get('doctor_specialty', '-')}", f"Doctor specialty: {doctor.get('doctor_specialty', '-')}"),
                            localize(locale, f"挂号费：{doctor.get('registration_fee', '-')}", f"Registration fee: {doctor.get('registration_fee', '-')}"),
                            localize(locale, f"坐诊时间：{doctor.get('clinic_schedule', '-')}", f"Clinic schedule: {doctor.get('clinic_schedule', '-')}"),
                            localize(locale, f"推荐理由：{doctor.get('reason', '-')}", f"Recommendation reason: {doctor.get('reason', '-')}"),
                        ]
                        add_bullet_lines(doctor_lines)
                        story.append(Spacer(1, 0.08 * cm))
                    story.append(Spacer(1, 0.08 * cm))
            else:
                story.append(
                    Paragraph(
                        localize(
                            locale,
                            "当前没有足够的居住地或检索信息来生成医院名单。请在 user_config.json 中补充常居地后再生成月报。",
                            "There is not enough residence or retrieval information to suggest hospitals yet. Add residence details to user_config.json and regenerate the monthly report.",
                        ),
                        normal_style,
                    )
                )
            add_source_note(source_text(locale, recommendation_source))

        story.append(Spacer(1, 0.16 * cm))
        story.append(
            Paragraph(
                localize(locale, f"报告生成时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", f"Report generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"),
                footer_style,
            )
        )
        story.append(Paragraph(f"{profile_condition_title(profile, locale)} - Health-Mate", footer_style))

        doc.build(story)
    finally:
        for image_path in temp_images:
            if image_path and os.path.exists(image_path):
                try:
                    os.unlink(image_path)
                except OSError:
                    pass
