#!/usr/bin/env node
/**
 * setup.mjs — one-time config wizard for appstore-brand-monitor
 *
 * Reads Lark App ID/Secret from OpenClaw config automatically.
 * Asks for alert recipient ID only.
 * Generates .env file.
 *
 * Usage: node setup.mjs
 */
import fs from 'fs';
import path from 'path';
import os from 'os';
import readline from 'readline';

const SKILL_DIR = path.dirname(new URL(import.meta.url).pathname);
const ENV_FILE  = path.join(SKILL_DIR, '.env');
const HOME      = os.homedir();

function readJson(filePath) {
  try { return JSON.parse(fs.readFileSync(filePath, 'utf8')); }
  catch { return null; }
}

function ask(rl, question) {
  return new Promise(resolve => rl.question(question, resolve));
}

async function main() {
  console.log('🔧 appstore-brand-monitor setup\n');

  const config = {};

  // Auto-read Lark credentials from OpenClaw config
  const openclawJson = readJson(path.join(HOME, '.openclaw/openclaw.json'));
  const feishuAccounts = openclawJson?.channels?.feishu?.accounts;
  const larkAccount = feishuAccounts?.[0];

  if (larkAccount?.appId && larkAccount?.appSecret) {
    console.log(`✅ Lark App: ${larkAccount.appId} — auto-read from OpenClaw`);
    config.LARK_APP_ID     = larkAccount.appId;
    config.LARK_APP_SECRET = larkAccount.appSecret;
  } else {
    console.log('⚠️  Lark credentials not found in OpenClaw config');
  }

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  // Prompt for Lark credentials if not auto-read
  if (!config.LARK_APP_ID) {
    config.LARK_APP_ID     = (await ask(rl, 'Enter Lark App ID: ')).trim();
    config.LARK_APP_SECRET = (await ask(rl, 'Enter Lark App Secret: ')).trim();
  }

  // Alert recipient
  config.ALERT_RECEIVER_ID = (await ask(rl, 'Enter alert recipient open_id or chat_id: ')).trim();

  rl.close();

  // Write .env
  const envContent = `# App Store brand monitor config (generated by setup.mjs)

# Lark app credentials
LARK_APP_ID=${config.LARK_APP_ID}
LARK_APP_SECRET=${config.LARK_APP_SECRET}

# Alert recipient: personal open_id (ou_xxx) or group chat_id (oc_xxx)
ALERT_RECEIVER_ID=${config.ALERT_RECEIVER_ID}
`;

  fs.writeFileSync(ENV_FILE, envContent, 'utf8');
  console.log(`\n✅ Config saved to ${ENV_FILE}`);
  console.log('\nRun a scan:');
  console.log('  node search.js --country ph --keyword Atome');
}

main().catch(e => {
  console.error('❌ Setup failed:', e.message);
  process.exit(1);
});
