#!/usr/bin/env python3
"""
MBTI Questions Bank
Four versions: 70, 93, 144, 200 questions
"""

QUESTIONS = {
    # ========== VERSION 70 (Quick) ==========
    70: [
        # Energy - EI (17 questions)
        {"id": 1, "dimension": "EI", "option_a": "在聚会中，你通常是...", "option_b": "和很多人热烈交谈，从中获得能量", "preference_a": "E"},
        {"id": 2, "dimension": "EI", "option_a": "独处时你感到...", "option_b": "需要社交来充电", "preference_a": "I"},
        {"id": 3, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "和人聊天", "preference_a": "E"},
        {"id": 4, "dimension": "EI", "option_a": "你倾向于...", "option_b": "先行动后思考", "preference_a": "E"},
        {"id": 5, "dimension": "EI", "option_a": "你更愿意...", "option_b": "和一群人一起工作", "preference_a": "E"},
        {"id": 6, "dimension": "EI", "option_a": "社交活动让你...", "option_b": "充满活力", "preference_a": "E"},
        {"id": 7, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "团队讨论", "preference_a": "E"},
        {"id": 8, "dimension": "EI", "option_a": "在空闲时间，你更倾向于...", "option_b": "和朋友出去玩", "preference_a": "E"},
        {"id": 9, "dimension": "EI", "option_a": "你通过...获得能量", "option_b": "与人互动", "preference_a": "E"},
        {"id": 10, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "外出社交", "preference_a": "E"},
        {"id": 11, "dimension": "EI", "option_a": "独处让你...", "option_b": "恢复精力", "preference_a": "I"},
        {"id": 12, "dimension": "EI", "option_a": "你更享受...", "option_b": "一对一的深度对话", "preference_a": "I"},
        {"id": 13, "dimension": "EI", "option_a": "你倾向于...", "option_b": "先思考后行动", "preference_a": "I"},
        {"id": 14, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "独自工作", "preference_a": "I"},
        {"id": 15, "dimension": "EI", "option_a": "社交活动让你...", "option_b": "感到疲惫", "preference_a": "I"},
        {"id": 16, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "安静的环境", "preference_a": "I"},
        {"id": 17, "dimension": "EI", "option_a": "在空闲时间，你更倾向于...", "option_b": "独自阅读或思考", "preference_a": "I"},
        
        # Information - SN (18 questions)
        {"id": 18, "dimension": "SN", "option_a": "你更看重...", "option_b": "实际的数据和事实", "preference_a": "S"},
        {"id": 19, "dimension": "SN", "option_a": "你更相信...", "option_b": "具体的信息", "preference_a": "S"},
        {"id": 20, "dimension": "SN", "option_a": "你更倾向于...", "option_b": "关注细节", "preference_a": "S"},
        {"id": 21, "dimension": "SN", "option_a": "你更喜欢...", "option_b": "已知的方法", "preference_a": "S"},
        {"id": 22, "dimension": "SN", "option_a": "你更关注...", "option_b": "现实情况", "preference_a": "S"},
        {"id": 23, "dimension": "SN", "option_a": "你更愿意...", "option_b": "按照计划执行", "preference_a": "S"},
        {"id": 24, "dimension": "SN", "option_a": "你更喜欢...", "option_b": "处理具体问题", "preference_a": "S"},
        {"id": 25, "dimension": "SN", "option_a": "你更看重...", "option_b": "经验和事实", "preference_a": "S"},
        {"id": 26, "dimension": "SN", "option_a": "你更倾向于...", "option_b": "使用既定的流程", "preference_a": "S"},
        {"id": 27, "dimension": "SN", "option_a": "你更相信...", "option_b": "实际经验", "preference_a": "S"},
        {"id": 28, "dimension": "SN", "option_a": "你更关注...", "option_b": "此时此刻", "preference_a": "S"},
        {"id": 29, "dimension": "SN", "option_a": "你更愿意...", "option_b": "相信看到的", "preference_a": "S"},
        {"id": 30, "dimension": "SN", "option_a": "你更喜欢...", "option_b": "可能性和想象", "preference_a": "N"},
        {"id": 31, "dimension": "SN", "option_a": "你更相信...", "option_b": "直觉", "preference_a": "N"},
        {"id": 32, "dimension": "SN", "option_a": "你更倾向于...", "option_b": "关注整体", "preference_a": "N"},
        {"id": 33, "dimension": "SN", "option_a": "你更喜欢...", "option_b": "新的想法", "preference_a": "N"},
        {"id": 34, "dimension": "SN", "option_a": "你更关注...", "option_b": "未来可能性", "preference_a": "N"},
        {"id": 35, "dimension": "SN", "option_a": "你更愿意...", "option_b": "尝试新方法", "preference_a": "N"},
        
        # Decisions - TF (18 questions)
        {"id": 36, "dimension": "TF", "option_a": "做决定时你更看重...", "option_b": "逻辑和一致性", "preference_a": "T"},
        {"id": 37, "dimension": "TF", "option_a": "你更倾向于...", "option_b": "公平对待每个人", "preference_a": "T"},
        {"id": 38, "dimension": "TF", "option_a": "你更重视...", "option_b": "原则和规则", "preference_a": "T"},
        {"id": 39, "dimension": "TF", "option_a": "你做决定时...", "option_b": "基于事实分析", "preference_a": "T"},
        {"id": 40, "dimension": "TF", "option_a": "你更倾向于...", "option_b": "用理性判断", "preference_a": "T"},
        {"id": 41, "dimension": "TF", "option_a": "你更重视...", "option_b": "正确的分析", "preference_a": "T"},
        {"id": 42, "dimension": "TF", "option_a": "你做决定时...", "option_b": "遵循逻辑", "preference_a": "T"},
        {"id": 43, "dimension": "TF", "option_a": "你更看重...", "option_b": "客观原因", "preference_a": "T"},
        {"id": 44, "dimension": "TF", "option_a": "你更倾向于...", "option_b": "批评错误", "preference_a": "T"},
        {"id": 45, "dimension": "TF", "option_a": "你更重视...", "option_b": "真相", "preference_a": "T"},
        {"id": 46, "dimension": "TF", "option_a": "做决定时你更看重...", "option_b": "对人的影响", "preference_a": "F"},
        {"id": 47, "dimension": "TF", "option_a": "你更倾向于...", "option_b": "考虑他人感受", "preference_a": "F"},
        {"id": 48, "dimension": "TF", "option_a": "你更重视...", "option_b": "人际关系", "preference_a": "F"},
        {"id": 49, "dimension": "TF", "option_a": "你做决定时...", "option_b": "考虑情感因素", "preference_a": "F"},
        {"id": 50, "dimension": "TF", "option_a": "你更倾向于...", "option_b": "体谅他人", "preference_a": "F"},
        {"id": 51, "dimension": "TF", "option_a": "你更重视...", "option_b": "和谐", "preference_a": "F"},
        {"id": 52, "dimension": "TF", "option_a": "你做决定时...", "option_b": "考虑价值观", "preference_a": "F"},
        {"id": 53, "dimension": "TF", "option_a": "你更看重...", "option_b": "情感联系", "preference_a": "F"},
        
        # Structure - JP (17 questions)
        {"id": 54, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "有计划的生活", "preference_a": "J"},
        {"id": 55, "dimension": "JP", "option_a": "你更倾向于...", "option_b": "按计划行事", "preference_a": "J"},
        {"id": 56, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "做决定并执行", "preference_a": "J"},
        {"id": 57, "dimension": "JP", "option_a": "你更愿意...", "option_b": "提前规划", "preference_a": "J"},
        {"id": 58, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "整洁有序", "preference_a": "J"},
        {"id": 59, "dimension": "JP", "option_a": "你更倾向于...", "option_b": "完成目标", "preference_a": "J"},
        {"id": 60, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "有组织", "preference_a": "J"},
        {"id": 61, "dimension": "JP", "option_a": "你更愿意...", "option_b": "按时完成任务", "preference_a": "J"},
        {"id": 62, "dimension": "JP", "option_a": "你更重视...", "option_b": "计划和安排", "preference_a": "J"},
        {"id": 63, "dimension": "JP", "option_a": "你更倾向于...", "option_b": "遵守截止日期", "preference_a": "J"},
        {"id": 64, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "灵活随性", "preference_a": "P"},
        {"id": 65, "dimension": "JP", "option_a": "你更倾向于...", "option_b": "随机应变", "preference_a": "P"},
        {"id": 66, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "保持开放", "preference_a": "P"},
        {"id": 67, "dimension": "JP", "option_a": "你更愿意...", "option_b": "等待发现", "preference_a": "P"},
        {"id": 68, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "自发行动", "preference_a": "P"},
        {"id": 69, "dimension": "JP", "option_a": "你更倾向于...", "option_b": "适应变化", "preference_a": "P"},
        {"id": 70, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "临时决策", "preference_a": "P"},
    ],
}

# Add more questions for version 93 (extend with 23 more questions)
QUESTIONS[93] = QUESTIONS[70].copy() + [
    {"id": 71, "dimension": "EI", "option_a": "在大型活动中，你通常是...", "option_b": "主动结识新朋友", "preference_a": "E"},
    {"id": 72, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "被人关注", "preference_a": "E"},
    {"id": 73, "dimension": "SN", "option_a": "你更相信...", "option_b": "已证明的方法", "preference_a": "S"},
    {"id": 74, "dimension": "SN", "option_a": "你更倾向于...", "option_b": "关注实际结果", "preference_a": "S"},
    {"id": 75, "dimension": "TF", "option_a": "你做决定时...", "option_b": "先分析利弊", "preference_a": "T"},
    {"id": 76, "dimension": "TF", "option_a": "你更倾向于...", "option_b": "保持客观", "preference_a": "T"},
    {"id": 77, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "按清单办事", "preference_a": "J"},
    {"id": 78, "dimension": "JP", "option_a": "你更倾向于...", "option_b": "事先准备", "preference_a": "J"},
    {"id": 79, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "即兴发挥", "preference_a": "E"},
    {"id": 80, "dimension": "SN", "option_a": "你更关注...", "option_b": "具体例子", "preference_a": "S"},
    {"id": 81, "dimension": "TF", "option_a": "你更重视...", "option_b": "效率和逻辑", "preference_a": "T"},
    {"id": 82, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "有明确截止", "preference_a": "J"},
    {"id": 83, "dimension": "EI", "option_a": "在团队中，你...", "option_b": "分享想法", "preference_a": "E"},
    {"id": 84, "dimension": "SN", "option_a": "你更相信...", "option_b": "事实和数据", "preference_a": "S"},
    {"id": 85, "dimension": "TF", "option_a": "你认为...更重要", "option_b": "公平而非怜悯", "preference_a": "T"},
    {"id": 86, "dimension": "JP", "option_a": "你喜欢...", "option_b": "确定计划", "preference_a": "J"},
    {"id": 87, "dimension": "EI", "option_a": "你通过...获得灵感", "option_b": "与头脑风暴", "preference_a": "E"},
    {"id": 88, "dimension": "SN", "option_a": "你更喜欢...", "option_b": "一步一步来", "preference_a": "S"},
    {"id": 89, "dimension": "TF", "option_a": "你做决定时...", "option_b": "优先考虑原则", "preference_a": "T"},
    {"id": 90, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "有清晰目标", "preference_a": "J"},
    {"id": 91, "dimension": "SN", "option_a": "你更关注...", "option_b": "当下事实", "preference_a": "S"},
    {"id": 92, "dimension": "TF", "option_a": "你认为...更重要", "option_b": "诚信而非圆滑", "preference_a": "T"},
    {"id": 93, "dimension": "JP", "option_a": "你喜欢...", "option_b": "有期限的压力", "preference_a": "J"},
]

# Add more questions for version 144 (extend with 51 more questions)
QUESTIONS[144] = QUESTIONS[93].copy() + [
    {"id": 94, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "在人群中发言", "preference_a": "E"},
    {"id": 95, "dimension": "SN", "option_a": "你更相信...", "option_b": "亲眼所见", "preference_a": "S"},
    {"id": 96, "dimension": "TF", "option_a": "你做决定时...", "option_b": "考虑对人的影响", "preference_a": "F"},
    {"id": 97, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "做决定后执行", "preference_a": "J"},
    {"id": 98, "dimension": "EI", "option_a": "社交让你...", "option_b": "思维活跃", "preference_a": "E"},
    {"id": 99, "dimension": "SN", "option_a": "你更关注...", "option_b": "具体细节", "preference_a": "S"},
    {"id": 100, "dimension": "TF", "option_a": "你更重视...", "option_b": "逻辑思考", "preference_a": "T"},
    {"id": 101, "dimension": "JP", "option_a": "你喜欢...", "option_b": "井井有条", "preference_a": "J"},
    {"id": 102, "dimension": "EI", "option_a": "你倾向于...", "option_b": "表达自己", "preference_a": "E"},
    {"id": 103, "dimension": "SN", "option_a": "你更喜欢...", "option_b": "已验证的", "preference_a": "S"},
    {"id": 104, "dimension": "TF", "option_a": "你认为...更重要", "option_b": "公正", "preference_a": "T"},
    {"id": 105, "dimension": "JP", "option_a": "你更倾向于...", "option_b": "按计划", "preference_a": "J"},
    {"id": 106, "dimension": "EI", "option_a": "你喜欢...", "option_b": "带领讨论", "preference_a": "E"},
    {"id": 107, "dimension": "SN", "option_a": "你更关注...", "option_b": "现有信息", "preference_a": "S"},
    {"id": 108, "dimension": "TF", "option_a": "你做决定时...", "option_b": "依据客观分析", "preference_a": "T"},
    {"id": 109, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "有明确方向", "preference_a": "J"},
    {"id": 110, "dimension": "EI", "option_a": "你通过...获得能量", "option_b": "与他人互动", "preference_a": "E"},
    {"id": 111, "dimension": "SN", "option_a": "你更愿意...", "option_b": "相信事实", "preference_a": "S"},
    {"id": 112, "dimension": "TF", "option_a": "你更重视...", "option_b": "一致性和公平", "preference_a": "T"},
    {"id": 113, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "有组织的工作", "preference_a": "J"},
    {"id": 114, "dimension": "EI", "option_a": "你倾向于...", "option_b": "主导对话", "preference_a": "E"},
    {"id": 115, "dimension": "SN", "option_a": "你更关注...", "option_b": "具体事实", "preference_a": "S"},
    {"id": 116, "dimension": "TF", "option_a": "你做决定时...", "option_b": "优先考虑逻辑", "preference_a": "T"},
    {"id": 117, "dimension": "JP", "option_a": "你喜欢...", "option_b": "提前安排", "preference_a": "J"},
    {"id": 118, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "即兴演讲", "preference_a": "E"},
    {"id": 119, "dimension": "SN", "option_a": "你更相信...", "option_b": "实际经验", "preference_a": "S"},
    {"id": 120, "dimension": "TF", "option_a": "你更倾向于...", "option_b": "公平对待", "preference_a": "T"},
    {"id": 121, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "完成再庆祝", "preference_a": "J"},
    {"id": 122, "dimension": "EI", "option_a": "你倾向于...", "option_b": "公开发言", "preference_a": "E"},
    {"id": 123, "dimension": "SN", "option_a": "你更关注...", "option_b": "现实可行", "preference_a": "S"},
    {"id": 124, "dimension": "TF", "option_a": "你认为...更重要", "option_b": "原则", "preference_a": "T"},
    {"id": 125, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "遵守时间", "preference_a": "J"},
    {"id": 126, "dimension": "EI", "option_a": "社交场合中，你...", "option_b": "成为焦点", "preference_a": "E"},
    {"id": 127, "dimension": "SN", "option_a": "你更愿意...", "option_b": "用具体例子", "preference_a": "S"},
    {"id": 128, "dimension": "TF", "option_a": "你做决定时...", "option_b": "考虑客观因素", "preference_a": "T"},
    {"id": 129, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "按部就班", "preference_a": "J"},
    {"id": 130, "dimension": "EI", "option_a": "你喜欢...", "option_b": "主持活动", "preference_a": "E"},
    {"id": 131, "dimension": "SN", "option_a": "你更关注...", "option_b": "真实数据", "preference_a": "S"},
    {"id": 132, "dimension": "TF", "option_a": "你更重视...", "option_b": "理性判断", "preference_a": "T"},
    {"id": 133, "dimension": "JP", "option_a": "你倾向于...", "option_b": "提前规划", "preference_a": "J"},
    {"id": 134, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "多人讨论", "preference_a": "E"},
    {"id": 135, "dimension": "SN", "option_a": "你更相信...", "option_b": "已知事实", "preference_a": "S"},
    {"id": 136, "dimension": "TF", "option_a": "你认为...更重要", "option_b": "正确性", "preference_a": "T"},
    {"id": 137, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "完成任务", "preference_a": "J"},
    {"id": 138, "dimension": "EI", "option_a": "你通过...学习更多", "option_b": "讨论和交流", "preference_a": "E"},
    {"id": 139, "dimension": "SN", "option_a": "你更关注...", "option_b": "现有问题", "preference_a": "S"},
    {"id": 140, "dimension": "TF", "option_a": "你做决定时...", "option_b": "分析所有选项", "preference_a": "T"},
    {"id": 141, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "有期限的工作", "preference_a": "J"},
    {"id": 142, "dimension": "EI", "option_a": "你喜欢...", "option_b": "结识新朋友", "preference_a": "E"},
    {"id": 143, "dimension": "SN", "option_a": "你更愿意...", "option_b": "相信经验", "preference_a": "S"},
    {"id": 144, "dimension": "JP", "option_a": "你更倾向于...", "option_b": "有清晰目标", "preference_a": "J"},
]

# Add more questions for version 200 (extend with 56 more questions)
QUESTIONS[200] = QUESTIONS[144].copy() + [
    {"id": 145, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "公开演讲", "preference_a": "E"},
    {"id": 146, "dimension": "SN", "option_a": "你更关注...", "option_b": "实际问题", "preference_a": "S"},
    {"id": 147, "dimension": "TF", "option_a": "你更重视...", "option_b": "客观标准", "preference_a": "T"},
    {"id": 148, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "确定计划", "preference_a": "J"},
    {"id": 149, "dimension": "EI", "option_a": "社交让你感到...", "option_b": "兴奋和活力", "preference_a": "E"},
    {"id": 150, "dimension": "SN", "option_a": "你更相信...", "option_b": "具体证据", "preference_a": "S"},
    {"id": 151, "dimension": "TF", "option_a": "你认为...更能衡量成功", "option_b": "成果和效率", "preference_a": "T"},
    {"id": 152, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "提前准备", "preference_a": "J"},
    {"id": 153, "dimension": "EI", "option_a": "你倾向于...", "option_b": "主动社交", "preference_a": "E"},
    {"id": 154, "dimension": "SN", "option_a": "你更关注...", "option_b": "现实情况", "preference_a": "S"},
    {"id": 155, "dimension": "TF", "option_a": "你做决定时...", "option_b": "考虑因果关系", "preference_a": "T"},
    {"id": 156, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "有结构的方式", "preference_a": "J"},
    {"id": 157, "dimension": "EI", "option_a": "你喜欢...", "option_b": "在会议上发言", "preference_a": "E"},
    {"id": 158, "dimension": "SN", "option_a": "你更愿意...", "option_b": "解决具体问题", "preference_a": "S"},
    {"id": 159, "dimension": "TF", "option_a": "你更重视...", "option_b": "一致的标准", "preference_a": "T"},
    {"id": 160, "dimension": "JP", "option_a": "你倾向于...", "option_b": "遵守截止日期", "preference_a": "J"},
    {"id": 161, "dimension": "EI", "option_a": "你通过...获得能量", "option_b": "与朋友聚会", "preference_a": "E"},
    {"id": 162, "dimension": "SN", "option_a": "你更相信...", "option_b": "实际数据", "preference_a": "S"},
    {"id": 163, "dimension": "TF", "option_a": "你认为...更重要", "option_b": "公平的规则", "preference_a": "T"},
    {"id": 164, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "清单和待办", "preference_a": "J"},
    {"id": 165, "dimension": "EI", "option_a": "在聚会中，你...", "option_b": "主导话题", "preference_a": "E"},
    {"id": 166, "dimension": "SN", "option_a": "你更关注...", "option_b": "已知的方法", "preference_a": "S"},
    {"id": 167, "dimension": "TF", "option_a": "你做决定时...", "option_b": "基于事实", "preference_a": "T"},
    {"id": 168, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "按计划进行", "preference_a": "J"},
    {"id": 169, "dimension": "EI", "option_a": "你喜欢...", "option_b": "即兴交流", "preference_a": "E"},
    {"id": 170, "dimension": "SN", "option_a": "你更愿意...", "option_b": "相信经验", "preference_a": "S"},
    {"id": 171, "dimension": "TF", "option_a": "你更重视...", "option_b": "逻辑和证据", "preference_a": "T"},
    {"id": 172, "dimension": "JP", "option_a": "你倾向于...", "option_b": "提前安排", "preference_a": "J"},
    {"id": 173, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "小组头脑风暴", "preference_a": "E"},
    {"id": 174, "dimension": "SN", "option_a": "你更关注...", "option_b": "实际可行", "preference_a": "S"},
    {"id": 175, "dimension": "TF", "option_a": "你认为...更重要", "option_b": "原则和秩序", "preference_a": "T"},
    {"id": 176, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "完成目标", "preference_a": "J"},
    {"id": 177, "dimension": "EI", "option_a": "你倾向于...", "option_b": "发起活动", "preference_a": "E"},
    {"id": 178, "dimension": "SN", "option_a": "你更愿意...", "option_b": "用事实证明", "preference_a": "S"},
    {"id": 179, "dimension": "TF", "option_a": "你做决定时...", "option_b": "优先考虑逻辑", "preference_a": "T"},
    {"id": 180, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "有组织的工作", "preference_a": "J"},
    {"id": 181, "dimension": "EI", "option_a": "你喜欢...", "option_b": "在人群中表达", "preference_a": "E"},
    {"id": 182, "dimension": "SN", "option_a": "你更关注...", "option_b": "具体的细节", "preference_a": "S"},
    {"id": 183, "dimension": "TF", "option_a": "你更重视...", "option_b": "客观分析", "preference_a": "T"},
    {"id": 184, "dimension": "JP", "option_a": "你倾向于...", "option_b": "制定计划", "preference_a": "J"},
    {"id": 185, "dimension": "EI", "option_a": "你更喜欢...", "option_b": "即兴发挥", "preference_a": "E"},
    {"id": 186, "dimension": "SN", "option_a": "你更愿意...", "option_b": "相信已知", "preference_a": "S"},
    {"id": 187, "dimension": "TF", "option_a": "你做决定时...", "option_b": "考虑所有因素", "preference_a": "T"},
    {"id": 188, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "有清晰的目标", "preference_a": "J"},
    {"id": 189, "dimension": "EI", "option_a": "你喜欢...", "option_b": "主持讨论", "preference_a": "E"},
    {"id": 190, "dimension": "SN", "option_a": "你更关注...", "option_b": "现有数据", "preference_a": "S"},
    {"id": 191, "dimension": "TF", "option_a": "你更重视...", "option_b": "理性和公正", "preference_a": "T"},
    {"id": 192, "dimension": "JP", "option_a": "你倾向于...", "option_b": "遵守时间表", "preference_a": "J"},
    {"id": 193, "dimension": "EI", "option_a": "你通过...获得能量", "option_b": "社交活动", "preference_a": "E"},
    {"id": 194, "dimension": "SN", "option_a": "你更相信...", "option_b": "实际观察", "preference_a": "S"},
    {"id": 195, "dimension": "TF", "option_a": "你认为...更重要", "option_b": "效率和逻辑", "preference_a": "T"},
    {"id": 196, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "有结构的工作", "preference_a": "J"},
    {"id": 197, "dimension": "EI", "option_a": "你倾向于...", "option_b": "积极参与社交", "preference_a": "E"},
    {"id": 198, "dimension": "SN", "option_a": "你更关注...", "option_b": "当下的事实", "preference_a": "S"},
    {"id": 199, "dimension": "TF", "option_a": "你做决定时...", "option_b": "优先考虑客观因素", "preference_a": "T"},
    {"id": 200, "dimension": "JP", "option_a": "你更喜欢...", "option_b": "有组织有计划", "preference_a": "J"},
]

def get_questions(version: int = 70) -> list:
    """Get questions for specified version"""
    if version not in QUESTIONS:
        version = 70
    return QUESTIONS[version]

def get_question_count(version: int = 70) -> int:
    """Get question count for version"""
    return len(get_questions(version))
