#!/usr/bin/env python3
"""
Numbered Diagram Exporter - Creates PNG files for numbered draw.io diagrams
"""

import os
from PIL import Image, ImageDraw, ImageFont

class NumberedDiagramExporter:
    def __init__(self, diagrams_dir: str):
        self.diagrams_dir = diagrams_dir
        
    def create_numbered_pngs(self):
        """Create PNG files for all numbered draw.io diagrams"""
        numbered_drawio_files = [
            "01-system-context.drawio",
            "02-containers.drawio", 
            "03-components.drawio",
            "04-data-flow.drawio"
        ]
        
        for drawio_file in numbered_drawio_files:
            if os.path.exists(os.path.join(self.diagrams_dir, drawio_file)):
                png_file = drawio_file.replace('.drawio', '.png')
                self._create_placeholder_png(png_file, drawio_file)
                print(f"✅ Created {png_file}")
                
    def _create_placeholder_png(self, png_file: str, title: str):
        """Create a professional placeholder PNG with proper numbering and layout info"""
        # Create image with professional layout
        img = Image.new('RGB', (800, 600), color='white')
        draw = ImageDraw.Draw(img)
        
        # Draw border
        draw.rectangle([0, 0, 799, 599], outline='black', width=2)
        
        # Add title with numbering
        try:
            font_large = ImageFont.truetype("DejaVuSans-Bold.ttf", 24)
            font_medium = ImageFont.truetype("DejaVuSans.ttf", 16)
            font_small = ImageFont.truetype("DejaVuSans.ttf", 12)
        except:
            # Fallback to default fonts
            font_large = ImageFont.load_default()
            font_medium = ImageFont.load_default()
            font_small = ImageFont.load_default()
            
        # Title
        draw.text((50, 50), f"Professional Architecture Diagram", fill='black', font=font_large)
        draw.text((50, 90), f"{title.replace('.drawio', '')}", fill='blue', font=font_medium)
        
        # Layer information based on diagram type
        diagram_type = title.split('-')[1].replace('.drawio', '') if '-' in title else 'unknown'
        
        layer_info = {
            'system-context': [
                "Layer 01: External Users",
                "Layer 02: System Boundary", 
                "Layer 03: External Systems"
            ],
            'containers': [
                "Layer 01: Infrastructure (File System, Network, Security)",
                "Layer 02: Platform (Memory, Tools, Skills Framework)",
                "Layer 03: Application (Core Engine, API, Executor)", 
                "Layer 04: Interface (User Interaction, External APIs)"
            ],
            'components': [
                "Layer 01: Presentation (Input Parser, Response Generator)",
                "Layer 02: Business Logic (Intent Matcher, Skill Router)",
                "Layer 03: Data Access (Memory Manager, Context Storage)",
                "Layer 04: External Integration (Tool Integrator, API Client)"
            ],
            'data-flow': [
                "Stage 01: Input (User Request, Natural Language)",
                "Stage 02: Processing (Intent Recognition, Skill Routing)",
                "Stage 03: Storage (Context Management, Memory)",
                "Stage 04: Output (Response Generation, Result Delivery)"
            ]
        }
        
        y_pos = 140
        if diagram_type in layer_info:
            draw.text((50, y_pos), "Architecture Layers:", fill='black', font=font_medium)
            y_pos += 30
            for layer in layer_info[diagram_type]:
                draw.text((70, y_pos), f"• {layer}", fill='gray', font=font_small)
                y_pos += 25
        
        # Footer
        draw.text((50, y_pos + 20), "Generated by Technical Insight Skill", fill='gray', font=font_small)
        draw.text((50, y_pos + 40), "Edit in draw.io for professional customization", fill='blue', font=font_small)
        
        # Save PNG
        png_path = os.path.join(self.diagrams_dir, png_file)
        img.save(png_path)

if __name__ == "__main__":
    import sys
    if len(sys.argv) != 2:
        print("Usage: python numbered-diagram-exporter.py <diagrams_directory>")
        sys.exit(1)
        
    diagrams_dir = sys.argv[1]
    exporter = NumberedDiagramExporter(diagrams_dir)
    exporter.create_numbered_pngs()
    print("✅ All numbered PNG files created successfully!")