#!/bin/bash
# generate-report.sh — Generate MD and/or HTML reports from analysis JSON
# v4.0: Adapted for 10-dimension traffic-light model
# Usage:
#   generate-report.sh --input <analysis.json> --format md|html|all [--output-dir <dir>]
# Timeout: 10s | Compatible: macOS (darwin) + Linux
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATE="$SKILL_DIR/assets/report-template.html"

INPUT=""
FORMAT="md"
OUTPUT_DIR=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --input)  INPUT="$2"; shift 2 ;;
    --format) FORMAT="$2"; shift 2 ;;
    --output-dir) OUTPUT_DIR="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [[ -z "$INPUT" || ! -f "$INPUT" ]]; then
  echo "Usage: generate-report.sh --input <analysis.json> --format md|html|all [--output-dir <dir>]" >&2
  exit 1
fi

if [[ -z "$OUTPUT_DIR" ]]; then
  OUTPUT_DIR="$(dirname "$INPUT")"
fi
mkdir -p "$OUTPUT_DIR"

# --- Generate Markdown Report ---
generate_md() {
  node -e '
const fs = require("fs");
const analysis = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
const outDir = process.argv[2];

const statusIcon = { pass: "✅", warning: "⚠️", error: "❌" };
const dims = analysis.dimensions || [];
const summary = analysis.summary || {};

const lines = [];

// L0 — One-line status
const overallIcon = statusIcon[analysis.overall_status] || "❓";
lines.push(`# 🏥 OpenClaw Health Report v4.0`);
lines.push("");
lines.push(`> **${summary.pass_count || 0}✅ ${summary.warning_count || 0}⚠️ ${summary.error_count || 0}❌** — Status: **${analysis.overall_status}** ${overallIcon}`);
lines.push(`> Generated: ${analysis.timestamp}`);
lines.push("");

// L1 — Dimension grid
lines.push("## Dimension Status");
lines.push("");
const row1 = dims.slice(0, 5).map(d => `${d.label} ${statusIcon[d.status] || "❓"}`).join(" | ");
const row2 = dims.slice(5, 10).map(d => `${d.label} ${statusIcon[d.status] || "❓"}`).join(" | ");
lines.push("```");
lines.push(row1);
lines.push(row2);
lines.push("```");
lines.push("");

// Dimension detail table
lines.push("## All Dimensions");
lines.push("");
lines.push("| # | Status | Dimension | Message |");
lines.push("|---|--------|-----------|---------|");
for (const d of dims) {
  lines.push(`| ${d.id} | ${statusIcon[d.status]} | ${d.label} (${d.label_en}) | ${d.message} |`);
}
lines.push("");

// L2 — Issues (only ⚠️ and ❌)
const problemDims = dims.filter(d => d.status !== "pass");
if (problemDims.length > 0) {
  lines.push("## Issues");
  lines.push("");
  lines.push("| # | Status | Dimension | Issue | Fix Reference |");
  lines.push("|---|--------|-----------|-------|---------------|");
  let idx = 0;
  for (const d of problemDims) {
    for (const issue of (d.issues || []).filter(i => i.severity !== "info")) {
      idx++;
      const fixRef = issue.fix_ref ? "`" + issue.fix_ref + "`" : "—";
      lines.push(`| ${idx} | ${statusIcon[d.status]} | ${d.label} | ${issue.msg} | ${fixRef} |`);
    }
  }
  lines.push("");
  lines.push("> 💡 Run \\`clawhub doctor --fix\\` to auto-fix issues");
  lines.push("");
}

// All pass celebration
if (problemDims.length === 0) {
  lines.push("## ✅ All Clear!");
  lines.push("");
  lines.push("All 10 dimensions passed. Your OpenClaw installation is healthy.");
  lines.push("");
}

lines.push("---");
lines.push("*Generated by @botlearn/botlearn-healthcheck v4.0.0*");

const md = lines.join("\n");
const outPath = outDir + "/report.md";
fs.writeFileSync(outPath, md);
console.log(outPath);
' "$INPUT" "$OUTPUT_DIR"
}

# --- Generate HTML Report ---
generate_html() {
  node -e '
const fs = require("fs");
const analysis = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
const templatePath = process.argv[2];
const outDir = process.argv[3];

const statusIcon = { pass: "✅", warning: "⚠️", error: "❌" };
const statusColor = { pass: "#22c55e", warning: "#eab308", error: "#ef4444" };
const statusClass = { pass: "text-green", warning: "text-yellow", error: "text-red" };

let html = "";
// Try to use template, or generate standalone HTML
if (fs.existsSync(templatePath)) {
  html = fs.readFileSync(templatePath, "utf8");
}

const dims = analysis.dimensions || [];
const summary = analysis.summary || {};

// Build dimension grid HTML
const gridItems = dims.map(d => {
  const color = statusColor[d.status] || "#94a3b8";
  const icon = statusIcon[d.status] || "❓";
  return `<div class="dim-card" style="border-left:4px solid ${color}">
    <div class="dim-status">${icon}</div>
    <div class="dim-label">${d.label}</div>
    <div class="dim-msg" style="color:${color}">${d.message}</div>
  </div>`;
}).join("\n");

// Build issue rows
const problemDims = dims.filter(d => d.status !== "pass");
const issueRows = [];
let idx = 0;
for (const d of problemDims) {
  for (const issue of (d.issues || []).filter(i => i.severity !== "info")) {
    idx++;
    const color = statusColor[d.status] || "#94a3b8";
    issueRows.push(`<tr><td>${idx}</td><td style="color:${color}">${statusIcon[d.status]}</td><td>${d.label}</td><td>${issue.msg}</td><td>${issue.fix_ref || "—"}</td></tr>`);
  }
}

// Generate standalone HTML if template not available
const overallColor = statusColor[analysis.overall_status] || "#94a3b8";
const generatedHtml = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>🏥 OpenClaw Health Report</title>
  <style>
    :root { --bg: #0f172a; --fg: #e2e8f0; --card: #1e293b; --muted: #94a3b8; --green: #22c55e; --yellow: #eab308; --red: #ef4444; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: var(--bg); color: var(--fg); padding: 2rem; max-width: 1200px; margin: 0 auto; }
    h1 { font-size: 1.8rem; margin-bottom: 1rem; }
    .overall { text-align: center; padding: 2rem; background: var(--card); border-radius: 12px; margin-bottom: 2rem; }
    .overall-status { font-size: 3rem; font-weight: 700; color: ${overallColor}; }
    .overall-summary { font-size: 1.2rem; color: var(--muted); margin-top: 0.5rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
    .dim-card { background: var(--card); padding: 1rem; border-radius: 8px; }
    .dim-status { font-size: 1.5rem; }
    .dim-label { font-weight: 600; margin: 0.3rem 0; }
    .dim-msg { font-size: 0.85rem; }
    table { width: 100%; border-collapse: collapse; background: var(--card); border-radius: 8px; overflow: hidden; }
    th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid #334155; }
    th { background: #334155; font-weight: 600; }
    .text-green { color: var(--green); } .text-yellow { color: var(--yellow); } .text-red { color: var(--red); }
    .footer { text-align: center; color: var(--muted); margin-top: 2rem; font-size: 0.85rem; }
    @media print { body { background: white; color: black; } .dim-card, table, .overall { background: #f8fafc; } }
  </style>
</head>
<body>
  <h1>🏥 OpenClaw Health Report</h1>
  <div class="overall">
    <div class="overall-status">${statusIcon[analysis.overall_status]} ${analysis.overall_status?.toUpperCase()}</div>
    <div class="overall-summary">${summary.pass_count || 0}✅ ${summary.warning_count || 0}⚠️ ${summary.error_count || 0}❌ — ${analysis.timestamp || ""}</div>
  </div>
  <h2>Dimensions</h2>
  <div class="grid">${gridItems}</div>
  ${issueRows.length > 0 ? "<h2>Issues</h2><table><tr><th>#</th><th>Status</th><th>Dimension</th><th>Issue</th><th>Fix</th></tr>" + issueRows.join("") + "</table>" : "<h2>✅ All Clear!</h2><p>All 10 dimensions passed.</p>"}
  <div class="footer">Generated by @botlearn/botlearn-healthcheck v4.0.0</div>
</body>
</html>`;

const outPath = outDir + "/report.html";
fs.writeFileSync(outPath, generatedHtml);
console.log(outPath);
' "$INPUT" "$TEMPLATE" "$OUTPUT_DIR"
}

# --- Main ---
case "$FORMAT" in
  md)
    MD_PATH=$(generate_md)
    echo "{\"format\":\"md\",\"path\":\"$MD_PATH\"}"
    ;;
  html)
    HTML_PATH=$(generate_html)
    echo "{\"format\":\"html\",\"path\":\"$HTML_PATH\"}"
    ;;
  all)
    MD_PATH=$(generate_md)
    HTML_PATH=$(generate_html)
    echo "{\"format\":\"all\",\"md\":\"$MD_PATH\",\"html\":\"$HTML_PATH\"}"
    ;;
  *)
    echo "Unknown format: $FORMAT. Use md, html, or all." >&2
    exit 1
    ;;
esac
