#!/usr/bin/env python3
"""
Compile preprocess outputs into a relevance-filtered draft packet.

Expected input files: markdown files generated by preprocess subagents.
"""

import argparse
import json
import re
from pathlib import Path
from typing import Dict, List, Optional


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _match_first(text: str, patterns: List[str]) -> Optional[str]:
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE | re.MULTILINE)
        if match:
            return match.group(1).strip()
    return None


def parse_preprocess_markdown(path: Path) -> Dict:
    text = _read(path)

    score_text = _match_first(
        text,
        [
            r"Relevance\s*Score\s*:\s*(\d+)",
            r"Relevance\s*:\s*(\d+)",
        ],
    )
    score = int(score_text) if score_text and score_text.isdigit() else 0

    verdict = _match_first(
        text,
        [r"Relevance\s*Verdict\s*:\s*(relevant|irrelevant)"],
    )

    title = _match_first(text, [r"Title\s*:\s*(.+)"]) or path.stem
    filepath = _match_first(text, [r"Filepath\s*:\s*(.+)"]) or ""
    summary = _match_first(text, [r"Summary\s*:\s*(.+)"]) or ""

    key_points_block = _match_first(
        text,
        [r"Key\s*Points\s*:\s*\n([\s\S]*?)(?:\n\s*Evidence\s*:|\n\s*Quotes\s*:|\Z)"],
    ) or ""

    evidence_block = _match_first(
        text,
        [r"(?:Evidence|Quotes)\s*:\s*\n([\s\S]*?)\Z"],
    ) or ""

    key_points = [line.strip("- ").strip() for line in key_points_block.splitlines() if line.strip().startswith("-")]
    evidence = [line.strip("- ").strip() for line in evidence_block.splitlines() if line.strip().startswith("-")]

    is_relevant = score >= 6
    if verdict:
        is_relevant = verdict.lower() == "relevant"

    return {
        "source_file": str(path.resolve()),
        "title": title,
        "filepath": filepath,
        "relevance_score": score,
        "relevance_verdict": "relevant" if is_relevant else "irrelevant",
        "summary": summary,
        "key_points": key_points,
        "evidence": evidence,
        "raw": text,
    }


def compile_packet(seed_path: Path, preprocess_dir: Path, min_score: int) -> Dict:
    all_results = []

    for md_file in sorted(preprocess_dir.glob("*.md")):
        parsed = parse_preprocess_markdown(md_file)
        all_results.append(parsed)

    relevant = [
        item
        for item in all_results
        if item["relevance_verdict"] == "relevant" and item["relevance_score"] >= min_score
    ]

    references = []
    seen = set()
    for item in relevant:
        ref_title = item["title"].strip()
        ref_path = item["filepath"].strip() or item["source_file"]
        key = (ref_title, ref_path)
        if key in seen:
            continue
        seen.add(key)
        references.append({"title": ref_title, "filepath": ref_path})

    return {
        "seed_note": str(seed_path.resolve()),
        "preprocess_dir": str(preprocess_dir.resolve()),
        "min_score": min_score,
        "stats": {
            "total_preprocessed": len(all_results),
            "relevant_count": len(relevant),
            "filtered_out": len(all_results) - len(relevant),
        },
        "relevant_notes": relevant,
        "references": references,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", required=True, help="Seed note path")
    parser.add_argument("--preprocess-dir", required=True, help="Directory of preprocess markdown outputs")
    parser.add_argument("--output", required=True, help="Draft packet JSON output path")
    parser.add_argument("--min-score", type=int, default=6, help="Minimum relevance score to keep")
    args = parser.parse_args()

    seed_path = Path(args.seed).expanduser()
    preprocess_dir = Path(args.preprocess_dir).expanduser()
    output_path = Path(args.output).expanduser()

    if not seed_path.exists():
        raise SystemExit(f"Seed note not found: {seed_path}")
    if not preprocess_dir.exists():
        raise SystemExit(f"Preprocess directory not found: {preprocess_dir}")

    packet = compile_packet(seed_path, preprocess_dir, args.min_score)
    output_path.write_text(json.dumps(packet, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
