#!/usr/bin/env python3
"""
viSales CRM Reminder — ICS Generator
Generates .ics calendar files with structured CRM data in the description.
"""

import argparse
import re
import uuid
from datetime import datetime, timedelta
from pathlib import Path


def sanitize_filename(name: str) -> str:
    """Replace special chars and spaces with hyphens for filenames."""
    name = re.sub(r'[^\w\s-]', '', name)
    name = re.sub(r'[\s]+', '-', name.strip())
    return name


def escape_ics_text(text: str) -> str:
    """Escape text for ICS DESCRIPTION field (RFC 5545)."""
    text = text.replace('\\', '\\\\')
    text = text.replace(';', '\\;')
    text = text.replace(',', '\\,')
    text = text.replace('\n', '\\n')
    return text


def priority_display(prio: str) -> str:
    mapping = {
        'hoch': '⚡ HOCH',
        'mittel': '● MITTEL',
        'niedrig': '○ NIEDRIG',
    }
    return mapping.get(prio.lower(), f'● {prio.upper()}')


def priority_ics_value(prio: str) -> str:
    """Map to ICS PRIORITY (1=high, 5=medium, 9=low)."""
    mapping = {'hoch': '1', 'mittel': '5', 'niedrig': '9'}
    return mapping.get(prio.lower(), '5')


def build_description(args) -> str:
    """Build the structured CRM description block."""
    lines = []
    lines.append('═══ viSales CRM Reminder ═══')
    lines.append('')

    # Kunde section
    lines.append('📋 KUNDE')
    lines.append(f'Firma: {args.firma}')
    if args.ansprechpartner:
        lines.append(f'Ansprechpartner: {args.ansprechpartner}')
    if args.telefon:
        lines.append(f'Tel: {args.telefon}')
    if args.email:
        lines.append(f'Mail: {args.email}')
    lines.append('')

    # Anlass section
    if args.thema or args.prioritaet:
        lines.append('🎯 ANLASS')
        if args.thema:
            lines.append(f'Thema: {args.thema}')
        lines.append(f'Priorität: {priority_display(args.prioritaet)}')
        lines.append('')

    # Deal Status section
    has_deal_info = any([args.deal_phase, args.budget, args.letzte_interaktion])
    if has_deal_info:
        lines.append('📊 DEAL STATUS')
        if args.deal_phase:
            lines.append(f'Phase: {args.deal_phase}')
        if args.budget:
            lines.append(f'Budget: {args.budget}')
        if args.letzte_interaktion:
            lines.append(f'Letzte Interaktion: {args.letzte_interaktion}')
        lines.append('')

    # Nächster Schritt
    if args.naechster_schritt:
        lines.append('➡️ NÄCHSTER SCHRITT')
        lines.append(args.naechster_schritt)
        lines.append('')

    # Notizen
    if args.notizen:
        lines.append('📝 NOTIZEN')
        lines.append(args.notizen)
        lines.append('')

    lines.append('───')
    lines.append('Generated by viSales CRM Reminder')

    return '\n'.join(lines)


def build_summary(args) -> str:
    """Build the calendar event title/summary."""
    parts = [f'📞 {args.firma}']
    if args.ansprechpartner:
        parts.append(f'({args.ansprechpartner})')
    if args.thema:
        parts.append(f'— {args.thema}')
    return ' '.join(parts)


def generate_ics(args) -> str:
    """Generate a complete ICS file string."""
    # Parse date and time
    dt_start = datetime.strptime(f'{args.datum} {args.uhrzeit}', '%Y-%m-%d %H:%M')
    dt_end = dt_start + timedelta(minutes=args.dauer)

    # Format for ICS (local time, no timezone = floating time)
    fmt = '%Y%m%dT%H%M%S'
    dtstart = dt_start.strftime(fmt)
    dtend = dt_end.strftime(fmt)
    dtstamp = datetime.utcnow().strftime(fmt) + 'Z'

    uid = str(uuid.uuid4())
    summary = build_summary(args)
    description = build_description(args)

    # Build DESCRIPTION with proper line folding
    desc_escaped = escape_ics_text(description)

    ics_lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//viSales GmbH//CRM Reminder//DE',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        'BEGIN:VEVENT',
        f'UID:{uid}',
        f'DTSTAMP:{dtstamp}',
        f'DTSTART:{dtstart}',
        f'DTEND:{dtend}',
        f'SUMMARY:{escape_ics_text(summary)}',
        f'DESCRIPTION:{desc_escaped}',
        f'PRIORITY:{priority_ics_value(args.prioritaet)}',
        f'STATUS:CONFIRMED',
        f'TRANSP:OPAQUE',
    ]

    # Add alarm
    if args.alarm > 0:
        ics_lines.extend([
            'BEGIN:VALARM',
            'TRIGGER:-PT{}M'.format(args.alarm),
            'ACTION:DISPLAY',
            f'DESCRIPTION:Reminder: {args.firma} kontaktieren',
            'END:VALARM',
        ])

    # Add categories based on deal phase
    categories = ['viSales CRM']
    if args.deal_phase:
        categories.append(args.deal_phase)
    if args.prioritaet.lower() == 'hoch':
        categories.append('Priorität Hoch')
    ics_lines.append(f'CATEGORIES:{",".join(categories)}')

    ics_lines.extend([
        'END:VEVENT',
        'END:VCALENDAR',
    ])

    return '\r\n'.join(ics_lines)


def main():
    parser = argparse.ArgumentParser(description='viSales CRM Reminder ICS Generator')

    # Required fields
    parser.add_argument('--firma', required=True, help='Firmenname')
    parser.add_argument('--datum', required=True, help='Datum im Format YYYY-MM-DD')
    parser.add_argument('--uhrzeit', required=True, help='Uhrzeit im Format HH:MM')

    # Optional CRM fields
    parser.add_argument('--ansprechpartner', default='', help='Ansprechpartner')
    parser.add_argument('--telefon', default='', help='Telefonnummer')
    parser.add_argument('--email', default='', help='E-Mail-Adresse')
    parser.add_argument('--thema', default='', help='Thema / Anlass')
    parser.add_argument('--prioritaet', default='mittel', help='hoch / mittel / niedrig')
    parser.add_argument('--letzte-interaktion', dest='letzte_interaktion', default='', help='Letzte Interaktion')
    parser.add_argument('--deal-phase', dest='deal_phase', default='', help='Deal-Phase')
    parser.add_argument('--budget', default='', help='Budget')
    parser.add_argument('--naechster-schritt', dest='naechster_schritt', default='', help='Nächster Schritt')
    parser.add_argument('--notizen', default='', help='Notizen')
    parser.add_argument('--dauer', type=int, default=30, help='Dauer in Minuten (Default: 30)')
    parser.add_argument('--alarm', type=int, default=15, help='Alarm in Minuten vorher (Default: 15)')

    # Output
    parser.add_argument('--output', required=True, help='Output-Pfad für die ICS-Datei')

    args = parser.parse_args()

    # Generate ICS content
    ics_content = generate_ics(args)

    # Determine output filename if only directory given
    output_path = Path(args.output)
    if output_path.is_dir():
        filename = f'{args.datum}_{sanitize_filename(args.firma)}_Reminder.ics'
        output_path = output_path / filename
    elif not output_path.suffix:
        filename = f'{args.datum}_{sanitize_filename(args.firma)}_Reminder.ics'
        output_path = output_path / filename

    # Write file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(ics_content, encoding='utf-8')

    print(f'✅ ICS-Datei erstellt: {output_path}')
    print(f'   Firma: {args.firma}')
    print(f'   Datum: {args.datum} {args.uhrzeit}')
    if args.thema:
        print(f'   Thema: {args.thema}')
    print(f'   Datei: {output_path.name}')


if __name__ == '__main__':
    main()
