#!/usr/bin/env python3
"""
build_digest.py — Format a list of articles (JSON stdin) into a markdown digest.

Reads JSON array of article objects from stdin (output of fetch_feeds.py) and
writes a formatted markdown digest to stdout or a file.

Usage:
    python3 fetch_feeds.py ... | python3 build_digest.py [options]

Options:
    --title STR       Digest title (default: "RSS Digest")
    --period STR      Period label, e.g. "Daily" or "Weekly" (default: "Daily")
    --output FILE     Write output to file instead of stdout
    --group-by STR    Group articles by: "feed", "category", or "none" (default: "feed")
    --max-summary N   Max characters of summary to include (default: 300, 0=omit)
    --date STR        Override date label (default: today in YYYY-MM-DD)
"""

import sys
import json
import argparse
from datetime import datetime, timezone
from collections import defaultdict


def format_date(iso_str: str) -> str:
    """Format ISO 8601 date string to a human-readable date."""
    if not iso_str:
        return "Unknown date"
    try:
        dt = datetime.fromisoformat(iso_str)
        return dt.strftime("%b %d, %Y %H:%M UTC")
    except ValueError:
        return iso_str


def truncate(text: str, max_chars: int) -> str:
    if not text or max_chars == 0:
        return ""
    if len(text) <= max_chars:
        return text
    return text[:max_chars].rsplit(" ", 1)[0] + "…"


def build_article_block(art: dict, max_summary: int) -> str:
    lines = []
    title = art.get("title") or "Untitled"
    url = art.get("url", "")
    pub = format_date(art.get("published", ""))
    summary = truncate(art.get("summary", ""), max_summary)

    if url:
        lines.append(f"- **[{title}]({url})**")
    else:
        lines.append(f"- **{title}**")

    lines.append(f"  *{pub}*")

    if summary:
        lines.append(f"  {summary}")

    return "\n".join(lines)


def build_digest(
    articles: list[dict],
    title: str,
    period: str,
    date_label: str,
    group_by: str,
    max_summary: int,
) -> str:
    lines = []

    # Header
    lines.append(f"# {period} {title}")
    lines.append(f"**{date_label}** · {len(articles)} article(s)")
    lines.append("")

    if not articles:
        lines.append("_No articles found for this period._")
        return "\n".join(lines)

    if group_by == "none":
        lines.append("## Articles")
        lines.append("")
        for art in articles:
            lines.append(build_article_block(art, max_summary))
            lines.append("")
    else:
        # Group articles
        groups: dict[str, list[dict]] = defaultdict(list)
        for art in articles:
            if group_by == "category":
                key = art.get("category") or art.get("feed_title") or "Uncategorized"
            else:  # "feed"
                key = art.get("feed_title") or art.get("feed_url") or "Unknown Feed"
            groups[key].append(art)

        # Sort groups by article count descending
        for group_name in sorted(groups.keys()):
            group_articles = groups[group_name]
            lines.append(f"## {group_name} ({len(group_articles)})")
            lines.append("")
            for art in group_articles:
                lines.append(build_article_block(art, max_summary))
                lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by rss-digest · {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Build a markdown RSS digest from article JSON.")
    parser.add_argument("--title", default="RSS Digest", help="Digest title")
    parser.add_argument("--period", default="Daily", help="Period label (Daily/Weekly)")
    parser.add_argument("--output", default="", help="Output file path (default: stdout)")
    parser.add_argument("--group-by", default="feed", choices=["feed", "category", "none"],
                        help="Group articles by feed, category, or none (default: feed)")
    parser.add_argument("--max-summary", type=int, default=300,
                        help="Max summary chars (0=omit, default: 300)")
    parser.add_argument("--date", default="", help="Override date label")
    args = parser.parse_args()

    # Read articles from stdin
    try:
        articles = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        print(f"[build_digest] JSON decode error: {e}", file=sys.stderr)
        sys.exit(1)

    if not isinstance(articles, list):
        print("[build_digest] Expected a JSON array.", file=sys.stderr)
        sys.exit(1)

    date_label = args.date or datetime.now(timezone.utc).strftime("%A, %B %d %Y")

    digest = build_digest(
        articles=articles,
        title=args.title,
        period=args.period,
        date_label=date_label,
        group_by=args.group_by,
        max_summary=args.max_summary,
    )

    if args.output:
        try:
            with open(args.output, "w") as f:
                f.write(digest)
            print(f"[build_digest] Wrote digest to {args.output} ({len(articles)} articles)", file=sys.stderr)
        except OSError as e:
            print(f"[build_digest] Error writing file: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print(digest)
        print(f"[build_digest] Done. {len(articles)} article(s).", file=sys.stderr)


if __name__ == "__main__":
    main()
