#!/bin/bash
# summarize.sh — Structured summary from text input (stdin or argument)
# Produces structured output + AI enhancement prompt

OUTPUT_DIR="${OUTPUT_DIR:-/tmp/summaries}"
mkdir -p "$OUTPUT_DIR"

# Read from argument or stdin
if [[ $# -ge 1 ]] && [[ "$1" != "-" ]]; then
  TEXT="$*"
elif [[ "$1" == "-" ]]; then
  TEXT=$(cat)
else
  echo "Usage: $0 \"Your text here...\""
  echo "   or: echo \"text\" | $0"
  echo "   or: cat file.txt | $0"
  exit 1
fi

if [[ ${#TEXT} -lt 50 ]]; then
  echo "ERROR: Text too short (minimum 50 characters)"
  exit 1
fi

TIMESTAMP=$(date +%s)
OUTPUT_FILE="${OUTPUT_DIR}/summary-text-${TIMESTAMP}.md"

WORD_COUNT=$(echo "$TEXT" | wc -w)
READ_TIME=$((WORD_COUNT / 200))

# Extract key sentences
KEY_SENTENCES=$(python3 - "$TEXT" << 'PYEOF'
import sys, re
text = sys.stdin.read()
sentences = re.split(r'(?<=[.!?])\s+', text.strip())
meaningful = [s.strip() for s in sentences if 4 <= len(s.split()) < 60]
print('\n'.join(meaningful[:15]))
PYEOF
)

cat > "$OUTPUT_FILE" << EOF
# Text Summary

**Stats:** ~${WORD_COUNT} words | ~${READ_TIME} min read

---

## Key Sentences (Extractive)

$KEY_SENTENCES

---

## Structured Summary Template

**What is this about?**
[TODO: 1-2 sentence description of main topic]

**Main arguments / findings:**
[TODO: 2-3 key points]

**Why it matters:**
[TODO: Significance or implications]

---

## Tweet Hook

> [TODO: One compelling sentence, 280 chars max]

---

## Key Takeaways

1. [TODO: First key point]
2. [TODO: Second key point]
3. [TODO: Third key point]

---

## AI Enhancement Prompt

\`\`\`
Summarize the following text in a structured format:

Text:
$TEXT

Please provide:
1. A 2-3 paragraph summary (what, why, so what)
2. A tweet-length hook (280 chars or less)
3. Three key takeaways as bullet points
4. The single most surprising or valuable insight

Write as if for a smart reader who didn't see the original.
\`\`\`

---

*Generated by content-summarizer skill | $(date '+%Y-%m-%d %H:%M UTC')*
EOF

echo "✅ Summary saved to: $OUTPUT_FILE"
echo ""
cat "$OUTPUT_FILE"
