#!/bin/bash
# url-to-summary.sh — Fetch URL, extract clean text, produce structured summary
# Uses extractive summarization + AI enhancement prompts

URL="${1:-}"
OUTPUT_DIR="${OUTPUT_DIR:-/tmp/summaries}"
MODEL="${MODEL:-minimax}"

if [[ -z "$URL" ]]; then
  echo "Usage: $0 <url>"
  echo "Example: $0 https://example.com/article"
  exit 1
fi

mkdir -p "$OUTPUT_DIR"
TIMESTAMP=$(date +%s)
TMP_CONTENT=$(mktemp)
TMP_CLEAN=$(mktemp)
TMP_SENTENCES=$(mktemp)
trap "rm -f $TMP_CONTENT $TMP_CLEAN $TMP_SENTENCES" EXIT

echo "Fetching: $URL" >&2

curl -sL --max-time 30 -A "Mozilla/5.0 (compatible; ContentSummarizer/1.0)" "$URL" > "$TMP_CONTENT" 2>/dev/null

if [[ ! -s "$TMP_CONTENT" ]] || [[ $(wc -c < "$TMP_CONTENT") -lt 200 ]]; then
  echo "ERROR: Failed to fetch content or content too short"
  exit 1
fi

# Extract clean text → TMP_CLEAN
python3 << PYEOF
import re, html as html_mod
with open("$TMP_CONTENT", 'r', errors='ignore') as f:
    content = f.read()
content = re.sub(r'<script[^>]*>.*?</script>', '', content, flags=re.DOTALL|re.IGNORECASE)
content = re.sub(r'<style[^>]*>.*?</style>', '', content, flags=re.DOTALL|re.IGNORECASE)
content = re.sub(r'<nav[^>]*>.*?</nav>', '', content, flags=re.DOTALL|re.IGNORECASE)
content = re.sub(r'<footer[^>]*>.*?</footer>', '', content, flags=re.DOTALL|re.IGNORECASE)
content = re.sub(r'<header[^>]*>.*?</header>', '', content, flags=re.DOTALL|re.IGNORECASE)
content = re.sub(r'<aside[^>]*>.*?</aside>', '', content, flags=re.DOTALL|re.IGNORECASE)
content = re.sub(r'<[^>]+>', ' ', content)
content = html_mod.unescape(content)
content = re.sub(r'\s+', ' ', content).strip()
content = re.sub(r' {2,}', ' ', content)
with open("$TMP_CLEAN", 'w') as f:
    f.write(content[:15000])
PYEOF

CLEAN_TEXT=$(cat "$TMP_CLEAN")

if [[ ${#CLEAN_TEXT} -lt 100 ]]; then
  echo "ERROR: Failed to extract text content"
  exit 1
fi

WORD_COUNT=$(echo "$CLEAN_TEXT" | wc -w)
READ_TIME=$((WORD_COUNT / 200))
TITLE=$(grep -oE '<title>[^<]+</title>' "$TMP_CONTENT" 2>/dev/null | head -1 | sed 's/<[^>]*>//g' || echo "Unknown")

# Extract key sentences → TMP_SENTENCES
python3 << PYEOF
import re
with open("$TMP_CLEAN", 'r') as f:
    text = f.read()
sentences = re.split(r'(?<=[.!?])\s+', text.strip())
meaningful = [s.strip() for s in sentences if 4 <= len(s.split()) < 60 and not s.startswith('http')]
with open("$TMP_SENTENCES", 'w') as f:
    f.write('\n'.join(meaningful[:20]))
PYEOF

KEY_SENTENCES=$(cat "$TMP_SENTENCES")

OUTPUT_FILE="${OUTPUT_DIR}/summary-${TIMESTAMP}.md"

cat > "$OUTPUT_FILE" << EOF
# Content Summary

**Source:** $URL

**Title:** $TITLE

**Stats:** ~${WORD_COUNT} words | ~${READ_TIME} min read

---

## Key Sentences (Extractive Summary)

$KEY_SENTENCES

---

## Structured Summary Template

**What is this about?**
[TODO: Fill in with 1-2 sentence description of the main topic]

**Main arguments or findings:**
[TODO: List 2-3 key points]

**Why it matters:**
[TODO: Explain the significance or implications]

---

## Tweet Hook

> [TODO: One compelling sentence, 280 chars max]

---

## Key Takeaways

1. [TODO: First key point]
2. [TODO: Second key point]
3. [TODO: Third key point]

---

## AI Enhancement Prompt

Copy the extracted text below and use this prompt with your AI agent:

---
Summarize the following article in a structured format:

Title: $TITLE
Word count: ~${WORD_COUNT} words
Source: $URL

Article text:
$CLEAN_TEXT

Please provide:
1. A 2-3 paragraph summary (what, why, so what)
2. A tweet-length hook (280 chars or less)
3. Three key takeaways as bullet points
4. The single most surprising or valuable insight

Write as if for a smart reader who didn't see the original.
---

*Generated by content-summarizer skill | $(date '+%Y-%m-%d %H:%M UTC')*
EOF

echo ""
echo "✅ Summary saved to: $OUTPUT_FILE"
echo ""
head -30 "$OUTPUT_FILE"
echo ""
echo "... [truncated] ..."
echo ""
echo "Full file: $OUTPUT_FILE"
