#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const QRCode = require('qrcode');

function arg(name, fallback = null) {
  const i = process.argv.indexOf(`--${name}`);
  if (i === -1) return fallback;
  return process.argv[i + 1] ?? fallback;
}

function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

const slug = arg('slug');
if (!slug || !/^[a-z0-9][a-z0-9-]{1,63}$/.test(slug)) {
  console.error('Usage: node scripts/generate_qr_card.js --slug <skill-slug> [--title <title>] [--mode install|clawhub|github] [--github <owner/repo>] [--out <file.svg>]');
  process.exit(1);
}

const title = arg('title', slug.replace(/-/g, ' ').replace(/\b\w/g, s => s.toUpperCase()));
const mode = arg('mode', 'install');
const github = arg('github');
const ts = new Date().toISOString().replace(/[:T]/g, '-').slice(0, 16);
const out = arg('out', `./images/${ts}-${slug}-qr-card.svg`);

let payload = `clawhub install ${slug}`;
if (mode === 'clawhub') payload = `https://clawhub.ai/${slug}`;
if (mode === 'github') {
  if (!github) {
    console.error('--github <owner/repo> is required for --mode github');
    process.exit(1);
  }
  payload = `https://github.com/${github}`;
}

fs.mkdirSync(path.dirname(out), { recursive: true });

(async () => {
  const qrSvgRaw = await QRCode.toString(payload, {
    type: 'svg',
    errorCorrectionLevel: 'M',
    margin: 0,
    width: 360,
    color: { dark: '#111827', light: '#ffffff' },
  });

  const qrBody = qrSvgRaw
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '');

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="960" height="600" viewBox="0 0 960 600" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#0f172a"/>
      <stop offset="100%" stop-color="#1e293b"/>
    </linearGradient>
    <linearGradient id="accent" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="#22d3ee"/>
      <stop offset="100%" stop-color="#818cf8"/>
    </linearGradient>
  </defs>

  <rect x="0" y="0" width="960" height="600" fill="url(#bg)"/>
  <rect x="60" y="60" width="840" height="480" rx="28" fill="#0b1220" stroke="#334155"/>
  <rect x="60" y="60" width="840" height="10" rx="28" fill="url(#accent)"/>

  <text x="110" y="140" fill="#e2e8f0" font-family="Inter, system-ui, sans-serif" font-size="46" font-weight="700">${escapeXml(title)}</text>
  <text x="110" y="180" fill="#94a3b8" font-family="Inter, system-ui, sans-serif" font-size="24">Scan to install this skill</text>

  <rect x="520" y="120" width="320" height="320" rx="16" fill="#ffffff"/>
  <g transform="translate(540,140)">${qrBody}</g>

  <text x="110" y="260" fill="#cbd5e1" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="22">Slug: ${escapeXml(slug)}</text>
  <text x="110" y="305" fill="#cbd5e1" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="22">Mode: ${escapeXml(mode)}</text>

  <rect x="110" y="360" width="360" height="56" rx="12" fill="#111827" stroke="#334155"/>
  <text x="130" y="395" fill="#22d3ee" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="20">${escapeXml(payload)}</text>

  <text x="110" y="500" fill="#64748b" font-family="Inter, system-ui, sans-serif" font-size="18">Generated by skill-qr-card</text>
</svg>`;

  fs.writeFileSync(out, svg, 'utf8');
  console.log(`Wrote: ${out}`);
  console.log(`MEDIA:${out.startsWith('./') ? out : './' + path.relative(process.cwd(), out)}`);

  if (!hasFlag('no-png')) {
    const pngOut = out.replace(/\.svg$/i, '.png');
    try {
      execSync(`convert -background none "${out}" "${pngOut}"`, { stdio: 'ignore' });
      console.log(`Wrote: ${pngOut}`);
      console.log(`MEDIA:${pngOut.startsWith('./') ? pngOut : './' + path.relative(process.cwd(), pngOut)}`);
    } catch {
      // optional
    }
  }
})();

function escapeXml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
