"""City name → che168 URL pinyin slug mapping.

che168.com uses full pinyin city names in URLs: /beijing/list/, /shanghai/list/.
National (全国) uses /china/list/.
"""

CHE168_CITY_SLUG: dict[str, str] = {
    "全国": "china",
    "北京": "beijing",
    "上海": "shanghai",
    "广州": "guangzhou",
    "深圳": "shenzhen",
    "成都": "chengdu",
    "杭州": "hangzhou",
    "重庆": "chongqing",
    "武汉": "wuhan",
    "苏州": "suzhou",
    "南京": "nanjing",
    "天津": "tianjin",
    "西安": "xian",
    "长沙": "changsha",
    "郑州": "zhengzhou",
    "东莞": "dongguan",
    "青岛": "qingdao",
    "合肥": "hefei",
    "佛山": "foshan",
    "宁波": "ningbo",
    "昆明": "kunming",
    "沈阳": "shenyang",
    "大连": "dalian",
    "厦门": "xiamen",
    "济南": "jinan",
    "无锡": "wuxi",
    "福州": "fuzhou",
    "哈尔滨": "haerbin",
    "石家庄": "shijiazhuang",
    "烟台": "yantai",
    "珠海": "zhuhai",
    "惠州": "huizhou",
    "中山": "zhongshan",
    "太原": "taiyuan",
    "南昌": "nanchang",
    "贵阳": "guiyang",
    "南宁": "nanning",
    "温州": "wenzhou",
    "常州": "changzhou",
    "徐州": "xuzhou",
    "兰州": "lanzhou",
    "长春": "changchun",
    "呼和浩特": "huhehaote",
    "乌鲁木齐": "wulumuqi",
    "拉萨": "lasa",
    "银川": "yinchuan",
    "西宁": "xining",
    "海口": "haikou",
    "三亚": "sanya",
    "保定": "baoding",
    "唐山": "tangshan",
    "洛阳": "luoyang",
    "潍坊": "weifang",
    "临沂": "linyi",
    "淄博": "zibo",
    "绍兴": "shaoxing",
    "嘉兴": "jiaxing",
    "泉州": "quanzhou",
    "漳州": "zhangzhou",
    "南通": "nantong",
    "扬州": "yangzhou",
    "芜湖": "wuhu",
    "泰州": "taizhou",
    "盐城": "yancheng",
    "镇江": "zhenjiang",
    "金华": "jinhua",
    "台州": "taizhoutj",
    "廊坊": "langfang",
    "邯郸": "handan",
    "沧州": "cangzhou",
    "株洲": "zhuzhou",
    "湘潭": "xiangtan",
    "柳州": "liuzhou",
    "桂林": "guilin",
    "赣州": "ganzhou",
    "九江": "jiujiang",
    "襄阳": "xiangyang",
    "宜昌": "yichang",
    "岳阳": "yueyang",
    "汕头": "shantou",
    "湛江": "zhanjiang",
    "江门": "jiangmen",
    "肇庆": "zhaoqing",
    "茂名": "maoming",
    "绵阳": "mianyang",
    "德阳": "deyang",
    "宜宾": "yibin",
    "南充": "nanchong",
    "乐山": "leshan",
    "遵义": "zunyi",
    "大庆": "daqing",
    "吉林": "jilinshi",
    "包头": "baotou",
}


def get_city_slug(city: str) -> str:
    """Get che168 URL slug for a city. Returns 'china' for unknown/全国."""
    return CHE168_CITY_SLUG.get(city, "china")
