#!/usr/bin/env python3
"""
Data Visualization Script

Usage:
    python data_visualization.py --query "QUERY" --file data.xlsx
    python data_visualization.py --query "QUERY" --json '[{"col1": 1, "col2": 2}]' --output chart.html

Environment Variables:
    CHARTGEN_API_KEY: API key

Output:
    - Returns ECharts configuration JSON
    - Optionally generates HTML file for browser viewing
"""
import argparse
import sys
import os
import json
import re
from datetime import datetime

# Add script directory to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from chartgen_api import ChartGenAPI


# ECharts HTML template
ECHARTS_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <script src="https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ 
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: #f5f5f5;
            padding: 20px;
        }}
        .chart-container {{
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }}
        .chart-title {{
            padding: 16px 20px;
            border-bottom: 1px solid #eee;
            font-size: 16px;
            font-weight: 600;
            color: #333;
        }}
        .chart-body {{
            width: 100%;
            height: 500px;
            padding: 10px;
        }}
        .footer {{
            text-align: center;
            color: #999;
            font-size: 12px;
            padding: 10px;
        }}
    </style>
</head>
<body>
{charts}
    <div class="footer">Generated by ChartGen at {timestamp}</div>
    <script>
{scripts}
    </script>
</body>
</html>
'''

CHART_ITEM_TEMPLATE = '''
    <div class="chart-container">
        <div class="chart-title">{title}</div>
        <div id="chart{i}" class="chart-body"></div>
    </div>
'''

CHART_SCRIPT_TEMPLATE = '''
        (function() {{
            var chart{i} = echarts.init(document.getElementById('chart{i}'));
            var option{i} = {option};
            chart{i}.setOption(option{i});
            window.addEventListener('resize', function() {{
                chart{i}.resize();
            }});
        }})();
'''


def parse_json_arg(json_arg: str) -> any:
    """
    Parse JSON argument (supports string or file path)
    
    Args:
        json_arg: JSON string or JSON file path
        
    Returns:
        Parsed Python object
    """
    if os.path.exists(json_arg):
        with open(json_arg, 'r', encoding='utf-8') as f:
            return json.load(f)
    else:
        return json.loads(json_arg)


def extract_echarts_options(text: str) -> list:
    """
    Extract ECharts configurations from returned text
    
    Args:
        text: Text returned by API (may contain markdown code blocks)
        
    Returns:
        List of ECharts configuration dicts
    """
    options = []
    
    # Try to extract from ```json or ```echarts code blocks
    pattern = r'```(?:json|echarts)?\s*(\{[\s\S]*?\})\s*```'
    matches = re.finditer(pattern, text)
    
    for match in matches:
        try:
            option = json.loads(match.group(1))
            options.append(option)
        except json.JSONDecodeError:
            continue
    
    # If no code blocks found, try to parse entire text directly
    if not options:
        try:
            # Try to find JSON object
            json_match = re.search(r'(\{[\s\S]*\})', text)
            if json_match:
                options.append(json.loads(json_match.group(1)))
        except json.JSONDecodeError:
            pass
    
    return options


def generate_html(options: list, title: str = "ChartGen Visualization") -> str:
    """
    Generate HTML containing ECharts
    
    Args:
        options: List of ECharts configurations
        title: Page title
        
    Returns:
        HTML string
    """
    charts_html = []
    scripts = []
    
    for i, option in enumerate(options):
        # Get chart title
        chart_title = option.get('title', {}).get('text', f'Chart {i+1}')
        
        charts_html.append(CHART_ITEM_TEMPLATE.format(
            title=chart_title,
            i=i
        ))
        
        scripts.append(CHART_SCRIPT_TEMPLATE.format(
            i=i,
            option=json.dumps(option, ensure_ascii=False, indent=12)
        ))
    
    return ECHARTS_TEMPLATE.format(
        title=title,
        charts='\n'.join(charts_html),
        scripts='\n'.join(scripts),
        timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    )


def main():
    parser = argparse.ArgumentParser(
        description='Data Visualization - Generate ECharts charts through natural language',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Generate chart from file
    python data_visualization.py --query "Draw a bar chart of sales" --file sales.xlsx
    
    # Generate chart and save HTML
    python data_visualization.py --query "Draw a line chart of trends" --file data.xlsx --output chart.html
    
    # Generate chart from JSON data
    python data_visualization.py --query "Draw a pie chart" --json '[{"name":"A","value":100},{"name":"B","value":200}]'
        """
    )
    parser.add_argument('--query', required=True, help='Visualization query statement')
    parser.add_argument('--file', help='Input file path (.xlsx/.xls/.csv)')
    parser.add_argument('--json', help='JSON data (string or file path)')
    parser.add_argument('--output', '-o', help='Output HTML file path (optional)')
    
    args = parser.parse_args()
    
    # Parameter validation
    if not args.file and not args.json:
        parser.error("Either --file or --json parameter must be provided")
    
    if args.file and args.json:
        print("Warning: Both --file and --json provided, will use --file", file=sys.stderr)
    
    try:
        api = ChartGenAPI()  # Read API Key from environment variable
        
        json_data = None
        if args.json and not args.file:
            json_data = parse_json_arg(args.json)
        
        # Call API
        result = api.visualize(
            query=args.query,
            file_path=args.file,
            json_data=json_data
        )
        
        # Output raw result (ECharts JSON)
        print(result)
        
        # Extract ECharts configuration
        options = extract_echarts_options(result)
        
        if options:
            # Determine output path
            output_path = args.output
            if not output_path:
                # Default save to /tmp/openclaw/charts/
                output_dir = "/tmp/openclaw/charts"
                os.makedirs(output_dir, exist_ok=True)
                timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
                output_path = os.path.join(output_dir, f"chart_{timestamp}.html")
            
            # Generate and save HTML
            html_content = generate_html(options)
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            
            print(f"\n---\nChart saved: {output_path}", file=sys.stderr)
        else:
            print("\nWarning: Could not extract ECharts configuration from result", file=sys.stderr)
        
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
