"""
botlearn/strategy-intel — Main Entry Point
Input: company_name
Output: structured strategic analysis (Where to Play / How to Win / What's the Risk)
"""

import sys
import json
import os
from apify_scraper import scrape_company

# ── Model call (OpenClaw will inject its model client)
# For standalone test: tries OpenAI first, then Claude, then raw prompt fallback
client = None
MODEL = None
_backend = None

if os.environ.get("OPENAI_API_KEY"):
    try:
        from openai import OpenAI
        client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
        MODEL = "gpt-4o"
        _backend = "openai"
    except ImportError:
        pass

if client is None and os.environ.get("ANTHROPIC_API_KEY"):
    try:
        import anthropic as _anthropic
        _claude = _anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
        MODEL = "claude-opus-4-6"
        _backend = "claude"
    except ImportError:
        pass


def _load_playbook() -> str:
    """Load Partner's Playbook from file if it exists."""
    playbook_path = os.path.join(os.path.dirname(__file__), "..", "partner_playbook.md")
    try:
        with open(os.path.abspath(playbook_path), "r") as f:
            return f.read()
    except FileNotFoundError:
        return ""

_playbook = _load_playbook()

SYSTEM_PROMPT = """
You are Partner, a senior strategy consultant with an MBA from Harvard Business School,
and 10 years of experience in corporate strategy at TikTok and top-tier global startups.

Your job is to analyze companies using the Where to Play / How to Win / What's the Risk framework.
You think like a McKinsey partner, but speak like a founder — clear, direct, no filler.

Rules:
- Never hedge with "it depends" without a concrete follow-up answer
- Always give a sharp point of view, not just a summary
- Solo founders don't have time for fluff — be precise
- End every analysis with ONE sentence: the single most important strategic implication

{playbook}
""".format(playbook=_playbook)

ANALYSIS_PROMPT = """
Based on the following raw data about {company_name}, produce a structured strategic analysis.
Apply your Partner's Playbook rigorously:
- For "Where to Play": use your Macro lens — is there a 10x incremental market? Where is the market going, not where it is?
- For "How to Win": use your Middle lens — what is the actual product-level edge? Apply Jobs to Be Done and Crossing the Chasm where relevant. Is this low-end disruption or something else?
- For "What's the Risk": use your Micro lenses — assess founder-market fit, and unit economics. Can they generate cash before they run out of it? How many funding rounds does survival require?
Be specific. Name the market. Name the customer. Name the vulnerability. No generic consulting language.

RAW DATA:
{raw_data}

Output EXACTLY in this format:

## Strategy Intel: {company_name}
Generated by botlearn/strategy-intel

### Macro — Industry & Market
> Where is the market going? Is there a 10x incremental opportunity?

[3-5 sentences — name the specific market, the tailwind, and whether this company is playing where the market is going or where it already is]

### Middle — Product & Customer
> What is the real product edge? What job is the customer hiring this for?

[3-5 sentences — apply Jobs to Be Done, assess whether the moat is real or just operational, Crossing the Chasm status]

### Micro — Team & Founders
> Does the founder have unique insight, or did they just spot an opportunity?

[2-3 sentences — assess founder-market fit and what their background predicts about the company's future bets]

### Micro — Economics & Cash
> Can they generate cash before they run out of it?

[2-3 sentences — unit economics, funding runway, path to cash flow positive]

### Strategic Implication
> [ONE sentence — the most important thing a competitor or investor should know]

---
Powered by BotLearn · botlearn.ai
"""


def analyze(company_name: str, depth: str = "quick") -> str:
    """Full pipeline: scrape → analyze → output"""
    
    print(f"[strategy-intel] Scraping data for: {company_name}")
    raw_data = scrape_company(company_name, depth)
    
    # Truncate to avoid token overflow
    raw_str = json.dumps(raw_data, ensure_ascii=False)[:6000]
    
    prompt = ANALYSIS_PROMPT.format(
        company_name=company_name,
        raw_data=raw_str
    )

    print(f"[strategy-intel] Running analysis...")
    
    if _backend == "openai":
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt}
            ],
            temperature=0.3,
            max_tokens=1000
        )
        return response.choices[0].message.content
    elif _backend == "claude":
        response = _claude.messages.create(
            model=MODEL,
            max_tokens=1000,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}]
        )
        return response.content[0].text
    else:
        # Fallback: return prompt for OpenClaw to handle
        return f"SYSTEM:\n{SYSTEM_PROMPT}\n\nUSER:\n{prompt}"


def main():
    if len(sys.argv) < 2:
        print("Usage: python run.py <company_name> [quick|deep]")
        sys.exit(1)
    
    company_name = sys.argv[1]
    depth = sys.argv[2] if len(sys.argv) > 2 else "quick"
    
    result = analyze(company_name, depth)
    print("\n" + result)


if __name__ == "__main__":
    main()
