#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOGS_FILE="$REPO_ROOT/logs/LOGS.md"
SKILL_IMPROVEMENTS_FILE="$REPO_ROOT/logs/SKILL_IMPROVEMENTS.md"

usage() {
    echo "Usage: $0 [--check-only]"
    echo ""
    echo "Scans logs/LOGS.md for SKILL_IMPROVEMENT entries and creates PRs for human review."
    echo ""
    echo "Options:"
    echo "  --check-only  Only scan and report, don't create PR"
    exit 1
}

CHECK_ONLY=false
if [[ "$1" == "--check-only" ]]; then
    CHECK_ONLY=true
fi

initialize_skill_improvements_file() {
    if [[ ! -f "$SKILL_IMPROVEMENTS_FILE" ]]; then
        cat > "$SKILL_IMPROVEMENTS_FILE" << 'EOF'
# SKILL_IMPROVEMENTS.md — Pending Skill Improvements

> This file tracks skill improvement suggestions from agents. The orchestrator scans this file to create PRs.

---

## Pending Improvements

*No pending improvements*

---

## Processed (PR Created)

| Timestamp | Skill | Improvement Type | PR URL | Status |
|-----------|-------|-------------------|--------|--------|
EOF
    fi
}

get_improvements() {
    local category="$1"
    local current_skill=""
    local current_type=""
    local current_suggestion=""
    local timestamp=""
    local agent=""
    
    while IFS= read -r line; do
        if [[ "$line" =~ ^##\ ([0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z) ]]; then
            timestamp="${BASH_REMATCH[1]}"
        elif [[ "$line" =~ ^###\ Agent:\ (.+) ]]; then
            agent="${BASH_REMATCH[1]}"
        elif [[ "$line" =~ ^###\ Category:\ SKILL_IMPROVEMENT ]]; then
            category="true"
        elif [[ "$line" =~ ^###\ Skill:\ (.+) ]]; then
            current_skill="${BASH_REMATCH[1]}"
        elif [[ "$line" =~ ^###\ Improvement\ Type:\ (.+) ]]; then
            current_type="${BASH_REMATCH[1]}"
        elif [[ "$line" =~ ^###\ Suggested\ Fix:\ (.+) ]]; then
            current_suggestion="${BASH_REMATCH[1]}"
        elif [[ "$line" =~ ^---$ ]] && [[ -n "$current_skill" ]]; then
            if [[ -n "$timestamp" ]] && [[ -n "$current_skill" ]]; then
                echo "$timestamp|$agent|$current_skill|$current_type|$current_suggestion"
            fi
            current_skill=""
            current_type=""
            current_suggestion=""
            timestamp=""
            agent=""
        fi
    done < "$LOGS_FILE"
}

check_pr_exists() {
    local skill="$1"
    local pr_title="skill: $skill - improvement from agent"
    
    if command -v gh &> /dev/null; then
        local existing_pr
        existing_pr=$(gh pr list --search "$pr_title" --json number --jq '.[0].number' 2>/dev/null || echo "")
        if [[ -n "$existing_pr" ]]; then
            echo "$existing_pr"
            return 0
        fi
    fi
    return 1
}

create_pr() {
    local skill="$1"
    local improvement_type="$2"
    local suggestion="$3"
    local agent="$4"
    
    local branch_name="skill-improvement/$(echo "$skill" | tr '/' '-' | tr '[:upper:]' '[:lower:]')-$(date -u +%Y%m%d-%H%M%S)"
    local pr_title="skill: Improve $skill - $improvement_type"
    local pr_body=$(cat << EOF
## Summary

Agent ($agent) identified an opportunity to improve skill during troubleshooting/cluster activities.

### Skill: $skill
### Improvement Type: $improvement_type
### Suggested By: $agent

### Description

$suggestion

### Category

This is a skill improvement PR created by the orchestrator based on agent feedback.

---

*This PR was automatically generated by the cluster-agent-swarm orchestrator.*
EOF
)

    echo "Creating branch: $branch_name"
    git checkout -b "$branch_name" 2>/dev/null || git checkout -b "$branch_name"
    
    cat >> "$SKILL_IMPROVEMENTS_FILE" << EOF

## $(date -u +%Y-%m-%dT%H:%M:%SZ)

### Skill: $skill
### Type: $improvement_type
### Agent: $agent
### Suggestion: $suggestion
### Status: PR_PENDING
EOF

    echo "To create PR manually, run:"
    echo "git push -u origin $branch_name"
    echo "gh pr create --title '$pr_title' --body '$pr_body'"
    
    git checkout main 2>/dev/null || git checkout master
    
    echo "PR created for skill improvement: $skill"
}

scan_and_process() {
    initialize_skill_improvements_file
    
    echo "Scanning $LOGS_FILE for SKILL_IMPROVEMENT entries..."
    
    local improvements
    improvements=$(get_improvements)
    
    if [[ -z "$improvements" ]]; then
        echo "No SKILL_IMPROVEMENT entries found."
        return 0
    fi
    
    echo "Found $(echo "$improvements" | wc -l) improvement entries"
    
    while IFS='|' read -r timestamp agent skill type suggestion; do
        [[ -z "$skill" ]] && continue
        
        echo ""
        echo "---"
        echo "Timestamp: $timestamp"
        echo "Agent: $agent"
        echo "Skill: $skill"
        echo "Type: $type"
        echo "Suggestion: $suggestion"
        
        if [[ "$CHECK_ONLY" == "true" ]]; then
            echo "[CHECK-ONLY] Would create PR for: $skill"
            continue
        fi
        
        if check_pr_exists "$skill"; then
            echo "PR already exists for $skill, skipping."
            continue
        fi
        
        create_pr "$skill" "$type" "$suggestion" "$agent"
        
    done <<< "$improvements"
}

main() {
    cd "$REPO_ROOT"
    
    if [[ ! -f "$LOGS_FILE" ]]; then
        echo "Error: LOGS.md not found at $LOGS_FILE"
        exit 1
    fi
    
    scan_and_process
}

main
