"""DID identity creation (wraps ANP).

[INPUT]: hostname, path_prefix, proof_purpose, domain, services
[OUTPUT]: DIDIdentity, create_identity(), load_private_key()
[POS]: Wraps ANP's create_did_wba_document() to provide key-bound DID
       identity creation; when enable_e2ee=True, also generates key-2 (secp256r1 signing)
       and key-3 (X25519 agreement) key pairs

[PROTOCOL]:
1. Update this header when logic changes
2. Check the folder's CLAUDE.md after updates
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass, field
from typing import Any

from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.serialization import load_pem_private_key

from anp.authentication import create_did_wba_document


@dataclass
class DIDIdentity:
    """Complete DID identity information."""

    did: str
    did_document: dict[str, Any]  # Contains proof (generated by ANP)
    private_key_pem: bytes  # PEM-encoded secp256k1 private key
    public_key_pem: bytes  # PEM-encoded public key
    user_id: str | None = field(default=None)  # Populated after registration
    jwt_token: str | None = field(default=None)  # Populated after WBA authentication
    e2ee_signing_private_pem: bytes | None = field(default=None)   # key-2 secp256r1
    e2ee_signing_public_pem: bytes | None = field(default=None)
    e2ee_agreement_private_pem: bytes | None = field(default=None) # key-3 X25519
    e2ee_agreement_public_pem: bytes | None = field(default=None)

    @property
    def unique_id(self) -> str:
        """Extract unique_id from DID (last path segment).

        For example, did:wba:localhost:user:abc123 -> abc123
        """
        return self.did.rsplit(":", 1)[-1]

    def get_private_key(self) -> ec.EllipticCurvePrivateKey:
        """Load secp256k1 private key object from PEM."""
        return load_private_key(self.private_key_pem)


def create_identity(
    hostname: str,
    path_prefix: list[str] | None = None,
    proof_purpose: str = "authentication",
    domain: str | None = None,
    challenge: str | None = None,
    services: list[dict[str, Any]] | None = None,
) -> DIDIdentity:
    """Create a key-bound DID identity (secp256k1 key pair + DID document + proof).

    Uses ANP's create_did_wba_document() to generate a complete DID document.
    First generates a temporary document to extract the key identifier (kid) from the
    public key JWK, then regenerates the final document with the kid appended to the
    path segments to create a key-bound DID.

    Args:
        hostname: Domain name for the DID.
        path_prefix: DID path prefix, e.g., ["user"] (default) or ["agent"].
            Final DID will be did:wba:<hostname>:<prefix>:k1_<kid>
        proof_purpose: Proof purpose (default "authentication", used for registration).
        domain: Service domain bound to the proof (verified by the server).
        challenge: Proof nonce (auto-generated by default, for replay prevention).
        services: Custom service entry list. Each item is a dict containing "id", "type",
            "serviceEndpoint". If "id" starts with "#", the DID prefix is automatically
            prepended. All services are written into the document before proof signing.

    Returns:
        DIDIdentity (did_document contains ANP-generated proof)
    """
    if challenge is None:
        challenge = secrets.token_hex(16)

    # Step 1: Generate temporary document to extract kid
    temp_doc, temp_keys = create_did_wba_document(
        hostname=hostname,
        path_segments=path_prefix or ["user"],
        proof_purpose=proof_purpose,
        domain=domain,
        challenge=challenge,
        services=services,
    )

    # Step 2: Extract kid from the first verification method
    kid = temp_doc["verificationMethod"][0]["publicKeyJwk"]["kid"]
    # Use k1_ prefix to indicate secp256k1 key
    key_id = f"k1_{kid}"

    # Step 3: Regenerate document with kid appended to path
    final_path_segments = (path_prefix or ["user"]) + [key_id]
    did_document, keys = create_did_wba_document(
        hostname=hostname,
        path_segments=final_path_segments,
        proof_purpose=proof_purpose,
        domain=domain,
        challenge=challenge,
        services=services,
    )

    private_key_pem, public_key_pem = keys["key-1"]

    # E2EE keys (generated by default when enable_e2ee=True in ANP)
    e2ee_signing_private_pem: bytes | None = None
    e2ee_signing_public_pem: bytes | None = None
    e2ee_agreement_private_pem: bytes | None = None
    e2ee_agreement_public_pem: bytes | None = None
    if "key-2" in keys:
        e2ee_signing_private_pem, e2ee_signing_public_pem = keys["key-2"]
    if "key-3" in keys:
        e2ee_agreement_private_pem, e2ee_agreement_public_pem = keys["key-3"]

    return DIDIdentity(
        did=did_document["id"],
        did_document=did_document,
        private_key_pem=private_key_pem,
        public_key_pem=public_key_pem,
        e2ee_signing_private_pem=e2ee_signing_private_pem,
        e2ee_signing_public_pem=e2ee_signing_public_pem,
        e2ee_agreement_private_pem=e2ee_agreement_private_pem,
        e2ee_agreement_public_pem=e2ee_agreement_public_pem,
    )


def load_private_key(pem_bytes: bytes) -> ec.EllipticCurvePrivateKey:
    """Load private key from PEM bytes."""
    key = load_pem_private_key(pem_bytes, password=None)
    if not isinstance(key, ec.EllipticCurvePrivateKey):
        raise TypeError(f"Expected EllipticCurvePrivateKey, got {type(key).__name__}")
    return key


__all__ = ["DIDIdentity", "create_identity", "load_private_key"]
