#!/usr/bin/env python3
"""
Merge multiple slide MP4 videos into one final video.

Uses FFmpeg concat demuxer for zero-re-encoding merge (very fast).
Requires all input videos to have the same encoding parameters
(which is guaranteed when they come from compose_video.py).

Usage:
    # Merge specific slides
    python scripts/merge_videos.py --slides 1,2

    # Merge a range
    python scripts/merge_videos.py --slides 1-5

    # Merge all available slide videos
    python scripts/merge_videos.py

    # Custom output path
    python scripts/merge_videos.py --slides 1,2 --output output/video/merged.mp4
"""

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path


# ---- Project paths ----
PROJECT_ROOT = Path(__file__).resolve().parent.parent
VIDEO_DIR = PROJECT_ROOT / "output" / "video"


def parse_slide_range(slide_range: str) -> list[int]:
    """Parse '1-3' or '1,3,5' or '2' into sorted list of ints."""
    nums = set()
    for part in slide_range.split(","):
        part = part.strip()
        if "-" in part:
            start, end = part.split("-", 1)
            for n in range(int(start), int(end) + 1):
                nums.add(n)
        else:
            nums.add(int(part))
    return sorted(nums)


def find_slide_videos(video_dir: Path, slide_nums: list[int] = None) -> list[Path]:
    """
    Find slide video files in the given directory.

    Looks for files matching patterns:
      - preview_slides_N.mp4  (generated by --slides N)
      - slide_NN.mp4          (generated by --slide N)

    Returns sorted list of video paths.
    """
    found = {}

    for f in sorted(video_dir.glob("*.mp4")):
        name = f.stem

        # Match "preview_slides_N"
        if name.startswith("preview_slides_"):
            suffix = name.replace("preview_slides_", "")
            try:
                num = int(suffix)
                found[num] = f
                continue
            except ValueError:
                pass

        # Match "slide_NN"
        if name.startswith("slide_") and not name.startswith("slide_merged"):
            suffix = name.replace("slide_", "")
            try:
                num = int(suffix)
                found[num] = f
                continue
            except ValueError:
                pass

    # Filter by requested slide numbers
    if slide_nums:
        missing = [n for n in slide_nums if n not in found]
        if missing:
            print(f"[ERROR] Missing video files for slide(s): {missing}")
            print(f"[INFO]  Available: {sorted(found.keys())}")
            sys.exit(1)
        videos = [found[n] for n in slide_nums]
    else:
        videos = [found[n] for n in sorted(found.keys())]

    return videos


def probe_video_params(video_path: Path) -> dict:
    """
    Use ffprobe to get video stream parameters (width, height, fps, pix_fmt, codec).
    Returns dict with keys: width, height, r_frame_rate, pix_fmt, codec_name.
    """
    try:
        result = subprocess.run(
            [
                "ffprobe", "-v", "quiet",
                "-select_streams", "v:0",
                "-show_entries", "stream=width,height,r_frame_rate,pix_fmt,codec_name",
                "-of", "json",
                str(video_path),
            ],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            data = json.loads(result.stdout)
            streams = data.get("streams", [])
            if streams:
                return streams[0]
    except Exception as e:
        print(f"[WARN] ffprobe failed for {video_path}: {e}")
    return {}


def check_videos_compatible(video_paths: list[Path]) -> tuple[bool, dict]:
    """
    Check if all videos have the same encoding parameters.

    Returns:
        (compatible: bool, info: dict)
        info contains 'params' list and 'target_resolution' (max width x height found).
    """
    params_list = []
    max_w, max_h = 0, 0

    for v in video_paths:
        p = probe_video_params(v)
        params_list.append(p)
        w = int(p.get("width", 0))
        h = int(p.get("height", 0))
        max_w = max(max_w, w)
        max_h = max(max_h, h)

    # Check compatibility: same width, height, pixel format
    compatible = True
    ref = params_list[0] if params_list else {}
    for p in params_list[1:]:
        if (p.get("width") != ref.get("width") or
            p.get("height") != ref.get("height") or
            p.get("pix_fmt") != ref.get("pix_fmt")):
            compatible = False
            break

    info = {
        "params": params_list,
        "target_width": max_w,
        "target_height": max_h,
    }
    return compatible, info


def merge_videos(video_paths: list[Path], output_path: Path, reencode: bool = False) -> Path:
    """
    Merge multiple MP4 files into one using FFmpeg.

    If reencode=False (default), uses concat demuxer for zero-re-encoding (very fast).
    If reencode=True, uses concat filter (slower, but handles different formats).

    Automatically detects resolution/format mismatches and falls back to re-encoding.
    """
    if len(video_paths) == 0:
        print("[ERROR] No videos to merge!")
        sys.exit(1)

    if len(video_paths) == 1:
        print("[INFO] Only 1 video, copying directly...")
        import shutil
        output_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(video_paths[0], output_path)
        return output_path

    print(f"\n[INFO] Merging {len(video_paths)} videos...")
    for i, v in enumerate(video_paths, 1):
        size_mb = v.stat().st_size / (1024 * 1024)
        print(f"  {i}. {v.name} ({size_mb:.2f} MB)")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Auto-detect compatibility
    if not reencode:
        compatible, info = check_videos_compatible(video_paths)
        if not compatible:
            print(f"\n[WARN] Videos have different parameters! Auto-switching to re-encode mode.")
            for i, p in enumerate(info["params"], 1):
                print(f"  {i}. {p.get('width')}x{p.get('height')} {p.get('pix_fmt')} {p.get('codec_name')}")
            print(f"  → Target resolution: {info['target_width']}x{info['target_height']}")
            reencode = True

    if not reencode:
        # Method 1: FFmpeg concat demuxer (zero re-encoding, fast)
        print(f"\n[INFO] Using FFmpeg concat demuxer (no re-encoding)...")

        # Create temporary file list
        with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as f:
            for v in video_paths:
                # FFmpeg concat requires 'file' directive with absolute path
                f.write(f"file '{v.resolve()}'\n")
            filelist = f.name

        try:
            tmp_output = output_path.with_suffix(".tmp.mp4")
            cmd = [
                "ffmpeg", "-y",
                "-f", "concat",
                "-safe", "0",
                "-i", filelist,
                "-c", "copy",
                "-avoid_negative_ts", "make_zero",
                "-movflags", "+faststart",
                str(tmp_output),
            ]
            print(f"[INFO] Running: {' '.join(cmd[:6])} ... {output_path.name}")

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                print(f"[ERROR] FFmpeg concat failed!")
                print(f"  stderr: {result.stderr[-500:]}")
                tmp_output.unlink(missing_ok=True)
                # Fall back to re-encoding
                print(f"[INFO] Falling back to re-encoding method...")
                return merge_videos(video_paths, output_path, reencode=True)

            # Post-process: fix start_pts offset caused by AAC encoder delay / edit list
            # Re-mux with -video_track_timescale to strip edit lists and ensure PTS starts at 0
            fix_cmd = [
                "ffmpeg", "-y",
                "-i", str(tmp_output),
                "-c", "copy",
                "-fflags", "+genpts",
                "-movflags", "+faststart+negative_cts_offsets",
                str(output_path),
            ]
            fix_result = subprocess.run(fix_cmd, capture_output=True, text=True)
            tmp_output.unlink(missing_ok=True)

            if fix_result.returncode != 0:
                print(f"[WARN] Post-process remux failed, using concat output directly")
                # If fix failed, just rename tmp to final
                if tmp_output.exists():
                    tmp_output.rename(output_path)
        finally:
            Path(filelist).unlink(missing_ok=True)
    else:
        # Method 2: FFmpeg concat filter with scale (re-encodes, slower but flexible)
        # Determine target resolution
        _, info = check_videos_compatible(video_paths)
        target_w = info["target_width"]
        target_h = info["target_height"]

        print(f"\n[INFO] Using FFmpeg concat filter (re-encoding to {target_w}x{target_h})...")

        inputs = []
        filter_parts = []
        for i, v in enumerate(video_paths):
            inputs.extend(["-i", str(v)])
            # Scale each input to target resolution, pad if needed to handle aspect ratio
            filter_parts.append(
                f"[{i}:v]scale={target_w}:{target_h}:force_original_aspect_ratio=decrease,"
                f"pad={target_w}:{target_h}:(ow-iw)/2:(oh-ih)/2,"
                f"setsar=1[v{i}]"
            )
            filter_parts.append(f"[{i}:a]aresample=async=1[a{i}]")

        # Build concat input: must interleave video and audio streams [v0][a0][v1][a1]...
        interleaved = "".join(f"[v{i}][a{i}]" for i in range(len(video_paths)))
        filter_parts.append(
            f"{interleaved}concat=n={len(video_paths)}:v=1:a=1[outv][outa]"
        )

        filter_str = ";".join(filter_parts)

        cmd = [
            "ffmpeg", "-y",
            *inputs,
            "-filter_complex", filter_str,
            "-map", "[outv]",
            "-map", "[outa]",
            "-c:v", "libx264",
            "-crf", "18",
            "-preset", "fast",
            "-c:a", "aac",
            "-pix_fmt", "yuv420p",
            "-bf", "0",
            "-movflags", "+faststart",
            str(output_path),
        ]
        print(f"[INFO] Running ffmpeg with concat filter...")

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print(f"[ERROR] FFmpeg concat filter failed!")
            print(f"  stderr: {result.stderr[-500:]}")
            sys.exit(1)

    # Report result
    if output_path.exists():
        size_mb = output_path.stat().st_size / (1024 * 1024)
        print(f"\n{'='*60}")
        print(f"  ✅ Merged video created!")
        print(f"  Output: {output_path}")
        print(f"  Size:   {size_mb:.2f} MB")

        # Get duration via ffprobe
        try:
            probe = subprocess.run(
                ["ffprobe", "-v", "quiet",
                 "-show_entries", "format=duration",
                 "-of", "default=noprint_wrappers=1:nokey=1",
                 str(output_path)],
                capture_output=True, text=True,
            )
            if probe.returncode == 0:
                dur = float(probe.stdout.strip())
                minutes = int(dur) // 60
                secs = dur - minutes * 60
                print(f"  Duration: {minutes}m {secs:.1f}s" if minutes else f"  Duration: {secs:.1f}s")
        except Exception:
            pass

        print(f"{'='*60}\n")
    else:
        print(f"[ERROR] Output file not created: {output_path}")
        sys.exit(1)

    return output_path


def main():
    parser = argparse.ArgumentParser(
        description="Merge multiple slide MP4 videos into one using FFmpeg"
    )
    parser.add_argument(
        "--slides",
        type=str,
        default=None,
        help="Slides to merge (e.g., --slides 1-3 or --slides 1,2,5). Default: all available.",
    )
    parser.add_argument(
        "--video-dir",
        type=str,
        default=str(VIDEO_DIR),
        help=f"Directory containing slide videos (default: {VIDEO_DIR})",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Output file path. Default: output/video/merged_slides_X_Y.mp4",
    )
    parser.add_argument(
        "--reencode",
        action="store_true",
        help="Force re-encoding (slower, use if concat demuxer fails)",
    )
    args = parser.parse_args()

    video_dir = Path(args.video_dir)

    # Parse slide range
    slide_nums = None
    if args.slides:
        slide_nums = parse_slide_range(args.slides)

    # Find videos
    videos = find_slide_videos(video_dir, slide_nums)

    if not videos:
        print("[ERROR] No slide videos found!")
        print(f"[INFO] Searched in: {video_dir}")
        sys.exit(1)

    # Determine output path
    if args.output:
        output_path = Path(args.output)
    else:
        if slide_nums:
            label = f"{slide_nums[0]}_{slide_nums[-1]}"
        else:
            # Auto-detect range from found videos
            label = "all"
        output_path = video_dir / f"merged_slides_{label}.mp4"

    print(f"\n{'='*60}")
    print(f"  Video Merger: Combine Slide Videos → Single MP4")
    print(f"{'='*60}")
    print(f"  Video dir:   {video_dir}")
    print(f"  Slides:      {slide_nums or 'all'}")
    print(f"  Input count: {len(videos)}")
    print(f"  Method:      {'re-encode' if args.reencode else 'auto (concat if compatible, else re-encode)'}")
    print(f"  Output:      {output_path}")
    print(f"{'='*60}")

    # Merge
    merge_videos(videos, output_path, reencode=args.reencode)


if __name__ == "__main__":
    main()